### ISSUE TITLE
Linux Based Machines - TacticalRMM

### ISSUE THREAD

**Issue by daygle** [wh1te909/tacticalrmm#1003]
**Is your feature request related to a problem? Please describe.**
Unable to add Linux based machines in TacticalRMM.

**Describe the solution you'd like**
Ability to be able to add/control Ubuntu desktop from TacticalRMM. It is my understanding that only Windows machines are able to be added. Would like to see the ability for Linux machines able to be added.

**Describe alternatives you've considered**
I understand that you are able to use Mesh to control the machines as an alternate.

**Comment by wh1te909** [comment]
linux agents are already done and will be in the next release which should drop in a few days

**Comment by daygle** [comment]
Great! Thanks for letting me know.

Love the application by the way!
