### ISSUE TITLE
Feature Request: Version Number

### ISSUE THREAD

**Issue by jlydia** [wh1te909/tacticalrmm#102]
Is it possible to have the version number of Tactical displayed somewhere prominent on the UI?

**Comment by wh1te909** [comment]
Yes good request, I haven't added this yet because there still isn't an official version for the RMM (only for windows agent). I'll try to figure out a versioning system for now until we officially release.

**Comment by wh1te909** [comment]
this has been added in 06a69045bc931ccf6592acc572a004180eb9bcd1

**Comment by jlydia** [comment]
Looks great, thx!
