### ISSUE TITLE
Bug - Issue updating to agent v0.11.0

### ISSUE THREAD

**Issue by rtwright68** [wh1te909/tacticalrmm#103]
Did a couple new installs of v0.11.0 and it worked fine.
Updating agents causes them to go into a disconnected state.
Downloading the full EXE and running again fires the agent back up.  It does fail during the install due it finding the agent being already installed, but the agent starts reporting.  Odd!

**Comment by wh1te909** [comment]
Yea I screwed up pretty bad last night, had a tiny bug in the agent update method that I didn't catch. Ended up updating all my agents at once then all of them went disconnected too, windows service failing to start. Turns out all of them (64 bit OS) got the 32 bit agent instead of the 64 bit agent LOL. Thankfully only around 300 were online and got the botched update and was pretty simple to fix with salt but I am working on a proper fix now. Not sure exactly when you updated, but I did temporarily hardcore the 64 bit agent for updates around 7 hours ago until I properly fix.

**Comment by wh1te909** [comment]
btw if you ever have to manually update an agent, need to stop the ```tacticalagent``` and ```checkrunner``` windows services first otherwise the installer will fail to replace all the files cuz they are still open and running.

**Comment by rtwright68** [comment]
> Yea I screwed up pretty bad last night, had a tiny bug in the agent update method that I didn't catch. Ended up updating all my agents at once then all of them went disconnected too, windows service failing to start. Turns out all of them (64 bit OS) got the 32 bit agent instead of the 64 bit agent LOL. Thankfully only around 300 were online and got the botched update and was pretty simple to fix with salt but I am working on a proper fix now. Not sure exactly when you updated, but I did temporarily hardcore the 64 bit agent for updates around 7 hours ago until I properly fix.

I did update some earlier, and manually fixed them.  I have some left but not a huge amount. Should I run the update script again?

**Comment by rtwright68** [comment]
> btw if you ever have to manually update an agent, need to stop the `tacticalagent` and `checkrunner` windows services first otherwise the installer will fail to replace all the files cuz they are still open and running.

Thanks, I will make a note of that!

**Comment by rtwright68** [comment]
Disregard my dumb reply before, I did update again and the agents are updating.

**Comment by wh1te909** [comment]
I am going to release a new agent soon with bugfix so you can hold off for now on updating until that's released I'll let you know when.

**Comment by wh1te909** [comment]
ok agent 0.11.1 is out. disregard what I said earlier about having to stop those 2 services before manual updating. you can now just run ```winagent-vX.X.X.exe``` now and it will take care of stopping and starting those services.
