### ISSUE TITLE
Feature Request - Sort by alpha in Update Agent screen, select by customer

### ISSUE THREAD

**Issue by rtwright68** [wh1te909/tacticalrmm#104]
Would be helpful to have the agent update screen sorted by Alpha and filter by selecting the customer.

**Comment by wh1te909** [comment]
Yes the agent update UI is terrible I know lol I never got around to making it better just did something fast. I will be adding auto agent update soon so should not need to use anymore but I'll improve the UI

**Comment by rtwright68** [comment]
naah, dont worry about updating it.  :-)
Especially, if auto-update is in our future.

**Comment by wh1te909** [comment]
auto update has been added

**Comment by rtwright68** [comment]
Awesome thanks!
