### ISSUE TITLE
Feature Request: 2FA for all Mesh sessions

### ISSUE THREAD

**Issue by meyerje** [wh1te909/tacticalrmm#105]
Our regulatory requirements need 2FA for all authenticated sessions.  I'd like to see 2FA implemented for all "Take Control" / Mesh sessions ran from the front end (rmm.*).

**Comment by jlydia** [comment]
I know of no commercial product, Teamviewer, Connectwise, Cloudberry, or any other VNC client that provides 2FA for each remote connection.

A 2FA authentication from the initial login as is being done now, should be sufficient.

The only way to implement what your "regulatory requirements" want, would be for you to configure 2FA on your desktops *independently* of Tactical. This way anyone logging into your desktops will be required to enter their 2FA code.

**Comment by meyerje** [comment]
The issue comes up because they are two separate products, MeshCentral vs TacticalRMM.  MeshCentral supports 2FA on the account.  Right now TacticalRMM is using the API to initiate a session with an account and token.  What I'm asking for is a prompt that uses an end users Mesh 2FA to authenticate the take control option.

**Comment by wh1te909** [comment]
@jlydia that's true but see @meyerje's response above, tacticalrmm and meshcentral are 2 completely separate products and you can run tacticalrmm without meshcentral. I am just integrating with meshcentral that way I don't have to write my own teamviewer replacement from scratch. If someone were to get the password for your meshcentral website, they could login directly to mesh.yourwebsite.com without needing any 2 factor and then take control of any computer. 

I just tested this however by enabling 2 factor for mesh. Apparently login token overrides 2 factor, last time I tested it was not working and take control in tacticalrmm was broken but seems like it's been fixed on meshcentral side. So you can now enable 2 factor for meshcentral and that will satisfy the 2 factor requirement for mesh. And there is no way to generate a mesh login token without being logged into tacticalrmm which already enforces 2 factor so I think we're good here.

**Comment by jlydia** [comment]
After more description of the issue, I clearly understand what was being asked now.
