### ISSUE TITLE
Feature Request: Audit table with export for all platform activity

### ISSUE THREAD

**Issue by meyerje** [wh1te909/tacticalrmm#106]
Due to regulatory requirements we would need all activity logged to a central audit table that is at minimum exportable to a csv / excel file. This would include all activity from users and system.

**Comment by bradhawkins85** [comment]
I almost put in a feature request for this myself last week.

**Comment by wh1te909** [comment]
@sadnub has done some awesome work implementing this in https://github.com/wh1te909/tacticalrmm/pull/115
still items to be added to the audit log but the ground work has been setup and most things already being logged to the audit database. please try it out and let us know any bugs you find.
