### ISSUE TITLE
Feature Request: auto update software using chocolatey

### ISSUE THREAD

**Issue by dinger1986** [wh1te909/tacticalrmm#110]
It would be good if software other than Microsoft software can be maintained at the newest version. I have found this https://chocolatey.org/packages/choco-upgrade-all-at#files can it be integrated?

**Comment by wh1te909** [comment]
Good request I have been planning to add this eventually. Although chocolatey can only update software that was installed via chocolatey, at least in the free version. I think the paid version can upgrade all software even if it wasn't installed with choco.

**Comment by dinger1986** [comment]
Ok.

So a way round that I guess would be to reinstall software with choco, is that possible? I’m sure that could be scripted as well. As in if it’s there already and needs updated reinstall with choco.

I’ll do some reading.


Daniel Lamb

Technical Director

[cid:logo_2094e808-adcc-455a-a5fd-54265dc137fa.jpg]<http://www.flonix.co.uk/>

Flonix Limited
Willowview
Redgorton
Perth
PH1 3EL

Phone: 01738 500400

http://www.flonix.co.uk

Company Reg: SC341802

[cid:fb_11c7c55d-b85e-4b3e-b8d8-daabbed1905e.png]<https://www.facebook.com/Flonixltd/>





________________________________

**Comment by dinger1986** [comment]
Reading more into this and testing as well, installing an already installed bit of software with choco allows me to then update using choco, guess then this and my other choco request kinda works together, if you can select multiple software and then reinstall it then having an update button or being able to schedule it would work.

**Comment by bradhawkins85** [comment]
@dinger1986 
Try this powershell, I am using it to upgrade packages currently.
Basically gets a list of outdated packages then kills the processes for any apps that are outdated to prevent the upgrade from being blocked.

I will work on adding support for force re-installing packages that are installed but not via chocolatey in the future, if its possible.

`$outdated = choco outdated
$outdated
if ($outdated -match 'GoogleChrome') {
    Start-Process -FilePath taskkill -ArgumentList "-f -t -im chrome.exe"
}

if ($outdated -match 'winrar') {
    Start-Process -FilePath taskkill -ArgumentList "-f -t -im winrar.exe"
}

if ($outdated -match 'firefox') {
    Start-Process -FilePath taskkill -ArgumentList "-f -t -im firefox.exe"
}

if ($outdated -match 'msedge') {
    Start-Process -FilePath taskkill -ArgumentList "-f -t -im msedge.exe"

}

&choco upgrade all -y`

**Comment by dinger1986** [comment]
Going to close this as can be looked at once winget is installed
