### ISSUE TITLE
Update didn't work?

### ISSUE THREAD

**Issue by kb8zgl** [wh1te909/tacticalrmm#113]
I recently ran the update.sh just to make sure I was up to date.  After running it, I couldn't access the RMM any longer.  So, I rolled it back via my snapshot.  However, now it seems like new clients can't checkin (tried to install a few new ones and they didn't show up).  Not sure where to go next.  Recommendations?

**Comment by dinger1986** [comment]
Just checking did it keep on saying your 2fa code was invalid? If so mine did that after the update.

Just had to refresh the page and I logged in fine, then logged out and back on and was working fine.

I don’t know about your current position but you could try upgrading again and see if it goes in after a refresh (if you had the same behaviour as I did)


Daniel Lamb

Technical Director

[cid:logo_2094e808-adcc-455a-a5fd-54265dc137fa.jpg]<http://www.flonix.co.uk/>

Flonix Limited
Willowview
Redgorton
Perth
PH1 3EL

Phone: 01738 500400

http://www.flonix.co.uk

Company Reg: SC341802

[cid:fb_11c7c55d-b85e-4b3e-b8d8-daabbed1905e.png]<https://www.facebook.com/Flonixltd/>





________________________________

**Comment by wh1te909** [comment]
there have been some breaking changes recently, and newer agents won't work with and older rmm. please DM me on discord and would like to screenshare and see exactly where the update.sh is failing

**Comment by kb8zgl** [comment]
I just ran update.sh again and here is the entire capture to see if it is clear what happened.  The issue is, it says Bad Credentials (with what I know are my correct credentials - so I can't login).
[RMMUpdate.zip](https://github.com/wh1te909/tacticalrmm/files/5252486/RMMUpdate.zip)

**Comment by dinger1986** [comment]
Is it asking for 2fa?


Daniel Lamb

Technical Director

[cid:logo_2094e808-adcc-455a-a5fd-54265dc137fa.jpg]<http://www.flonix.co.uk/>

Flonix Limited
Willowview
Redgorton
Perth
PH1 3EL

Phone: 01738 500400

http://www.flonix.co.uk

Company Reg: SC341802

[cid:fb_11c7c55d-b85e-4b3e-b8d8-daabbed1905e.png]<https://www.facebook.com/Flonixltd/>





________________________________

**Comment by kb8zgl** [comment]
No it doesn't pop up the 2fa window.  Mike

**Comment by wh1te909** [comment]
output of update.sh looks good. bad credentials is just the generic error, the issue is something with the nginx config. if you open your browser's dev tools and try to login you'll probably see an error about access to CORS origin denied or something like that. I'll need to see all your configs to see where the CORS error is. Please DM me on discord

**Comment by kb8zgl** [comment]
Issue appears to be that I ran update.sh as my username instead of the tactical user.  Rerunning now.  Thanks for pointing me in the right direction.
