### ISSUE TITLE
Feature Request: Alerts to Webhook

### ISSUE THREAD

**Issue by netwalker0099** [wh1te909/tacticalrmm#116]
Would it be possible to get alerts sent to webhooks for teams / discord instead of just email and SMS.

**Comment by wh1te909** [comment]
pretty cool never thought of that. def will work on adding it!

**Comment by sadnub** [comment]
The ability to specify and use alert details in a script will be added in the next release. With this you can run a script on alert failure or resolve. This script can hit an API to create tickets or send custom alerts.

**Comment by wh1te909** [comment]
Released in 0.6.3
