### ISSUE TITLE
Feature Request: Add Message to Event Check alert

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#117]
Can you please add the message from an event log check failure email instead of just that a particular event ID was detected.

**Comment by wh1te909** [comment]
done, can you test and lmk if looks good or needs tweaks ty

**Comment by bradhawkins85** [comment]
Working well, haven't received many alerts but a 6008 Unexpected shutdown has <pre> and </pre> before and after the message, not an issue but would be good if they can be removed eventually.

**Comment by wh1te909** [comment]
thanks fixed in https://github.com/wh1te909/tacticalrmm/commit/6364cae47599acc812e525f1dd6b5a600dc90566
