### ISSUE TITLE
Installation Stuck

### ISSUE THREAD

**Issue by Erdju** [wh1te909/tacticalrmm#122]
Hi,

First of all thanks for this great project. 
I am having a problem while installing.

I am installing on a Ubuntu LTS 20.04 with the script provided.

The installation goes on a loop at  Mesh Central Not Ready Yet. I left it on for a while waiting because I am trying it on a free tier machine on Amazon so I though it might have been slow. 

If you have any solutions it would be appreciated.
Thanks
![cpu util](https://user-images.githubusercontent.com/5808334/94706688-2f8afb00-034b-11eb-9f1e-7f3be457df01.png)
![notr](https://user-images.githubusercontent.com/5808334/94706691-30bc2800-034b-11eb-9691-b12fe6fefa5e.png)

**Comment by saulens22** [comment]
Maybe it's because AWS gives less than required 4GB of RAM? My own VPS has 8GB, but it stays fixed at 4GB. Maybe it's hard requirement?

Try running `systemctl status meshcentral` and check output for errors.

**Comment by wh1te909** [comment]
Correct, installation will get stuck around that point because it literally runs out of RAM. 
Bare minimum for a fresh install is 2GB with 0 agents.

**Comment by Erdju** [comment]
Thanks a lot guys. It was the free tier so its probably the ram.  Will try on a new machine with more ram tomorrow.

**Comment by wh1te909** [comment]
np! please re-open tomorrow if still have issues

**Comment by dinger1986** [comment]
On AWS I would pay attention to the disk IOPS as well, low IOPS is slow disks, off the top of my head a desktop SSD is roundabout 44,000 IOPS, some AWS disks are far below that. I ran a test on an old server in my office with 7200rpm drives in raid 5 and the IOPS on that is only about 1000 and it was slow!!

**Comment by wh1te909** [comment]
@dinger1986 great point, I avoid AWS like the plague, their low end VM's are terribly slow cuz of the limits they place on disk IO. For the same price on vultr or buyvm etc you can get ssd's with thousands of more iops and no stupid limits. And yea biggest bottleneck for the RMM is the harddrive, def would not run on anything other than an SSD.

**Comment by dinger1986** [comment]
Was going to say similar about other providers, just worried Jeff might be watching haha
