### ISSUE TITLE
Take Control - File Upload Question

### ISSUE THREAD

**Issue by KenGrant** [wh1te909/tacticalrmm#127]
Hi
Is there a method for uploading a file to the client PC from the Take Control screen
Thanks
Ken

**Comment by dinger1986** [comment]
in tactical, right click on the computer and click remote background then click file browser and connect

**Comment by dinger1986** [comment]
rather than asking or creating issues here, theres loads of people who would be happy to help on discord.
https://discord.gg/upGTkWp

not trying to discourage you on here, just thought some questions are probably answered quicker there

**Comment by KenGrant** [comment]
Fantastic - Thanks for the lightning response - much appreciated.
Ken

**Comment by KenGrant** [comment]
Thanks - Have got discord but have used it much. Have joined the. group discussion- thanks for the link.
