### ISSUE TITLE
Mesh - 2FA

### ISSUE THREAD

**Issue by KenGrant** [wh1te909/tacticalrmm#131]
With Mesh available on the url mesh.xxxx.net is it ok if I add using Account security ,Manage authenticator app to enable 2FA within the mesh interface  or does that break the rmm.xxx.net interface?

Just a bit nervous about having password only on the mesh site.

Ken

**Comment by wh1te909** [comment]
yea that's fine, it won't break anything see here https://github.com/wh1te909/tacticalrmm/issues/105

**Comment by KenGrant** [comment]
Yes thanks, have implemented 2FA - Sorry, I searched but missed 105.

Thanks

Ken
