### ISSUE TITLE
Feature Request: Show Last Logged In User Instead Of Blank

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#142]
Would it be possible to save/display the last logged in user in the event of no one being currently logged in to a device?
Perhaps format the User with _italics_ to signify the user is no longer logged in.
This will assist locating machines for after-hours maintenance as staff often log off after a shift but want work done

**Comment by wh1te909** [comment]
done try it out and lmk

**Comment by bradhawkins85** [comment]
Looks good to me, thank you.
