### ISSUE TITLE
Feature request: Session indicator for paranoid users

### ISSUE THREAD

**Issue by jlydia** [wh1te909/tacticalrmm#144]
How about a way to toggle a transparent popup on the remote desktop, allowing us to alert the user that we are connected and working on their issues. This would also double as a notice to those paranoid users weary of "big brother" spying on them.
(see attached idea)

![session_indicator](https://user-images.githubusercontent.com/43318108/97063382-70061f00-156d-11eb-8163-3238a067b38e.png)

**Comment by jlydia** [comment]
Nm, this should have been on the meshcentral product.

**Comment by wh1te909** [comment]
pretty sure it's already built in to meshcentral, u can try playing with the notification and consent settings in /meshcentral/meshcentral-data/config.json, see all of them here:
https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json
