### ISSUE TITLE
Adding checks to existing automation not affecting defaults

### ISSUE THREAD

**Issue by DjMagicFingers** [wh1te909/tacticalrmm#145]
I have setup default policy at the automation manager to perform 3 checks for every workstation.
After a while, I have found out about a new check that I wanted all workstations to perform - about bad blocks on disk so I have added the check to the policy that is defined as the default policy for workstations.

![image](https://user-images.githubusercontent.com/32017425/97092329-ebd69900-164b-11eb-93c9-4b336d577d53.png)

**The new check is not added to all existing devices.**

![image](https://user-images.githubusercontent.com/32017425/97092346-03158680-164c-11eb-861d-0babe2af0bbd.png)

**The new check I have added IS applied to any NEW device I am adding:**

![image](https://user-images.githubusercontent.com/32017425/97092350-0f99df00-164c-11eb-8cac-ea3b059bb3a5.png)

**Comment by bradhawkins85** [comment]
Check the view menu, pending actions. It should show something in there about tasks pending creation.
It can take a little while for new tasks and checks to be applied to existing agents.

**Comment by DjMagicFingers** [comment]
> Check the view menu, pending actions. It should show something in there about tasks pending creation.
> It can take a little while for new tasks and checks to be applied to existing agents.

@bradhawkins85 thank you, you are correct, it looks like the tasks are pending.

I should change this report to request some kind of visual alert on the dashboard to show that there are pending tasks - something like the new devices count icon.

![image](https://user-images.githubusercontent.com/32017425/97092694-a8315e80-164e-11eb-991d-1ff74933b527.png)

**Comment by bradhawkins85** [comment]
I believe a full dashboard is on the agenda eventually, would probably be best on there instead of cluttering the current interface.

**Comment by sadnub** [comment]
@DjMagicFingers In the next release, there is a new column on the agent table that will show if there are pending actions. You can also filter the table to only include agents with pending actions.
