### ISSUE TITLE
Feature Request: control client list order - alphabet or other

### ISSUE THREAD

**Issue by DjMagicFingers** [wh1te909/tacticalrmm#146]
While looking for the correct client to choose install agent for, the list of client is provided in FIFO order - by the order I have added clients.

A way to choose my preferred ordering - like in an Alphabetical ascending or descending order, would be much appreciated :)

![image](https://user-images.githubusercontent.com/32017425/97092529-4de3ce00-164d-11eb-88d1-8d87c18652cd.png)

**Comment by wh1te909** [comment]
Not sure if quasar supports choosing the order but I can at least make it sorted alphabetically

**Comment by wh1te909** [comment]
I made most dropdowns throughout the site sorted alphabetically now, please update and try it out.
