### ISSUE TITLE
Feature Request: Allow removing agent from MESH server at agent removal

### ISSUE THREAD

**Issue by DjMagicFingers** [wh1te909/tacticalrmm#147]
Currently, removing an agent from Tactical RMM does not remove it from the Mesh Central server.
That can cause a problem when re-installing the agent.

A tick box to allow removal of agent from Mesh Central when the user asks to remove Tactical RMM agent is requested.

**Comment by wh1te909** [comment]
There doesn't seem to be an official api in mesh for removing an agent, would have to delete it from the mongodb which I would rather not mess with. If you find one please let me know.

Mesh will handle duplicate agents with no issue, I have reinstalled agents up to 20 times in testing and it always creates a new agent in meshcentral with a different unique id. I have literally hundreds of duplicate agents in meshcentral that are offline cuz they've been reinstalled and no issues at all.

**Comment by DjMagicFingers** [comment]
Understood 👍 
I am using the separated Mesh panel to manage and allow clients to connect to their own devices with permissions only to connect to the allowed devices.
Having many instances of the same device, together with the fact that the same device name can belong to many cleints, can be a bit confusing but we will manage :)

**Comment by sadnub** [comment]
I might be able to use the wss setup to remove mesh agent. I'll mess around with this.

**Comment by dinger1986** [comment]
This is more a Mesh request, @DjMagicFingers I would suggest opening a ticket with them, for my business we just only show Online from the dropdown. @sadnub I will close this unless you want to look at this further?

**Comment by sadnub** [comment]
@dinger1986 I actually am porting the meshctrl javascript program over to python to allow a tighter integration between the two. It would make this possible, but it isn't really high on my priority list.

**Comment by dinger1986** [comment]
nice one! would be cool if it works but agreed low priority

**Comment by wh1te909** [comment]
we now have a clear way to interact with the mesh websocket so this should be do-able and will be in a future release

**Comment by silversword411** [comment]
`trace=1` ? :D

**Comment by wh1te909** [comment]
done will be in next release
