### ISSUE TITLE
Bug: Policies dont update

### ISSUE THREAD

**Issue by dinger1986** [wh1te909/tacticalrmm#151]
after applying a policy to a group of computers if the policy is updated ie scripts/checks added then they dont automatically show on the groups of computers. Currently I have got round this by having a blank policy, apply that then apply the original and the scripts/checks come through.

I have checked and if a script is applied to the group and its updated then this works properly.

**Comment by sadnub** [comment]
@dinger1986 I tried to replicate this, but wasn't able to. Can you lay out each policy that is applied to the group of computers, and which checks are applied to those policies? Then which types of checks are applied to each? A screenshot of the Policy Overview with the checks should be enough. Also need to know if default policies are set and the checks added to those.

Thanks!

**Comment by sadnub** [comment]
@dinger1986 Thanks for your help in tracking this down. I was able to fix the issue and I submitted a PR. Once that is merged you can update.
