### ISSUE TITLE
Feature Request: Favourite Scripts

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#152]
It would be handy if we could mark a script in Script Manager as favourites and have them appear in the right-click menu of an agent.
I find there are two or three scripts I run on a regular basis that would be nice to just be able to click and run.
Even if the scripts just ran as Fire and Forget to keep things simple.

**Comment by wh1te909** [comment]
sounds good, got some work to do still on scripts for your other requests so will try to do all

**Comment by wh1te909** [comment]
This has been added in release v0.2.17
