### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by plaxon** [wh1te909/tacticalrmm#155]
I would love to see the ability to add custom fields to hosts that can be filled by scripts that run on the hosts.
This would be useful to store some custom properties such as Bitlocker keys, licensing information, etc. that can be extracted using Powershell for example and be send to TacticalRMM.

**Comment by wh1te909** [comment]
Hi yes this is planned, there is a request for this already here https://github.com/wh1te909/tacticalrmm/issues/47

**Comment by wh1te909** [comment]
added in release 0.5.0
