### ISSUE TITLE
Feature Request: More info on Error Emails

### ISSUE THREAD

**Issue by dinger1986** [wh1te909/tacticalrmm#156]
It would be good to have more info on error emails for custom scripts, currently this is the details coming through:

EG on a speedtest script I get:
Client, Sitename, REBECCA-PC - Script Check: Speedtest Reporting Failed - Return code: 1, Error:

If I open RMM and go to output on the script the error in full is:

Standard Output
Time taken: 4 second(s) | Download Speed: 20 mbps
Current download speed at is 20 mbps which is below the minimum threshold of 30 mbps

Maybe I need to modify the scripts to output an error?

Thanks

**Comment by wh1te909** [comment]
done in 50a3c62c28cc6ea9f90bd54532d6f3cbc327bc18
I was only sending the stderr in email, just added stdout too
let me know if it works

**Comment by dinger1986** [comment]
perfect, updating now!

**Comment by dinger1986** [comment]
works great thanks!
