### ISSUE TITLE
Feature Request: Dark mode!

### ISSUE THREAD

**Issue by dniesen** [wh1te909/tacticalrmm#157]
It's a huge crowd pleaser!

**Comment by wh1te909** [comment]
LOL i know, this is definitely the biggest bug right now xD. nah seriously i been planning to add it just haven't got around yet but will do

**Comment by DjMagicFingers** [comment]
+1

**Comment by wh1te909** [comment]
just released dark mode in 0.1.6, plz upgrade and try it out

**Comment by dniesen** [comment]
it's beautiful!  I love the chosen colors, good definition, very easy on the eyes.

**Comment by jlydia** [comment]
I didn't think I would like it but you've got a great eye for color variations.
This look so good it will be my default, and I can count on one hand how many web-based programs I run in dark-mode.
Thx!
