### ISSUE TITLE
Audit logging for all script, patch, and check runs

### ISSUE THREAD

**Issue by meyerje** [wh1te909/tacticalrmm#158]
When you start getting hundreds of endpoints there is a necessity for seeing execution results from the patching, scripting, and check tasks that get executed. Could a page be built that shows a log of all these allowing you to drill into bulk and/or policy executed operations to see the multiple results.  I'd also want to single single execution results too.  The results should be sortable by column, filterable by status (maybe site as well), and definitely drillable when done in bulk.

Ultimately what I'm looking for is a way to efficiently review actions on scripts, tasks, and patching both in mass and on single execution runs.  Regardless, thank you for the efforts and work you've all put in!

**Comment by sadnub** [comment]
@meyerje All of that data except patching are captured in Audit Logging currently. The check runs will show up as a Check Object edit though. I could create another action that says Check Run to make it more clear. I also think being able to filter by action, site and client would be beneficial. Does that sound good?

You can also see bulk actions for automation policies by clicking on the status of the policy, but you can only see that at a per policy level. There really isn't a good way to see patching statuses in bulk at the moment. There will eventually be a dashboard to see status' of various things. The patching would definitely be on there. 

In the meantime, we could create custom filters for the agent table that will include only agents that are missing patches, patches pending, failed checks, online, offline, etc. 

Let me know what you think

**Comment by meyerje** [comment]
Yea these sound great.  Having one place we can check all of these results easily is important once you get the endpoint count up there.

**Comment by sadnub** [comment]
@meyerje I created a PR that adds the ability to filter more fields in the audit manager. I also added Check Run, Task Run, Bulk Action, and Agent Install entries. This will be in the next release and let me know if anything needs to be added or modified. 

Also the ability to filter the agent table has been added. You can filter by failing checks, missing patches, and reboot pending as well as whether or not the agent is online.
