### ISSUE TITLE
run task if schedule missed

### ISSUE THREAD

**Issue by wh1te909** [wh1te909/tacticalrmm#160]
from https://github.com/wh1te909/tacticalrmm/issues/109
> Also, allow setting the option on the scheduled task to run task immediately if scheduled start is missed.

**Comment by sadnub** [comment]
#161 should fix this

**Comment by wh1te909** [comment]
@bradhawkins85 this is released in version 0.1.1 (please download and run the latest update.sh script, now releasing version numbers for tacticalrmm and updates are based off master branch instead of develop)
