### ISSUE TITLE
Feature Request: User permissions per client

### ISSUE THREAD

**Issue by tozjerimiah** [wh1te909/tacticalrmm#162]
Would it be a relatively simple job to enable controls that allowed specific users to be assigned to specific clients?

**Comment by wh1te909** [comment]
I'll add it as an enhancement but definitely not simple so can't promise this will happen anytime soon.

**Comment by nr-plaxon** [comment]
A (simple) permission management that would allow for creating users without the option to run administrative tasks such as editing scripts, policies, etc. or deleting agents and other stuff would be great.

**Comment by saulens22** [comment]
+1 on this.

Role "Client admin"

- No "Global settings" menu
- No "Add" / "Delete" functions
- No "Upload MeshAgent"
- No "Edit clients"
- No "User administration"
- "Script manager" - edit only current user's scripts or no edit at all
- "Automation manager" ?

It would be enough to be useful and (relatively) simple to implement. Later on it could contain more granularity (for example, allow / deny patch management, software installation, access to specific clients / sites / machines...) 

Might look into this if I'll find some time.

**Comment by frankemann** [comment]
+1 for being able to get access fo specific Clients, Sites or Devices for specific Users.

As a MSP we often have individual IT-consultants we work with which have they own small customerbase and also would like to have a small RMM installed. Instead of using multiple RMM on the devices, they could log in to our RMM and just see their clients.

**Comment by cm-slu** [comment]
+1 for me too is a good idea.

**Comment by wh1te909** [comment]
released in 0.6.9

**Comment by cm-slu** [comment]
Hello, this is great.
I looked quickly but is it possible to prohibit a certain user from accessing a certain site?

**Comment by dinger1986** [comment]
Have you added a new user since doing the updates?

**Comment by cm-slu** [comment]
> Have you added a new user since doing the updates?
Yes

**Comment by wh1te909** [comment]
i've opened #494 to keep track of this

**Comment by dinger1986** [comment]
Cheers @wh1te909 was just about to add that ticket to this one!

**Comment by cm-slu** [comment]
Ok my English is not at the top, if I understand it is my request is in progress

**Comment by wh1te909** [comment]
> Ok my English is not at the top, if I understand it is my request is in progress

yes
