### ISSUE TITLE
Enhancement request: Display machine name at take control window

### ISSUE THREAD

**Issue by DjMagicFingers** [wh1te909/tacticalrmm#163]
While it is understood that Tactical RMM calls Mesh Central and uses it's remote control abilities, it still has the overall envelope that "hugs" Central's window.

Central shows only the asset number at the top of the window so if I am using more than one window at the same time, it gets very confusing to know who is controlled at the open window.

The enhancement requested is to add the device name and the group name to the top of the window  at the heading so it would be clear to which client the open window belongs and to which machine.

![image](https://user-images.githubusercontent.com/32017425/97817621-35eff800-1ca6-11eb-9101-c007ed235fbe.png)

![image](https://user-images.githubusercontent.com/32017425/97817640-59b33e00-1ca6-11eb-8506-c657d0acb565.png)

**Comment by wh1te909** [comment]
added in 2dc56d72f6fe2a134409391d8459af5ee76d2bdf, will be in the next release
