### ISSUE TITLE
Bug report: Checks not using selected timezone

### ISSUE THREAD

**Issue by dniesen** [wh1te909/tacticalrmm#166]
I have a default agent timezone selected in Global settings and confirmed a timezone is selected for each agent.  The "Last response" time seems to be displayed in the chosen timezone but the Checks Date/Time column appears to be showing UTC.

**Comment by wh1te909** [comment]
thanks yea there are still a few areas in the frontend where times are being displayed as UTC including the checks column and I believe automated tasks date column, it's on my list to convert all to agent timezones before sending to the frontend

**Comment by wh1te909** [comment]
fixed in 6bbc0987ad2aaad84083000c8a6490daa7896f1d, will be in the next release
