### ISSUE TITLE
Feature Request: when event clears or fault clears an alert is sent

### ISSUE THREAD

**Issue by dinger1986** [wh1te909/tacticalrmm#168]
in the event that an agent is in a errored state if this error clears an alert could be sent to just say the error has cleared.

**Comment by wh1te909** [comment]
got it, so basically like how an alert is send for an outage recovery now but for checks?

**Comment by dinger1986** [comment]
Yeah pretty much. So for example my internet speed test, it goes below a threshold but when I get to it it's back to normal again, it would be good know when it's gone back to normal.

**Comment by dinger1986** [comment]
Thanks guys!
