### ISSUE TITLE
Feature Request: Sort by checks results

### ISSUE THREAD

**Issue by DjMagicFingers** [wh1te909/tacticalrmm#169]
Having the option to sort by checks mark (green or red) will make it more convinient to see the devices that need help right now at the top of the screen.
Another option is having red-marked machines "jump" to the top of the list in the same manner that groups does.

![image](https://user-images.githubusercontent.com/32017425/98173941-a8f2ac00-1efc-11eb-8f97-ae823ff9d660.png)

**Comment by wh1te909** [comment]
done in 8c480b43e28600ed6fab5e3f55432d8020dabf29, will be in the next release
