### ISSUE TITLE
Enhancement request: Time window and random value for intervals

### ISSUE THREAD

**Issue by DjMagicFingers** [wh1te909/tacticalrmm#177]
When setting up a lot of devices to perform checks or run scripts by policy, the only current timing mechanism is by static amount of minutes.
That can cause an issue if 1000 devices perform speed test at the same time and the same intervals, sometimes tens of devices from the same location (same ISP).
The requested enhancement is to have better time frame definition.
For example, being able to setup static amount of minutes (let's say 120) PLUS random amount of minutes with some kind of limitation (let's say - randomly within another 120 minutes.

**Comment by wh1te909** [comment]
@DjMagicFingers this should now be possible with the latest task rework. you can set a random delay. let me know if it works for you
