### ISSUE TITLE
Feature Request: User Administratoin Groups / Permissions

### ISSUE THREAD

**Issue by Epod** [wh1te909/tacticalrmm#180]
Greetings,

At the current moment, it seems that all users have permissions to all sites. 

As a feature request, the implementation of a Group/Sub group system, allowing only those in specific groups to access sites in those groups would be a interesting path forward.

**Comment by wh1te909** [comment]
similar request in #162 it's planned

**Comment by dinger1986** [comment]
suggest closing this as same as #162
