### ISSUE TITLE
Feature request: Software repository

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#181]
Requesting the ability to add admin credentials to be able to install software from a shared drive on the network. Would use the saved credentials in TRMM to install any company specific third-party software from the network share to remote computers.

**Comment by dinger1986** [comment]
This should be achievable with custom fields now, just need to add the variables to your scripts

**Comment by dinger1986** [comment]
Did you test this using custom fields?

**Comment by subzdev** [comment]
Sorry didnt see your replies. I have not tried this yet, I'm not sure hpw to about it to be honest.

What I have done though is actually move software to a SharePoint doc library. I call it via invoke-webrequest and doenload it to thr computer first needing the software and install from there using the same script.

**Comment by sadnub** [comment]
The global keystore added in the latest release should also work with this.

**Comment by subzdev** [comment]
Global keystore essentially solved the issue. Closing.
