### ISSUE TITLE
UI issue: Able to Edit Agent Patch even when inheriting patch policy

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#185]
When right-clicking on an client and clicking Edit - Patches, even though the agent has inherited a patch policy I am  able to still edit and save the days of the week and frequency even though they are greyed out.

**Comment by sadnub** [comment]
@subzdev That is actually by design. Specifying it on the agent will override that setting in the patch policy.

**Comment by subzdev** [comment]
The options are greyed out and the mouse pointer turns to a red circle with a line in the middle symbolizing the non-ability to make edits, but you can actually edit it.

**Comment by sadnub** [comment]
I will check into this. Thanks for reporting!

**Comment by wh1te909** [comment]
fixed, will be in the next release either later tonight or tmrw
