### ISSUE TITLE
Checks and Tasks when moving an agent

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#188]
Do agent Checks and Tasks update when an agent is moved from one site to another.

E.G. When I am doing system builds I would like to use one agent installer for a Generic Site then move each machine to the correct customer later. or even if a client moves a machine from one office to another do the new policies update when the agent is moved in the RMM.

**Comment by sadnub** [comment]
I will need to check into that. As of right now I don't think that it does, but it is easy to add that functionality.

**Comment by wh1te909** [comment]
@bradhawkins85  done will be in the next release either later tonight or tmrw
