### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by CarFla** [wh1te909/tacticalrmm#189]
Hi

sorry man, i am stupid....

I was created two time a VM into Proxmox, and do the installation.

Then request i insert the username, but no password was request.

After the end of installation, I can go to rmm to login, but.... I insert username inserted during installation and password for meshCentral password, but indicate Bad Credential

Can you help me to how i  mistake?

Thank you

**Comment by wh1te909** [comment]
no problem lol

the username/password was during installation when it asked you to "Please create your login for the RMM website and django admin"

If you don't remember it, you can reset the password manually. Run the following commands in your terminal from the below screenshot. change "hunter2" to whatever password you want. Also if you don't remember the username, you can type `user.username` in the python shell before you do the `exit()` and it will show you your username

![changepassword](https://user-images.githubusercontent.com/7434746/100149925-b5ab5580-2e53-11eb-89d1-96614d934275.png)

**Comment by CarFla** [comment]
Thank you. But I think there is something else.

This is the answare

https://pastebin.com/bCeW2mh7

My VM is a CT on Proxmox. I try more time to install from install.sh. The installation stuck in all secret creation like:
DJANGO_SEKRET=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 80 | head -n 1)

I try different VM.

Thank you for support.

**Comment by wh1te909** [comment]
ah ok yea the install script is only tested on a fresh ubuntu 20.04 VM, not a proxmox lxc container
I have gotten it to work before on proxmox lxc but requires extra steps
I would recommend just using a full VM instead of ct

**Comment by CarFla** [comment]
Thank you. But I think there is something else.

This is the answare

https://pastebin.com/bCeW2mh7

My VM is a CT on Proxmox. I try more time to install from install.sh. The installation stuck in all secret creation like:
DJANGO_SEKRET=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 80 | head -n 1)

I try different VM.

Thank you for support.

**Comment by CarFla** [comment]
Ok, I install on VPS

Thank you
