### ISSUE TITLE
Agent shown "online" but machine powered off

### ISSUE THREAD

**Issue by juaromu** [wh1te909/tacticalrmm#191]
Hi:

First of, thanks a lot for this project. Been testing it for a few days now and it's awesome.
Not sure if not using proper settings but agents are displayed as online on the UI when they've actually been offline for hours.
I'm using the defaults for "check interval" and "send overdue alert".

Cheers

**Comment by wh1te909** [comment]
Hi, that's odd, you refreshed the web ui using the refresh button top left of page? Cuz the online status does not auto refresh. If it's still showing online and the computer is really turned off, then it has to be a timezone issue, check to see if the correct timezone is set on the agent.

The online/offline/overdue status is calculated like so:
online (green): means the RMM has received a ping from the agent in the last 6 minutes (the tacticalagent windows service on the agent checks in every 30 to 120 seconds)
offline (yellow): the last ping from the agent was greater than 6 minutes ago, but less than whatever time is set in the "send overdue alert after"
overdue (red): default 30 minutes or whatever you've set for the "send overdue alert" field

**Comment by juaromu** [comment]
It's the TZ indeed, funny though that didn't cross my mind.
Thanks a lot for your prompt answer and for the explanation as well, appreciated :-)
