### ISSUE TITLE
Linux Agent

### ISSUE THREAD

**Issue by CarFla** [wh1te909/tacticalrmm#192]
Hi

How Can I install an agent to linux?

I try to install from mesh link, but not view the client into RMM or mesh.

I try with Fedora.

Thank you

**Comment by wh1te909** [comment]
Linux is not supported yet :) eventually I will write an agent for linux first and then mac. Right now windows only

**Comment by CarFla** [comment]
Yes I just read Discord chat. 
But, it is possible to connect to mesh that al already installed and run? Do you have suggestion?

Thanks

**Comment by wh1te909** [comment]
you can install a mesh linux agent but there won't be any integration with the RMM, you'll have to manage them separately from mesh.yourwebsite.com
