### ISSUE TITLE
Fail to start nats-server

### ISSUE THREAD

**Issue by ltchurik** [wh1te909/tacticalrmm#201]
**sudo systemctl status nats.service**
● nats.service - NATS Server
     Loaded: loaded (/etc/systemd/system/nats.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2020-12-11 11:38:33 UTC; 3s ago
    Process: 5596 ExecStart=/usr/local/bin/nats-server -c /rmm/api/tacticalrmm/nats-rmm.conf (code=exited, status=1/FAILURE)
   Main PID: 5596 (code=exited, status=1/FAILURE)

Dec 11 11:38:33 it-rmm systemd[1]: nats.service: Main process exited, code=exited, status=1/FAILURE
Dec 11 11:38:33 it-rmm systemd[1]: nats.service: Failed with result 'exit-code'.

$ /usr/local/bin/nats-server -c /rmm/api/tacticalrmm/nats-rmm.conf
nats-server: Parse error on line 1: 'Invalid escape character 'u'. Only the following escape characters are allowed: \xXX, \t, \n, \r, \", \\.'

Platform Ubuntu 20.04

**Comment by wh1te909** [comment]
Hi can you please join our discord (link is on readme) and then privately DM me and send me this file `/rmm/api/tacticalrmm/nats-rmm.conf`
