### ISSUE TITLE
Feature Request : Unraid template

### ISSUE THREAD

**Issue by Nonobis** [wh1te909/tacticalrmm#202]
Hello,

Could you make an unraid template for quick et perfect install of tacticalrmm in Unraid ?
Thanks

And good work, i hope to stop using teamviewer in future ... for tacticalRmm !! soon i hope ^^

**Comment by wh1te909** [comment]
Hi, never used unraid so not familiar with what an unraid template is.
Doesn't unraid runs VMs though? Just create an ubuntu 20.04 VM and run the install script, no different than any other hypervisor.

**Comment by johnnyq** [comment]
@Nonobis I have never used UnRAID either @wh1te909 Maybe he means a docker container which is already available

**Comment by Nonobis** [comment]
I can't use your docker directly because unraid does not support docker-compose... I will check your install.sh or try to make a template.

thkx

**Comment by johnnyq** [comment]
@Nonobis As @wh1te909 said it is highly recommended in running this in a VM. 
Can this issue be closed?

**Comment by Nonobis** [comment]
yes
