### ISSUE TITLE
Successful install but doesn't load URL

### ISSUE THREAD

**Issue by digeratiexperts** [wh1te909/tacticalrmm#205]
I have installed on Vultr and my URL is hosted at cloudflare however I am unable to get to the URLs at the end. 
I have them saved in a text editor if you can assist I would appreciate it.

**Comment by wh1te909** [comment]
Ok I just ran through an install in vultr to make sure it's just cloudflare not vultr and mine works.

So wipe the VM and install again but first turn off the orange cloud icon and caching for the 3 subdomains, you can turn them back on after install

![rmmvultr](https://user-images.githubusercontent.com/7434746/102028023-db45c380-3d5c-11eb-809e-62134c196bf4.PNG)

**Comment by wh1te909** [comment]
once we get rid of the saltstack dependency (which is coming soon) you won't need 4gb anymore, 2 should be enough. you can prolly get away with 2 right now, just monitor the vm and restart the `salt-master` and `salt-api` systemd services once in a while when memory gets near max. dont go lower than 2 tho. of course also depends on how many agents you plan to add, 2gb without saltstack should be enough for a few hundred agents, once you start adding more though you'll prolly need to up the ram
