### ISSUE TITLE
Checks

### ISSUE THREAD

**Issue by yiannislas** [wh1te909/tacticalrmm#207]
when i am choosing a server and trying to add windows service check, nothing happens. All the other checks i can add normally, i tested it on chrome and edge

**Comment by wh1te909** [comment]
Hi yes this was a bug, it was fixed recently so make sure to update your rmm to latest version and that will get your agents on version 1.1.11. For a quick fix now, you can right click on the agent > Remote Background. Then open the services tab, let it load once and then try to add a service check again.

**Comment by johnnyq** [comment]
I can confirm the latest update did fix the issue

**Comment by yiannislas** [comment]
Worked, thank you
