### ISSUE TITLE
Bug: Default Server/Workstation Policies Not Applying

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#208]
I have a default policy set for both servers and workstations via the global settings however when adding a check or task to these policies nothing changes on the agents checks/tasks.

I have tried removing and re-adding the default policy in global settings, I have also deleted and re-created the default policy and re-associated the default policy.

No issues show in the debug log.

**Comment by sadnub** [comment]
@bradhawkins85 Thanks for reporting! I was able to track down the issue you are seeing and opened a PR to fix this. Will be in the next release.
