### ISSUE TITLE
Enhancement request: Add an option to send script run results by email

### ISSUE THREAD

**Issue by DjMagicFingers** [wh1te909/tacticalrmm#212]
A tick-box to enable sending email with the results of running the script is requested.
Another option would be to input a specified email address, if different than default one and maybe also an option to add additional recipients to get the run results.

**Comment by wh1te909** [comment]
sounds good, will do!

**Comment by wh1te909** [comment]
Just to confirm, this would be for the "Run Script" fire and forget method from the agent's context menu, right?

**Comment by DjMagicFingers** [comment]
I think it would be best to add this to any script run, even if the operator can see results, they may be required to be reviewed later so having it sent to a mailbox would be great!

**Comment by wh1te909** [comment]
released in 0.2.21
