### ISSUE TITLE
Bad Credential after upgrade

### ISSUE THREAD

**Issue by CarFla** [wh1te909/tacticalrmm#215]
Hi

I upgrade Tactical RMM from 0.2.2 to 0.2.17

Upgrade seem to be ok, If i re-execute ./upgrade it tell me Already on latest version. Current version: 0.2.17 Latest version: 0.2.17.

But after that when i try to login, I recive the Bad Credential window.

Ok I try to change my password, so I try to do procedure for that, but when i execute user = User.objects.first() This is the error:
![immagine](https://user-images.githubusercontent.com/58566341/102599897-6b4d8980-411e-11eb-9991-1ab5dfaa7977.png)

What can I do?

Thank you

**Comment by bradhawkins85** [comment]
I've had this too on an earlier version.
First up, chest your browser cache and cookies then try and log in again. Also open the browsers console and post any errors in there that you receive.
I don't know if wh1te909 is available now to help but I'll try and help until he can get back. I'm tied up for a bit too but will check back later if I get a chance and see how you went.

**Comment by CarFla** [comment]
Thank you

I try with a different Browser to don't have cache problem.

The problem is that api website is not found:

![immagine](https://user-images.githubusercontent.com/58566341/102601386-64277b00-4120-11eb-8c7a-1b8b91b70865.png)

Damn me that want to upgrade! :(

**Comment by bradhawkins85** [comment]
Can you run the commands below on your server and post the output:
systemctl status rmm
service postgresql status
df -kh

**Comment by CarFla** [comment]
![immagine](https://user-images.githubusercontent.com/58566341/102602526-efedd700-4121-11eb-9754-b2cc0d9c5d15.png)
![immagine](https://user-images.githubusercontent.com/58566341/102602550-fb410280-4121-11eb-904f-04cf372fb6b1.png)
![immagine](https://user-images.githubusercontent.com/58566341/102602599-0c8a0f00-4122-11eb-8d29-db5ec5944a93.png)

**Comment by bradhawkins85** [comment]
The only other fix I have is to restart the services, try:

for i in celery celerybeat celery-winupdate rmm
do
sudo systemctl restart $i
done

Let me know if that helps

**Comment by CarFla** [comment]
Not help.

I try to force the upgrade removing from script version control.
I send Log of upgrade.sh

[log-upgrade.txt](https://github.com/wh1te909/tacticalrmm/files/5715852/log-upgrade.txt)

I hope that someone can understand the problem.

**Comment by sadnub** [comment]
@CarFla Looks like the frontend build didn't work. Try running this:
```
cd /rmm/web
npm update
npm run build
```

If that works without error run this to restart nginx `sudo systemctl restart nginx`

**Comment by sadnub** [comment]
I edited the above. Try npm install first

**Comment by CarFla** [comment]
EUREKA!!

Ok, this is my step:

npm install tell me that found 9 low severity vulnerabilities, 
so i run npm audit fix.
After that 
npm audit fix --force to resolve another 1 vulnerability
npm run build
Restart Nginx and ... no run RMM. 
Reboot system and... no run RMM

so i try to run upgrade.
Upgrade tshi time run without error, and ... boom, RMM is OK! username and password accepted!!

THANK YOU!!!!

**Comment by sadnub** [comment]
Awesome! Glad that worked out.
