### ISSUE TITLE
Server 2019 - Patching Behavior & Online/Offline not working.

### ISSUE THREAD

**Issue by Jonathan-Garber** [wh1te909/tacticalrmm#216]
**Patching Behavior**

Clean install of Server 2019, brand new machine.
No server roles configured, it does nothing right now but hold files on a shared drive.

Patch Behavior is weird...
RMM shows they were installed and has a timestamp. However Timestamps are off a bit, they jumped from 23:30 to 05:14 in the same update run and reboots. The only thing was the server crossed midnight during the patching but I would expect it to go 23:30 ish to 01:00 not jump to 05:00 hours.

RMM will show reboot pending but even after a reboot all patches still show as "pending install" in Windows Update.
I ran patch scan and install until there were no more shown as pending and no reboot pending was shown.
Then I rebooted manually & still the patches show as "pending install" in Windows Update.
So I went ahead and clicked install in windows update and it zipped through them and cleared the list. Then I clicked check updates again and it reported all up to date.

So it appears the updates were actually installed completely via RMM but Windows Update didn't get the memo here and kept showing them until I manually clicked to install them.

Is this due to how RMM handles patches or is it a Microsoft disconnect between patching via different commands vs the GUI options?

**Online / Offline**

Online/Offline doesn't work for this same server. MeshCentral will show when it is offline but no matter how many times I refresh RMM it still shows it green and online. Anything to check here?

Thanks.

**Comment by Jonathan-Garber** [comment]
Possibly related to here #191 
But I have confirmed the timezone is correct on the server2019 and the RMM Server. They are both set to America/New_York

**Comment by wh1te909** [comment]
Hi yes the rmm installs updates using the windows update API which doesn't appear to sync automatically with the GUI. Am rewriting the windows update module though so we'll see if it still happens once that's done.

**Comment by Jonathan-Garber** [comment]
Comment to close - Questions and Issues addressed.
