### ISSUE TITLE
Feature Request: SMART Disk Check and Reporting

### ISSUE THREAD

**Issue by johnnyq** [wh1te909/tacticalrmm#218]
This would be awesome if we can setup SMART DISK check to make sure disks are running good. Checking  for bad sectors, high temps, SSD Wearout etc

**Comment by dinger1986** [comment]
You can check this via the event viewer.

I can share my check disks script I run if you like? I keep on meaning to upload my scripts to the community scripts

**Comment by DjMagicFingers** [comment]
You can also use a script (look at the discord "scripts" tab - there is already a done script for this) to automatically check and report if something bad happens to your drives or your drive controllers.

**Comment by dinger1986** [comment]
# Checks local disks for errors reported in event viewer within the last 24 hours

$ErrorActionPreference= 'silentlycontinue'
$TimeSpan = (Get-Date) - (New-TimeSpan -Day 1)
if (Get-WinEvent -FilterHashtable @{LogName='system';ID='11','9','15','52','129','7','98';Level=2,3;ProviderName='*disk*','*storsvc*','*ntfs*';StartTime=$TimeSpan})

{
Write-Host "Disk errors detected please investigate"
Get-WinEvent -FilterHashtable @{LogName='system';ID='11','9','15','52','129','7','98';Level=2,3;ProviderName='*disk*','*storsvc*','*ntfs*';StartTime=$TimeSpan}
exit 1
}


else
{
Write-Host "Disks are Healthy"
exit 0
}


Exit $LASTEXITCODE

**Comment by dinger1986** [comment]
add that as a powershell script

**Comment by johnnyq** [comment]
@dinger1986 Thank you for sharing your code. I am looking forward to your scripts.

**Comment by dinger1986** [comment]
Think this has now been dealt with so can be closed?

**Comment by johnnyq** [comment]
Absolutely Closing this Thanks
