### ISSUE TITLE
Feature Request - Hide certain UI elements on conditions

### ISSUE THREAD

**Issue by johnnyq** [wh1te909/tacticalrmm#219]
For Example
Do not show the enable SMS checkbox next to each host if SMS is not enabled globally same with email.

When Client is selected on the left do not show the client field in the list view, same thing for site.

**Comment by azulskyknight** [comment]
Is there a way to change the primary grid view?

I'd love to add agent version, OS, and OS version to the columns of data being displayed.  The ability to customize this view would be handy too.  So we can start creating dashboards of agents with the views we need for specific tasks.

**Comment by tektrak** [comment]
On Kaseya's grid, I always liked seeing the user keyboard/mouse idle time. It wasn't perfect but it helped. 

I also like the ability to see the agent version and OS version as well. Right now I do a query in my Terminal to find agents that might have issues updating. And I can do a query to see potential OS upgrades needed.

I like seeing if a system is logged out. Is that what the username in italics means? If there were a separate dot in a column, you could sort by that if you wanted to see those users still logged in and may have documents open before rebooting a bunch of systems.

Most columns are currently sortable. I think it could be useful for all columns to be sortable. For example, I currently only have a few systems with SMS alerting. If I could sort that column, I could more easily review the set of systems to double check which ones have that enabled.

And maybe the pending patches indicator for a system could change while patches are actively being installed.
