### ISSUE TITLE
Feature Request: DNS Response Check

### ISSUE THREAD

**Issue by johnnyq** [wh1te909/tacticalrmm#220]
Add a check to check for DNS response time based on the current configured resolver and report if response is slow or name doesn't resolve this could help troubleshoot slow website loading if a DNS server is the issue. have the domain it checks configurable.

**Comment by dinger1986** [comment]
I'm sure PowerShell would do this for you. 

So you want it to show it it's longer than x time to resolve a dns query and to fail if it doesn't resolve the query? Is that right?

This is probably a script which could be written. Probably best discussing on discord.

**Comment by johnnyq** [comment]
@dinger1986 exactly this

**Comment by dinger1986** [comment]
I have written one for powershell, does this suit your needs?

Just upload to tactical scripts and  change $hostname and $time

Does a ping, checks it can resolve and then times the lookup.

## name of hostname to run DNS checks against please leave the name in brackets
$hostname = 'bbc.com'

## allowed time for DNS check to be done (Milliseconds)
$time = 100

write-host -NoNewLine "Verifying" $hostname " ... "

## Do a ping test to ensure hostname can be contacted

if (Test-Connection $hostname -Count 1 -ErrorAction SilentlyContinue) 
	{ 
	write-host "Ping test passed for $hostname"
	} 
else 
	{
	write-host "Ping Test Failed for $hostname" 
	exit 1
	}
	
## Test if the DNS record exists or not

try
	{  
	$dnscheck = [System.Net.DNS]::GetHostByName($hostname)
	$test = $true
	}  
catch
	{
	Write-Output "Unable to resolve DNS for $hostname"
	exit 1
	}
	
## Do some verification if DNS record exists

if($test)
	{

## Check time taken in Milliseconds to resolve hostname

	$start_time = Get-Date 
	nslookup $hostname
	$timetaken = $((Get-Date).Subtract($start_time).Milliseconds)
	Write-Output "Time taken: $timetaken Milliseconds"
if ($timetaken -ge $time) 
	{
	write-host "DNS lookup for $hostname took longer than $time Milliseconds"
	exit 1
	}
	else 
	{ 
	Write-Output "Everything appears fine with your DNS for $hostname" 
	exit 0
	}
	}


Exit $LASTEXITCODE

**Comment by johnnyq** [comment]
@dinger1986 Thanks a Lot! That's exactly what I was looking for, im sure this will help others too

**Comment by dinger1986** [comment]
No problems, if you check scripts on the tactical discord kyt has tidied it up quite a bit, mine works his is tidier!

**Comment by dinger1986** [comment]
Think this has now been dealt with?

**Comment by johnnyq** [comment]
Absolutely Closing this Thanks
