### ISSUE TITLE
installation subdomains

### ISSUE THREAD

**Issue by Shootify** [wh1te909/tacticalrmm#221]
Hello, thanks for a great software. During installation when creating A records, do i have to use mesh.mydomain.com, asking cuz i have meshcentral install poiting to remote.mydomain.com, so which one should i use. thanks

**Comment by dinger1986** [comment]
Do you mean you have a current meshcentral install on remote? Can always chat on the discord chat loads of people to help there!

**Comment by Shootify** [comment]
in the installation it says you have to create subdomain mesh.mydomain.com and a A record, since i have meshcentral up and running using remote.mydomain.com, do i still need to use mesh.mydomain.com ? thanks

**Comment by dinger1986** [comment]
So are you going to create a token to authenticate between your current meshcentral installation or create a new one?

If you are using a token and are happy doing that then that's not something I know about however if you are going to migrate machines across then create mesh.yourdomain and have it as a separate meshcentral server.

I have written a script (on the scripts channel on mesh discord) and which can be used along with task scheduler plugin on mesh to swap over to tactical.

**Comment by Shootify** [comment]
thanks for the help.

**Comment by dinger1986** [comment]
No problems, Think this has now been dealt with so can be closed?

**Comment by Shootify** [comment]
yes and once thank you!
