### ISSUE TITLE
Feature Request: Allow overdue alert faster than 5mins

### ISSUE THREAD

**Issue by dinger1986** [wh1te909/tacticalrmm#222]
I think originally it was 2mins but now its 5, ideally if a server goes off need to know immediately, 5 mins can be a long time during a working day.

Also would be good to change this from 30mins to a lower number globally.

We dont use it on every agent just specific ones which help us keep a better control of customers needs.

**Comment by wh1te909** [comment]
Sounds good, I was going to change the way the rmm keeps track of agent's online status so this should be easier to do once that's implemented. 

If you want to change the overdue alert time globally a quick way to do it is like this (for example 5 minutes):
```
cd /rmm/api/tacticalrmm/
source ../env/bin/activate
python manage.py shell
from agents.models import Agent
Agent.objects.all().update(overdue_time=5)
exit()
```

**Comment by wh1te909** [comment]
@dinger1986 the minimum offline is now 2 minutes and overdue is 3 minutes, do you need faster than this or is that enough? if need faster i'll need to get creative and rework some stuff

also u prolly already saw this but just in case, added some management commands to bulk edit the offline/overdue time: https://wh1te909.github.io/tacticalrmm/management_cmds/#bulk-update-agent-offlineoverdue-time

**Comment by dinger1986** [comment]
Yes perfect thanks!

Let's close this, sorry had meant to earlier!
