### ISSUE TITLE
allow any event log channel to be queried

### ISSUE THREAD

**Issue by bbrendon** [wh1te909/tacticalrmm#226]
Is it possible to change the event log query to "Event log channel" and allow us to write it in? 

For example a channel such as: 
`Microsoft-Windows-Windows Defender/Operational`

The regular "System" event log is the `System` channel 

![image](https://user-images.githubusercontent.com/6364477/103431554-93110880-4b86-11eb-9985-1571d8581f5e.png)

**Comment by dinger1986** [comment]
I achieved this using powershell to query the event viewer and report back

**Comment by dinger1986** [comment]
@bbrendon is this ok to close as can be achieved via powershell

**Comment by sadnub** [comment]
We don't plan on adding new checks or expanding existing checks since everything can essentially be accomplished with script checks. Check examples can be created and added to community script to offload the task of creating the script. I believe there might be a few that are there.
