### ISSUE TITLE
Feature Request - double-click on an Agent options

### ISSUE THREAD

**Issue by rtwright68** [wh1te909/tacticalrmm#232]
Would be cool to permit the double click to "Take Control" automatically.
Perhaps have a system-wide setting to set it to Edit Agent, Take Control, or Remote Background

**Comment by dinger1986** [comment]
Oh!!! I like that idea.

**Comment by wh1te909** [comment]
nice sounds good will add it

**Comment by wh1te909** [comment]
Released in 0.2.23. You can edit the double-click default action by clicking on username top right > Preferences
