### ISSUE TITLE
Checks not removed on policy change

### ISSUE THREAD

**Issue by azulskyknight** [wh1te909/tacticalrmm#233]
Tactical v0.2.21

Checks aren't being removed from the endpoints when the site's policies are changed.

Currently removing the checks requires deleting them from the policy in automation manager to clear them from any impacted devices.

**Comment by sadnub** [comment]
@azulskyknight I attempted to replicate this but was unable to. Can you tell me how the policies are set and how they are applied to the Client/Site?

Then the steps you take to come across the issue. 
Thanks!
