### ISSUE TITLE
sorting background process list by memory doesn't sort correctly

### ISSUE THREAD

**Issue by bbrendon** [wh1te909/tacticalrmm#234]
Checked against tasklist.exe and it's clearly not correct.

the most chrome process is using is 96 MB? Impossible.
Also some process with kb is in there which shouldn't be visible at the top.

![image](https://user-images.githubusercontent.com/6364477/103820661-99d5ca80-5021-11eb-9b6d-ac93bd8c9426.png)

**Comment by wh1te909** [comment]
Fixed in 0.3.0
