### ISSUE TITLE
ALT Key sticks & Type/Paste Clipboard doesn't paste correctly

### ISSUE THREAD

**Issue by Jonathan-Garber** [wh1te909/tacticalrmm#240]
If I have a remote control window open and I "ALT-TAB" to another window on my local machine. When I "ALT-Tab" back to the remote window the remote session has the "ALT" key stuck down/on. I can double tap "ALT" on my keyboard to resolve it in the remote window but it causes some major headaches. When I "ALT-TAB" back to the remote and try to type something, it starts bringing up whatever "ALT+Letter/Number" does in that OS. So I have accidentally done a handful of actions in error because this "ALT" key is stuck.

The "Type" function isn't working.
I click "Type" and put the string "2308809400498" into the window and send it to the remote in a text editor my result is "23080940498"

Example
Click "type" and enter the word "access" then send it.
The result is "aces"

**Comment by wh1te909** [comment]
Hi these are meshcentral issues so please open tickets in their repo, I see one already #2126 for a bug with the "type" function so they are already aware of that

**Comment by dinger1986** [comment]
Use clipboard rather than copy and paste.

Copy and paste is flawed because your keyboard layout isn't always the same as what's set on the server and that mucks it up, it's not so much a mesh bug as just keyboard layouts.

If you send the clipboard to notepad first and check it if it's a script that works better.

**Comment by Jonathan-Garber** [comment]
Yea I started using the clipboard option to avoid the copy/paste issues but the "ALT" key sticking down is really killing things. Such a strange behavior.

I'll close it here since it's MeshCentral and not TacticalRMM related. I wasn't even thinking about the MeshCentral part.
