### ISSUE TITLE
fresh install: Bad credentials

### ISSUE THREAD

**Issue by Servery** [wh1te909/tacticalrmm#248]
I can not initialy login using the credentials set up when installing.
![Firefox_Screenshot_2021-01-17T09-13-54 187Z](https://user-images.githubusercontent.com/3184297/104836771-9ad3eb00-58b0-11eb-98ba-c516839ca817.png)

I tried installing on Ubuntu, Debian.
I tried also installing docker verison.
I tried using diffrent complex passwords and unsernames.
I tried copy&pasting username/password and also typing ist in manually.

Is there anything I should try to do?

**Comment by dinger1986** [comment]
Are you using the linux username and password or the credentials setup during the tactical install?

**Comment by wh1te909** [comment]
it's probably DNS. open ure browsers dev console and paste a screenshot of the error

**Comment by Servery** [comment]
sorry...
I've found the issue: the subdomain api.example.com was not pointig to correct IP, so that login on rmm.example.org was not possible. (The browser console error was CORSDidNotSucceed)
