### ISSUE TITLE
Bug: Searching by computer name doesn't always return results

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#250]
When searching for a Computer Name in the search box the list only shows devices that has no user logged on or an actively logged on user.
When the agent has a remembered user / last user in italics the RMM does not display the agent when searching.

**Comment by wh1te909** [comment]
thanks! ive noticed this myself but never was able to figure out what exactly was causing it lol cuz was so random but this is great will fix!

**Comment by bradhawkins85** [comment]
ha ha, took me a while to figure it out too.
Also, the search box appears to be multi-line enabled (when using chrome at least) might be good to switch to single line?

**Comment by wh1te909** [comment]
Fixed in 0.3.2
Also made search box single line
