### ISSUE TITLE
Anybody  have any idea how to set this up in docker? Thanks

### ISSUE THREAD

**Issue by rhinopctec** [wh1te909/tacticalrmm#254]

**Comment by dinger1986** [comment]
Should be a guide in the readme, if not get in discord and I'm sure someone there will be able to help you!

**Comment by wh1te909** [comment]
@sadnub is still working on the install/update script for docker
for now you can follow the instructions in the docker readme to setup and test https://github.com/wh1te909/tacticalrmm/blob/develop/docker/readme.md
