### ISSUE TITLE
Feature request: allow installation without MeshCentral

### ISSUE THREAD

**Issue by I2700I** [wh1te909/tacticalrmm#256]
While I understand the point of being the be-all solution, it quite can be a simple install script option (like do you want to install or point to an existing one) in case there is already a fully running MeshCentral instance. Sure it can be pointed to the one later in the settings, but maybe there is a possibility of doing that beforehand?

**Comment by jlydia** [comment]
Hmmm, we pretty much like it the way it is.
This request just screams confusion.

**Comment by I2700I** [comment]
It does not. The RMM and MechCentral are not essential parts of each other and can be working separately. Therefore when a long established instance of MeshCentral exists, it is much easier to link the RMM to it rather than peer the MC servers or export/import the data.

**Comment by jlydia** [comment]
This also means you will have to perform dual entries for new TRMM devices doesn't it?

When you add a new device on TRMM, that process won't create a Mesh device in your "established instance".

**Comment by I2700I** [comment]
Have you seen the installation? It requires you to get the agent from MeshCentral and creates the second agent on top of it. Therefore there is absolutely no complications in performing the same action against the already established server.

**Comment by 12nick12** [comment]
I second this. I have a long running instance and wouldn’t mind be able to use it.

**Comment by wh1te909** [comment]
Hi guys yes this is already possible, you don't have to use the meshcentral that tactical installs if you already have another mesh server somewhere you can just use that. There will be a section in the upcoming docs with full instructions, for now please join the discord and scroll up a bit in general chat I posted instructions for someone on how to integrate with an existing mesh server

**Comment by I2700I** [comment]
> Hi guys yes this is already possible, you don't have to use the meshcentral that tactical installs if you already have another mesh server somewhere you can just use that. There will be a section in the upcoming docs with full instructions, for now please join the discord and scroll up a bit in general chat I posted instructions for someone on how to integrate with an existing mesh server

You're the real MVP!

**Comment by dinger1986** [comment]
So if you could install without installing mesh are you happy doing the manual steps to setup the auth tokens between the 2? That would be my biggest issue as not everyone who is deploying tactical is comfortable with Linux.

**Comment by I2700I** [comment]
Given the installer can automate it with the new instance, it most likely can automate it with the existing one as well.

**Comment by dinger1986** [comment]
it would need root access to the existing mesh server to create the token then copy that back and add that to tactical settings, would mostly like need to manually generate the login token on the existing mesh server

**Comment by I2700I** [comment]
I wouldn't mind them being separate entities at all tbh. Probably less of "one piece of glass" ease and beauty but also less dependencies to take care of.
