### ISSUE TITLE
install tacticalrmm in local network

### ISSUE THREAD

**Issue by mandelbrotmedia** [wh1te909/tacticalrmm#257]
is it possible to install tacticalrmm in a local network / onprem?
i tried the install script but got the follwing error:

----------------------------------------
Press Enter to ContinueWaiting for verification...
Challenge failed for domain xxxx.domain.com
dns-01 challenge for xxxx.domain.com
Cleaning up challenges
Some challenges have failed.
----------------------------------------

i think its because of the local network.
no DNS records

**Comment by wh1te909** [comment]
Hi, yes it's possible but you'll need a real domain that is publicly resolvable just to get the cert. No need to publicly expose any ports. 
You can get a free one from https://www.freenom.com/
After install, you'll need to make sure your 3 subdomains resolve to the private IP of the VM running the RMM if you want to keep everything internal.

**Comment by wh1te909** [comment]
closing, reopen if still issues
