### ISSUE TITLE
Sorting Last Response

### ISSUE THREAD

**Issue by nr-plaxon** [wh1te909/tacticalrmm#258]
Sorting Last Response is broken since Jan. 1st.

Most likely not too hard to fix?

<img width="139" alt="image" src="https://user-images.githubusercontent.com/75976239/105832909-c77eb580-5fc8-11eb-954d-9f17f5feaff4.png">

<img width="139" alt="image" src="https://user-images.githubusercontent.com/75976239/105832940-d2394a80-5fc8-11eb-958c-366ac156ed6b.png">

**Comment by wh1te909** [comment]
thanks! fixed in develop will be in next release

**Comment by wh1te909** [comment]
released in 0.4.1
