### ISSUE TITLE
Bug: WebUI does not follow timeout of Run Script

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#260]
When running a script, selecting Wait For Output and a timeout longer than 30 seconds the script continues to run but the web interface does not actually return an output once the script completes.
The interface appears to still wait for only 30 seconds before displaying a blank output.

**Comment by wh1te909** [comment]
can you paste the script you're using? I can't reproduce, I just tried with the following powershell script
```powershell
write-host "sleeping for 75"
start-sleep -s 75
write-host "finished"
```

and here is output

![testsleep](https://user-images.githubusercontent.com/7434746/106032468-5bae5280-6085-11eb-92d9-2b904de1ee9a.PNG)

**Comment by bradhawkins85** [comment]
I tried your script with the same settings and also get no output.
Here is the script I am using which I normally set to a 300-second timeout as it takes a while to install Salt.

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$OutPath = $env:TMP
$path = 'HKLM:\SOFTWARE\TacticalRMM'
$AgentID = (Get-ItemProperty $path).AgentPK
$MinionName = $env:COMPUTERNAME + '-' + $AgentID
$Master = (Get-ItemProperty $path).ApiURL

$url = "https://repo.saltstack.com/windows/Salt-Minion-Latest-Py3-AMD64-Setup.exe"
$output = "Salt-Minion-Latest-Py3-AMD64-Setup.exe"

Out-File -FilePath "c:\windows\temp\saltcustom" -InputObject ("master_tries: -1")
Out-File -FilePath "c:\windows\temp\saltcustom" -Append -InputObject "keysize: 2048"
Out-File -FilePath "c:\windows\temp\saltcustom" -Append -InputObject "multiprocessing: True"
Out-File -FilePath "c:\windows\temp\saltcustom" -Append -InputObject "output: json"
Out-File -FilePath "c:\windows\temp\saltcustom" -Append -InputObject "grains_cache: True"
Out-File -FilePath "c:\windows\temp\saltcustom" -Append -InputObject "grains_refresh_every: 180"
Out-File -FilePath "c:\windows\temp\saltcustom" -Append -InputObject "grains_cache_expiration: 86400"
Out-File -FilePath "c:\windows\temp\saltcustom" -Append -InputObject "enable_fqdn_grains: False"
Out-File -FilePath "c:\windows\temp\saltcustom" -Append -InputObject "log_level: error"

Try
{			
    if (Test-Path -Path "$OutPath\$output"){
    } else {
	$start_time = Get-Date
	$wc = New-Object System.Net.WebClient
	$wc.DownloadFile($url, "$OutPath\$output")
    }

	Write-Output "Time taken to download: $((Get-Date).Subtract($start_time).Seconds) second(s)"
    Start-Process -FilePath $OutPath\$output -ArgumentList "/S /master='$Master' /minion-name='$MinionName' /custom-config=c:\windows\temp\saltcustom" -Wait
    exit 0
}
Catch
{
    $ErrorMessage = $_.Exception.Message
    $FailedItem = $_.Exception.ItemName
    Write-Error -Message "$ErrorMessage $FailedItem"
    exit 1
}
Finally
{
    Remove-Item -Path $OutPath\$output
    Remove-Item -Path "c:\windows\temp\saltcustom"
}

**Comment by wh1te909** [comment]
can u try again with that test sleep script first
stop tacticalrpc service and then run the rpc service in debug mode manually from cmd
`net stop tacticalrpc`
`"C:\Program Files\TacticalAgent\tacticalrmm.exe" -m rpc -log debug -logto stdout`
then run script from web UI
should see any errors in the cmd window

**Comment by bradhawkins85** [comment]
C:\Windows\system32>"C:\Program Files\TacticalAgent\tacticalrmm.exe" -m rpc -log debug -logto stdout
time="2021-01-31T18:53:41+10:00" level=info msg="RPC service started"
time="2021-01-31T18:55:08+10:00" level=debug msg="sleeping for 75\nfinished\n"

Web UI stopped waiting for a reply after 50 seconds and just returned the normal blank result,

**Comment by bradhawkins85** [comment]
Would the console output be more useful from Chrome?

![image](https://user-images.githubusercontent.com/15325110/106382063-affc5e00-6408-11eb-9b53-557b7754b833.png)

**Comment by bradhawkins85** [comment]
So, my bad, my HAProxy is causing the issue.
Added manual host file entries to point to the local RMM IP and the Web UI does work as expected.

**Comment by wh1te909** [comment]
haha all good!
