### ISSUE TITLE
Display of non ASCII characters

### ISSUE THREAD

**Issue by nr-plaxon** [wh1te909/tacticalrmm#261]
Since 0.4.1. the display of non-ASCII character such as ä,ö,ü,ß, etc. in the usernames is broken:
<img width="145" alt="usernames" src="https://user-images.githubusercontent.com/75976239/106006409-7ac4d880-60b5-11eb-838c-168e6f2e9747.png">

**Comment by wh1te909** [comment]
thanks fixed, will be in the next agent. tested by creating a new user on win 10 with those chars in it

![asciifix](https://user-images.githubusercontent.com/7434746/106063251-bb6c2400-60ac-11eb-98be-7ffb441b96bd.PNG)
