### ISSUE TITLE
Feature request: view the last line of an script check output

### ISSUE THREAD

**Issue by ItzMxrcxl** [wh1te909/tacticalrmm#266]
It would be nice, if the last line of an script output could be displayed next to the Script check.

eg:
![image](https://user-images.githubusercontent.com/26329863/106359590-ff149700-6313-11eb-9621-1c6a4f5509ed.png)

**Comment by dinger1986** [comment]
Does last output not work?

**Comment by ItzMxrcxl** [comment]
No, everything works like a charm.

My idea is to display the last output in a separate column. So you see everything at once.
For the script execution there would be the last output row.

![image](https://user-images.githubusercontent.com/26329863/108599571-4382d800-7392-11eb-9f83-f9949641a067.png)
Eg. on the cpu/ram check, display the usage in 5min interval?

In my mind, this was already built in, but got removed in some past version.

I hope you can imagine, what my idea is.
Sorry if it was unclear at first.

**Comment by wh1te909** [comment]
Hi sounds good ya it used to be there but got removed, i'll add it back. Last line of script output will need to be truncated tho if too long so will just do first 30 chars or whatever

**Comment by sadnub** [comment]
I attempted adding this and it really messes with the column widths because the last line could be any length. I even tried truncating it and the information was cut off and wouldn't be very useful at 30 characters.
