### ISSUE TITLE
Update 0.3.3 to 0.4.5 - Agents don't appear to be updating

### ISSUE THREAD

**Issue by Jonathan-Garber** [wh1te909/tacticalrmm#267]
Following update.sh, I tried to update 0.3.3 to 0.4.5 expecting agents to update automatically but they don't seem to be updating? What is the delay on agents updating? Just wait longer here?

**Comment by wh1te909** [comment]
what versions are the agents that are not updating

**Comment by Jonathan-Garber** [comment]
Reporting as 1.2.1

I looked for some method of updating the entire system on step up from 0.3.3 to 0.4.0 first to get 0.4.0 and agent 1.3.0 but the update script from release 0.4.0 updates itself to latest release during run So update.sh forces the entire system to 0.4.5 regardless of where you get the update.sh script from.

**Comment by Jonathan-Garber** [comment]
I just had two agents jump to 1.3.0, should they jump to 1.4.1 on their own? They just took a while to get up to 1.3.0

**Comment by Jonathan-Garber** [comment]
Commenting to close, to prevent any confusion. The agents are updating they are just slow to update, made it look like something was wrong.

**Comment by wh1te909** [comment]
that's fine, the rmm will automatically take care of making sure agents first go to 1.3.0 before going any further, even on 0.4.5
so even if you do Agents > Update Agents > select all, even tho the version says 1.4.2 the rmm will still send the agent 1.3.0 first and then next time u do it will send the latest

there have been some changes to agent update recently, please read thru the discussion in ticket #262

**Comment by Jonathan-Garber** [comment]
This has been excellent work so far. Thanks.
