### ISSUE TITLE
Upgrade 0.4.6 - 0.4.7 - Agent Failed to update

### ISSUE THREAD

**Issue by Jonathan-Garber** [wh1te909/tacticalrmm#270]
Updated install 0.4.6/Agent 1.4.3 to 0.4.7/Agent 1.4.4
One system failed to update, dropped offline completely.
I uninstalled Tactical / Mesh manually from this machine
Then reinstalled from a fresh deployment .exe for Workstations
Agent checked back in then immediately fell offline. Tachical RMM Agent and RPC Services are stuck in "paused" state refuse to start/restart. Mesh agent is running though. No errors reported when trying to pause/start the services, they just go right back to paused.

Any pointers?

**Comment by Jonathan-Garber** [comment]
Commenting to close: Rebooting this specific machine seems to have been the answer. Not entirely sure where/why the process crashed with the automatic agent updating but it did.

**Comment by wh1te909** [comment]
to troubleshoot agent updates, look in `c:\windows\temp\tacticalrmmXXXXXXXX` where XXX are random numbers. There will be a txt file in there with a full log of the update process.

If the services are stuck in paused state then you can run them manually from cli to get the error
for the tactical agent service run
```"C:\Program Files\TacticalAgent\tacticalrmm.exe" -m winagentsvc -log debug -logto stdout```
and for the RPC service run
```"C:\Program Files\TacticalAgent\tacticalrmm.exe" -m rpc -log debug -logto stdout```

**Comment by Jonathan-Garber** [comment]
I'll keep this in mind if it happens again, I'll get logs.
