### ISSUE TITLE
Suspected Bug: 2 Factor QR Code Page

### ISSUE THREAD

**Issue by Jonathan-Garber** [wh1te909/tacticalrmm#271]
If a new user goes to logon to their account for the first time, they are shown a QR Code/2FA page to get their device setup to generate codes. If they for any reason close or cancel this page. They are stuck without being able to get back to it.

The logon process assumes they have an OTP code and asks for it from this point on. How do you get back to the QR/2FA page?
I can probably delete the account and re-create it to resolve it for now but wanted to report what I found.

**Comment by wh1te909** [comment]
right click on the user in Settings > User Administration and select "Reset 2 factor auth" and then when they attempt to login again they'll be redirected to the QR code page

**Comment by Jonathan-Garber** [comment]
Wow... I went into "Edit" and saw no options there. I didn't think to "Right-click" the darn thing.
