### ISSUE TITLE
Feature Request: Custom URL actions on clients

### ISSUE THREAD

**Issue by nr-plaxon** [wh1te909/tacticalrmm#277]
Custom URLs that accept values from custom fields could allow integration of other tools such as TeamViewer.

Example: A custom field named **TeamViewerID** could be created and assigned to a client by using the local command 

`tacticalrmm.exe --fieldname TeamViewerID --fieldvalue "123456789"`

This field (and all other custom fields) should be visible (ie. as a table, exportable as CSV) in a separate tab on the client in TRMM.

Next, we should be able to create custom URLs for web actions. These could be listed in a separate submenu on a right click on the client name, just like the "Run Favorited Scripts" menu:

<img width="288" alt="Bildschirmfoto 2021-02-16 um 10 06 15" src="https://user-images.githubusercontent.com/75976239/108042174-c24cdd80-703f-11eb-8855-57166d66f705.png">

A custom URL could be defined by using the custom variable created earlier:

`https://start.teamviewer.com/{{TeamViewerID}}`

which would result in

`https://start.teamviewer.com/123456789`

Having this as a clickable link in the a "Open Custom URL" submenu would allow integration of many tools that allow for URL schemas to run certain actions.

As a further enhancement, this could be modified to allow for calling REST APIs with GET and POST request and displaying / processing the results.

Custom field feature request: https://github.com/wh1te909/tacticalrmm/issues/155

**Comment by Omnicef** [comment]
While I do need this feature, it is not for TeamViewer... so I do not think it should be so specific. I plan on using it for osTicket and for Connectwise Control.

**Comment by Omnicef** [comment]
As far as placement... I'd be okay with it down in the Summary section as a clickable link.

**Comment by nr-plaxon** [comment]
> I agree as long as it can be generic. TeamViewerID is a good example. But I need it ffor other things such as osTicket and Connectwise Control.

This is meant to be configurable, so it could call any web link, be it osTicket, Connectwise Control, etc.

**Comment by Omnicef** [comment]
Got it. This would be great.

**Comment by sadnub** [comment]
This will be possible in the next release with url actions.

**Comment by wh1te909** [comment]
released in 0.6.9 https://wh1te909.github.io/tacticalrmm/functions/url_actions/
