### ISSUE TITLE
user management

### ISSUE THREAD

**Issue by aftechro** [wh1te909/tacticalrmm#278]
First of all, great project.

I`m asking this here cause i cant see any documentation.

How can i add users (as technicians) and give them access just to specific sites or specific pcs and restrict certain aspects and/or limit them to work with remote (take control) only option?

Any other permissions should be done by a higher level support agent

**Comment by wh1te909** [comment]
Hi, thanks! This is currently not possible but it is planned, see https://github.com/wh1te909/tacticalrmm/issues/162
For now all users have full permissions

**Comment by afsound** [comment]
That`s great! Thanks!

One other thing, can we generate the agent for linux in rmm.domain and to show the linux server in the server list?
I did use the mesh central mesh.domain and got the server there, but it doesn't shows in the rmm.domain panel

**Comment by wh1te909** [comment]
Hi, currently there are no linux or mac agents for tactical, only windows. Also planned :)
Meshcentral and tactical are 2 completely separate products and can be used independently, all I'm doing with mesh is wrapping it in an iframe inside the tactical UI. So until i make the linux agent you'll need to use meshcentral's web gui to manage any linux agents.

**Comment by aftechro** [comment]
Great, keep doing awesome work!
