### ISSUE TITLE
Bug: Automation Manager Not Showing All Policies

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#280]
Automation manager does not show all policies, list of policies is not scrollable.
![image](https://user-images.githubusercontent.com/15325110/108155998-9dce2f80-712b-11eb-9257-a9d7af9418aa.png)

Checks and Tasks tabs overlap with policy list.
![image](https://user-images.githubusercontent.com/15325110/108155868-5b0c5780-712b-11eb-893c-f2d08061c6cd.png)

RMM v0.4.9

**Comment by sadnub** [comment]
I just pushed a fix for this. Will be in the next release. Thanks for reporting!

**Comment by wh1te909** [comment]
released 0.4.10 let us know if good now
