### ISSUE TITLE
errors on install

### ISSUE THREAD

**Issue by aftechro** [wh1te909/tacticalrmm#281]
Bellow error on fresh install 0.4.9

Could not connect to apt.postgresql.org:443 (87.238.57.227), connection timed out Could not connect to apt.postgresql.org:443 (72.32.157.246), connection timed out Could not connect to apt.postgresql.org:443 (217.196.149.55), connection timed out Could not connect to apt.postgresql.org:443 (147.75.85.69), connection timed out

**Comment by bradhawkins85** [comment]
Can you PING apt.postgresql.org from your RMM server?
Sounds like a firewall issue on either the host or your router.

**Comment by aftechro** [comment]
That`s sorted! Thanks!
