### ISSUE TITLE
[Questions] Install via mesh central and 2fa on mesh central

### ISSUE THREAD

**Issue by 12nick12** [wh1te909/tacticalrmm#282]
My three questions are as follows

Since it uses MeshCentral as the backend is there any way to run this via MeshCentral and allow it to finish installing since the CMD gets killed before it's finished? 

Secondly, am I able to use the MeshCentral that this installs by itself? I have a couple Linux servers I'd like to add and I would just create a secondary user for them directly in MC. 

Thirdly, would we be able to add 2fa to the MC backend? I know the username/password are randomly generated, but I would love to throw 2fa on top of it. 

Thanks, so far this seem pretty awesome.

**Comment by wh1te909** [comment]
Hi, yea you can use an existing mesh terminal to install the tactical agent, just call the tactical installer like this `start rmm-xxxx.exe` that will spawn it in background so that wont get killed when mesh uninstalls itself.

Yes, the install script just installs meshcentral for you with some extra config.json settings to allow framing in iframe so that it can integrate into the tactical UI, but they are 2 completely separate products just running on the same box, u can use one without the other

And yes you can add 2fa to mesh, mesh's login token (which is what tactical uses to login to mesh without username/password) overrides mesh's 2fa so everything will still work after u enable 2fa on mesh

**Comment by 12nick12** [comment]
Awesome, thank you so much for this. 

Two more questions
Can I organize the devices in meshcentral to their own groups and would tactical still see them? 
Also, how does patch management work with this? This is just a general question. I never knew there was any sort of open source patch management software.

**Comment by 12nick12** [comment]
Also is there a way to switch the default view from servers to mixed or workstations?

**Comment by meyerje** [comment]
> Also is there a way to switch the default view from servers to mixed or workstations?

This is configurable in the top right of the RMM front end under your user preferences.

**Comment by 12nick12** [comment]
> > Also is there a way to switch the default view from servers to mixed or workstations?
> 
> This is configurable in the top right of the RMM front end under your user preferences.

Awesome, thank you so much. That worked.

**Comment by wh1te909** [comment]
> Awesome, thank you so much for this.
> 
> Two more questions
> Can I organize the devices in meshcentral to their own groups and would tactical still see them?
> Also, how does patch management work with this? This is just a general question. I never knew there was any sort of open source patch management software.

yes for organizing should be fine as long as the mesh user you're using for tactical integration has full admin rights and rights to access all device groups (you can always edit the user in tactical's UI in Settings > Global Settings > MeshCentral).
Tactical just needs the agent's meshnodeid, which the tactical agent gets by calling `meshagent.exe -nodeid` on the actual computer and then sends it to the RMM to store in the database, that's how it knows what mesh agent to render in the iframe.

Patch management is all handled by the tacticalagent, I just use the windows update API straight from microsoft to do updates.

**Comment by 12nick12** [comment]
Ah ok cool. 

One thing I did notice is that I can't right click on the updates to approve/deny unless I'm on the servers tab.

**Comment by wh1te909** [comment]
can you post a screenshot please of the UI with the patches tab shown. also open ure browsers dev tools and see if any errors in console

easier way than right clicking individually is to just create a patch policy from Settings > Automation Manager and then apply it to either entire client, site or individual agents.

**Comment by dinger1986** [comment]
@12nick12 can this be closed now?

**Comment by wh1te909** [comment]
closing, plz open new ticket for the patch management issue if still having it
