### ISSUE TITLE
Recommendation:  Move credentials for postgres DB in backup script to separate file 

### ISSUE THREAD

**Issue by knk90** [wh1te909/tacticalrmm#285]
Currently /rmm/backup.sh needs to be modified on every upgrade to include the postgres DB creds.  

Recommend these are read from a separate file or similar which does not get overwritten on every trmm update.

**Comment by dinger1986** [comment]
Download the backup file directly and store it in /home/your-user as the only reason its in /rmm/ is due to it doing git clone to there, you will see the install.sh file and others are in there as well.

wget https://raw.githubusercontent.com/wh1te909/tacticalrmm/master/backup.sh

**Comment by wh1te909** [comment]
@dinger1986 im gonna reopen, this is a good request cuz now if I update the backup script it requires you to redownload the latest one and then edit the username/password again. so if the creds are in a different file then the backup script can just be re-run without having to edit it again

**Comment by wh1te909** [comment]
ok so this is added, thank you @dinger1986 for writing the new grep command to grab the username/password from local_settings.py

@knk90 I've updated the documentation site with new instructions. You can just run both `backup.sh` and `restore.sh` without editing anything.
