### ISSUE TITLE
Feature request: allow client to download agent from website

### ISSUE THREAD

**Issue by aftechro** [wh1te909/tacticalrmm#287]
Is there any way to put the .msi/.exe/.ps1 of the agent to be available as downloadable install from the public website and all the clients who will download and run the installation to be placed in a default site that can be moved to the site needed afterwords?

For instance, on my website i have a section remote support, and i want to make available a downloadable file that client can run themselves.

**Comment by dinger1986** [comment]
Yes.

Create a deployment URL and then put the link on your site instead of the exe as the deployment URL should keep up to date.

**Comment by wh1te909** [comment]
Agents > Manage Deployments. Create a deployment then copy paste the link and there's your public website.

**Comment by wh1te909** [comment]
also for the deployment just create a client/site named "Default" or whatever and u can use that and then move the agent's into correct sites from the web UI

**Comment by dinger1986** [comment]
Yeah that's how we do it. Apart from using AAAincoming and site name is changeme. Works really well and just tidy out that "client" all the time.

**Comment by aftechro** [comment]
I managed to do the deployment link. So far so good... The problem is that when the user download the exe file, the antivirus will block the file and user cannot install it. Any other work around for this?

Also, how can I change the name of the agent? Instead to show rmm domain workstation rmm domain to show only remote company name

Thanks in advance!

**Comment by dinger1986** [comment]
So it's flagged as a virus. Aide an RMM kinda is a Trojan.

So the way to resolve this is getting certificates. This is expensive and time consuming and I know the Devs are working on this feel free to donate to help push this forward!

What we do in our company is get the customer to download and install mesh first then run a background task or locally on the machine to set the defender exceptions and then download rmm and install it. Happy to share that script with you.

Fixes the name issue as well doing it that way.

**Comment by aftechro** [comment]
Any chance to have the option when deploy the agent as power shell script?  I suppose I can try to do the ps1 file downloadable from the website and just set the script not to expire maybe? What you think? I never had issues with ps in the past... Just an idea...

**Comment by wh1te909** [comment]
yes you can create a deployment url with an expiry set to year 2030 or something. Then create a powershell script that simply downloads the exe from the deployment url with `Invoke-WebRequest` and calls it

**Comment by dinger1986** [comment]
I can give you a ps or bat script to run. Join the discord channel and I'll dm you it. I find ps scripts and bats get blocked by AV and windows as well as browsers
