### ISSUE TITLE
Issue: SSL Unsupported protocol

### ISSUE THREAD

**Issue by aftechro** [wh1te909/tacticalrmm#289]
Hi guys,

Trying to set the email for alterts with my smtp details, but when i hit save and test i get this error:

[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1123)

Any suggestion? Running rmm with latest version 

Also, i tried to access the Discord chat, but for some reason i cannot get access to it, i think i need an invite, not sure how that will work.

Thank you!

**Comment by dinger1986** [comment]
What email service are you using?

You should be able join the discord channel without an invite.

Link is in the readme.

**Comment by aftechro** [comment]
When i click on the chat url (https://discord.com/invite/upGTkWp) i get this:
![image](https://user-images.githubusercontent.com/38830718/108920431-8b249080-762c-11eb-98fe-f5b67f4e3116.png)

As mail service i`m using the hosting provider`s one. think is OX mail or something...

**Comment by dinger1986** [comment]
Have you got a discord account setup?

Who is your hosting provider?

**Comment by aftechro** [comment]
i dont have discord account

hosting provider is blacknight.com

**Comment by dinger1986** [comment]
If you setup an account first then follow the link you will get in fine.

From Black nights website:

Please ensure, when using encryption, that you set the following ports:
SMTP (Outgoing): 25 or 587 as an alternative.
Have you tried both?
Note: Set TLS/STARTTLS as the encryption type and NOT SSL (where available).
@wh1te909 is it SSL only rather than TLS?

**Comment by wh1te909** [comment]
@dinger1986 rmm uses TLS, not ssl so not sure why black night is not working, their instructions seem exactly the same as gmail or office365 which work fine

@aftechro here's the code that the rmm uses to send emails
https://github.com/wh1te909/tacticalrmm/blob/126be3827d3ce15399dcae76ca69cb80a12c863c/api/tacticalrmm/core/models.py#L173
and here is python's smtplib documentation
https://docs.python.org/3/library/smtplib.html
please play around with it and let us know if you can get it working

**Comment by aftechro** [comment]
That`s sorted with the TLS, thanks for your help!
