### ISSUE TITLE
Feature Request: Agent Migration to another Tactical Installation

### ISSUE THREAD

**Issue by johnnyq** [wh1te909/tacticalrmm#290]
The possibility to migrate RMM agents to another Tactical RMM Installation on another server. 
The options could be migrate all, migrate client, migrate site or migrate single device. 

This would prove useful if for example a client wants to move from their current MSP to another MSP or IT Company. This will allow the current MSP to migrate the client seamlessly to the new MSP that also has Tactical RMM.

Another scenario  if your company changes domain names for example smallITFirm.com to simpleMSP.com

**Comment by dinger1986** [comment]
yes, you can do this with a script, powershell or otherwise and then setup a task

**Comment by johnnyq** [comment]
that makes sense @dinger1986 I'll give it a test whirl. Thanks

**Comment by dinger1986** [comment]
This is the script I use to reinstall tactical and it could be used to move deployments as well.

powershell Set-ExecutionPolicy -ExecutionPolicy Unrestricted
powershell Add-MpPreference -ExclusionPath C:\TEMP\TRMM
powershell Add-MpPreference -ExclusionPath 'C:\Program Files\TacticalAgent\*'
powershell Add-MpPreference -ExclusionPath 'C:\Windows\Temp\winagent-v*.exe'
powershell Add-MpPreference -ExclusionPath 'C:\Program Files\Mesh Agent\*'
cd c:\temp\trmm
powershell Invoke-WebRequest "deployment URL" -Outfile tactical.exe
"C:\Program Files\TacticalAgent\unins000.exe" /VERYSILENT /SUPPRESSMSGBOXES /FORCECLOSEAPPLICATIONS
tactical.exe
powershell Remove-MpPreference -ExclusionPath C:\TEMP\TRMM

Let me know how it goes and we can maybe close this?

**Comment by dinger1986** [comment]
@johnnyq can we close this now?

**Comment by johnnyq** [comment]
absolutely
