### ISSUE TITLE
Bad credential

### ISSUE THREAD

**Issue by CarFla** [wh1te909/tacticalrmm#291]
I upgrade Tactical RMM yesterday.
I change the file for new version, and seems all ok.

But now when I try to enter with correct credential It indicate Bad Credential

I try to change password from env, check username that is right, password is right.

Postgres and nginx in up and running, 

I don't know what can I do...

**Comment by wh1te909** [comment]
try all steps here first then post back with your results
https://wh1te909.github.io/tacticalrmm/troubleshooting/

**Comment by CarFla** [comment]
I have to try many time to register let's encrypt certificate, because a TXT not properly propagate.

Tip: if TXT not propagate, insert 2 TXT with same value.

To verify propagation on dns you can use:
for i in $(dig your.domain ns +short); do echo "Checking $i"; dig @$i _acme-challenge.your.domain txt +short;echo ""; done

After add a second TXT it was ok

Many thanks to @wh1te909 for help
