### ISSUE TITLE
Feature request: Open multiple windows for remote access

### ISSUE THREAD

**Issue by aftechro** [wh1te909/tacticalrmm#294]
Hi guys,

Any chance that we can have for clients with multiple screens, to change the remote windows from all remote screens in a single window, to have multiple windows that can open each screen separate? 

Like screen 1 in windows 1, screen 2 in windows 2 and so on... seen this on logme in (multi windows, single windows, all windows)

Thank you!

**Comment by dinger1986** [comment]
This is an open request on meshcentrals GitHub, this isn't controlled by Tactical.

https://github.com/Ylianst/MeshCentral/issues/1795
