### ISSUE TITLE
Public IP for agent sometimes shows IPV6

### ISSUE THREAD

**Issue by bbrendon** [wh1te909/tacticalrmm#304]
I think this is happening mostly for remote agents.  I could care less about their IPV6 IP. I do care about their IPv4 IP  :)

I'm guessing the Windows API is just passing along the first thing it finds.

**Comment by bradhawkins85** [comment]
Not a fix but a workaround for now:
You can run the command below using Send Command on these agents to get the IPv4 address. 

nslookup myip.opendns.com. resolver1.opendns.com

**Comment by bbrendon** [comment]
I dug around and found where is is being done. No idea why because I dunno how to fix... except one idea.... remove ipv6 from icanhazip.tacticalrmm.io :)

I'm not sure how you tell go to prefer ipv4 over ipv6.

https://github.com/wh1te909/rmmagent/blob/1e54c45d23854232a4a3e5c0b71ca79ab1473e47/agent/utils.go#L27

**Comment by wh1te909** [comment]
hi the icanhaz code is here xD https://github.com/wh1te909/icanhazip/blob/master/main.go i'll change it to prefer ipv4 and only return v6 if it's really using v6 and has no v4

**Comment by bbrendon** [comment]
I was thinking the fix would be on the client. If it requests IPv6, then how can icanhaz know if it is dual stack ?  Unless maybe you have the client do two requests? One for ipv4 and one ipv6.

**Comment by wh1te909** [comment]
Hi changed it to prefer v4 and only return v6 if really not using v4, it will be in next rmm/agent release
