### ISSUE TITLE
Feature Request - ability to reset a user's 2FA settings

### ISSUE THREAD

**Issue by rtwright68** [wh1te909/tacticalrmm#306]
We had a user get a new smartphone and I had to delete their user and re-create them from scratch to re-enable 2FA.
Would be cool to be able to reset that status and have them re-add their 2FA themselves.

**Comment by dinger1986** [comment]
You can already do this.

Go to Settings, User Administration, Right Click on the user and select Reset Two-Factor Auth

**Comment by rtwright68** [comment]
Thanks, I feel like a dumb-ass, lol.
