### ISSUE TITLE
Feature Request: Custom port (instead of 4222)

### ISSUE THREAD

**Issue by Evo-c** [wh1te909/tacticalrmm#318]
It would be super helpful to be able to specify the port if possible, we have some sites that find it difficult to unblock ports so this would make life much easier.

If somehow it could work off 80 & 443 so we don't need to whitelist the port for new sites that would be amazing but looking over it I don't see how this is possible, I only ask in case someone has a clever idea on how to handle this even if additional servers are required.

**Comment by wh1te909** [comment]
Hi, 4222 is the default port for [NATS](https://docs.nats.io/). Doesn't need to be open at your sites, only wherever you're hosting the RMM.

You can always fork the rmm and agent and modify the code to change ports. There are instructions on the agent's github readme for compiling them yourself.

You're better off tho just getting a cheap VPS that has no restrictions. I recommend https://buyvm.net/
