### ISSUE TITLE
Feature Request - Auto Connect after opening Take Control

### ISSUE THREAD

**Issue by rtwright68** [wh1te909/tacticalrmm#320]
Not sure if this is even possible, but can the Connect happen automatically when launching Take Control?
As much as I bounce in and out of connections, it would save a little time.

A side question, if you leave a take control session without disconnecting, does that leave it open in Mesh or does it close automatically?  If it closes automatically, I'm wonder if that Connect/Disconnect button would be necessary at all?

Thanks!

**Comment by dinger1986** [comment]
The Connect part is build into Mesh not tactical, and you need to hit connect on mesh as well so I am sure it will be the same.

When you close the window the mesh connection is closed as well, so probably no need for disconnect but again thats a mesh thing.

There might be some sort of scripting thing that can be done, or it could be a request opened on mesh's github?

**Comment by wh1te909** [comment]
yes plz open this request in [meshcentral's](https://github.com/Ylianst/MeshCentral) repo. cannot script it to auto click due to browser security restrictions that prevent me changing stuff within iframes, so mesh needs to implement this
