### ISSUE TITLE
Have patch severity column match patch policy labels

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#326]
See image

![2021-03-16 10_08_33-Tactical RMM Patch consistency](https://user-images.githubusercontent.com/13395348/111323175-ff58bf80-863f-11eb-92cd-21c091793516.png)

**Comment by wh1te909** [comment]
It already matches, except for "Other" since the severity returned by the windows update API for "other" is just an empty string. I can make it just say "Other" if the field is blank

**Comment by silversword411** [comment]
Yeah, blank = Other messed me up yesterday. Would be nice to have the match :)
