### ISSUE TITLE
Feature Request: Make alert issues clickable

### ISSUE THREAD

**Issue by manc74** [wh1te909/tacticalrmm#332]
When there is an alert, there is a drop down showing a list of current alerts, as well as the full "view all alerts" display.  

It would be great if the host name was clickable to go to the host in the main screen, to save selecting the client/site then scrolling or searching for it.

**Comment by sadnub** [comment]
I think I can make this happen. Will work on it

**Comment by silversword411** [comment]
While you're in that area of the code, maybe add (on the left  so it's not clicked accidentally) a "clear all alerts" button. 

Saw another issue about alert spam coming up when rebooting server (haven't encountered it myself yet) but there might be occasions where you want to clear all alerts.

**Comment by sadnub** [comment]
This will be in the next release
