### ISSUE TITLE
Unable to upload MeshAgent to RMM

### ISSUE THREAD

**Issue by tedtms** [wh1te909/tacticalrmm#338]
**Server Info:**
 - OS: Ubuntu 20.04
 - Browser: Firefox & Chromium
 - RMM Version: v0.4.27

**Installation Method:**
  - [X] Standard
  - [ ] Docker

Hi! Just discovered the project, really intrigued and excited to get it working! I've got Tactical installed on Ubuntu, using an existing postgres db and an external nginx secure proxy, but otherwise vanilla. I can log into RMM but the issue comes with trying to upload the Agent. 

I've downloaded the latest agent from [the rmmagent release page](https://github.com/wh1te909/rmmagent/releases/tag/v1.4.13), but when I go to File > Upload MeshAgent and select the file, it says "Unable to upload".

Any help you can offer would be super appreciated! Thanks again for such a cool project!

Cheers,
Ted

**Comment by Omnicef** [comment]
The reason you're running to an issue, is because you need to upload the agent from your Mesh Central instance.

**Comment by tedtms** [comment]
@Omnicef Oh! How should I do that? And apologies if this is documented somewhere, I was following the installation Wiki but didn't see anything about this in there. Thanks for your quick reply!

**Comment by Omnicef** [comment]
Copied from the instructions...

A bunch of URLS / usernames / passwords will be printed out at the end of the install script. Save these somewhere safe. Recover them if you didn't

Copy the url for the meshagent exe (https://mesh.example.com), paste it in your browser and download the mesh agent:

Navigate to https://rmm.example.com and login with the username/password you created during install.

Once logged in, you will be redirected to the initial setup page.

Create your first client/site, choose the default timezone and then upload the mesh agent you just downloaded.

**Comment by Omnicef** [comment]
In a nutshell you get it from mesh.your_domain.com

**Comment by tedtms** [comment]
OK, I have a small update and a couple more questions:
- The reason I had Upload issues was because I was dumb and forgot to set client_max_body_size to something greater than 1MB. I can upload the agent now.
- Where do I download the agent from my meshcentral instance? I can log in but I'm admittedly unfamiliar with MC so I've so far been unable to find where I'm supposed to download the agent.
- If I'm supposed to download the agent from my MC instance, what's the point of the rmmagent that wh1te909 has available in his other repo?

**Comment by Omnicef** [comment]
You just need to upload the mesh agent once on your server. You only install the RMM agent to your client PCS/Servers. It uses mesh in the background. 
Download it from you mesh instance by clicking on add agent. Then log into your TacticalRMM instance and upload it there. It's only a one-time thing. Also, you may want to check out the Discord server for help as there is a support channel. There is a link on the github page for it.

**Comment by tedtms** [comment]
Great, thanks! Since my initial issue is solved, I'll mark this as closed and seek further help on the Discord if needed.

Cheers!
