### ISSUE TITLE
Assistance

### ISSUE THREAD

**Issue by dinger1986** [wh1te909/tacticalrmm#34]
Sorry to write this here but I want to help! I am
Not a programmer but run my own MSP in the UK, I would be keen if possible to help with a website and any other way I can. I can share my contact details if anyone wants.

Thanks,
Dinger1986

**Comment by wh1te909** [comment]
Hi thank you! Would be awesome if you could help test it out to find any bugs. We are using it in production at our MSP with over 600 endpoints so it's pretty stable at the moment, but the more endpoints can test it on will help with finding bugs.

I opened a group chat at https://discord.gg/upGTkWp if need help installing or anything

**Comment by kodemafia** [comment]
how to reset the username and password for rmm link. rmm.example.com

**Comment by kodemafia** [comment]
HOW TO CHANGE THE LOGO AND PRODUCT NAME

**Comment by wh1te909** [comment]
@kodemafia check discord I added instructions there for resetting password. for logo and product name it's hardcoded in at the moment so you'll need to upload your own favicon.ico and and then do a find and replace for "Tactical RMM" in the frontend files then rebuild the frontend
