### ISSUE TITLE
Feature Request: Add Creation date to manage deployment links screen

### ISSUE THREAD

**Issue by bbrendon** [wh1te909/tacticalrmm#340]
We're trying to track down what we currently believe are "rouge" agents joining. It would be useful to have a creation date on this screen.

![image](https://user-images.githubusercontent.com/6364477/112041489-aedfd700-8b03-11eb-8cbc-74b1833c2e75.png)

**Comment by wh1te909** [comment]
Hi, just to clarify, creation date of when the deployment was generated right? Cuz the actual exe is generated dynamically whenever the download link is accessed.

**Comment by bbrendon** [comment]
Yes. 

If anyone else reads this we believe the rogueness is from AV sandboxes running our installer.

**Comment by saulens22** [comment]
Can confirm. Some AV software runs EXEs in local / cloud sandbox, so it joins your RMM dashboard. You can safely delete them.

**Comment by wh1te909** [comment]
done will be in next release
