### ISSUE TITLE
Bad Credential after completing Dockerized new install with default and/or custom creds 

### ISSUE THREAD

**Issue by wiicode** [wh1te909/tacticalrmm#349]
**Server Info (please complete the following information):**
 - OS: Docker on Ubuntu 20.04
 - Browser: Chrome
 - RMM Version: unable to login to verify

**Installation Method:**
  - [X] Docker

**Describe the bug**
Followed installation process for Docker.   Attempted with only necessary mods to .env and extended ones.  Necessary mods were just certs and DNS.  Extended mods were all new user names and passwords.   

**To Reproduce**
1. Follow documented procedure

**Expected behavior**
I expected to be able to access login page and login with tactical/tactical or using my custom creds.
However, both threw "Bad Credentials"

**Additional context**
My install is scripted via https://github.com/wiicode/automation-scripts/blob/main/tacticalrmm/install_tacticalRMM_on_AWS_Ubuntu_20.sh

**Comment by wh1te909** [comment]
Hi please see this https://wh1te909.github.io/tacticalrmm/troubleshooting/#bad-credentials-error-when-trying-to-login-to-the-web-ui check your dns and port forwarding

I'll test your install script tmrw on AWS to see if can reproduce

**Comment by wiicode** [comment]
I am sorry, I was being dense.   I thought I had resolved the cert issue
earlier, I had not.   It's most def a cert issue because I ended up issuing
a cert for my APP_HOST domain only.

**Comment by dinger1986** [comment]
Shall close this as sounds like its working
