### ISSUE TITLE
SMTP Settings require email as username

### ISSUE THREAD

**Issue by Omnicef** [wh1te909/tacticalrmm#35]
Under Global Settings, when I try to configure the SMTP settings... the username field requires an email address. I am attempting to use MailJet as my SMTP relay and the username is not an email address. So I cannot save the settings as it tells me invalid email.

**Comment by wh1te909** [comment]
fixed in 932cd8f3d391833d76522d5a7640a52c2a1b7fa5 can you try it out and lmk if works

**Comment by Omnicef** [comment]
It's working. Thanks!
