### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by kuerious** [wh1te909/tacticalrmm#350]
New install of Debian 10 VM; 4c4G, NetInst.

Followed instructions (multiple times) at: https://wh1te909.github.io/tacticalrmm/install_server/

The MeshCentral (titled TacticalRMM) install seems to go off without a hitch. I can reach "mesh.x.x" without an issue.

The "api.x.x" link reads **"The requested resource was not found on the server".**
The "rmm.x.x" link reads "**nginx: Error 500 Internal Server Error**".

I honestly don't know what I'm doing wrong.

**Comment by wh1te909** [comment]
> The "api.x.x" link reads **"The requested resource was not found on the server".**

This is normal, the django admin is disabled by default so you'll get a not found error unless you enable it: https://wh1te909.github.io/tacticalrmm/functions/django_admin/

Can you please try running the update script with the `--force` flag and then try logging in again. Instructions here https://wh1te909.github.io/tacticalrmm/update_server/

**Comment by kuerious** [comment]
No change. See: https://i.imgur.com/OxmshsF.png

**Comment by wh1te909** [comment]
can you please run the following from the tactical user and paste screenshot
```bash
cd ~
ls -la
```

**Comment by wh1te909** [comment]
also where is your vm hosted? I want to try and replicate so plz lmk where like on hyper-v or proxmox or in public cloud and if so which cloud provider

**Comment by kuerious** [comment]
> can you please run the following from the tactical user and paste screenshot
> 
> ```shell
> cd ~
> ls -la
> ```

Found here:

https://i.imgur.com/7JxcpFa.png

My VM is hosted locally. Its running on VMware ESXi. Router is pfSense, exists behind Nginx Proxy Manager.

As I've said, the "**mesh**.domain.com" is working fine. Its the RMM link that no worky.

**Comment by wh1te909** [comment]
thanks. Yea your frontend is not installing, related to that npm error. Someone had something similar recently was a permission issue in the home dir but your home dir looks good.

I just spun up a fresh debian 10 vm on hyper-v locally and ran thru the install and no errors all works, so no issues with install script and not able to reproduce.

So just google the npm errors and see if you can fix them and then just keep running `./update.sh --force` that will rebuild and reinstall the frontend

**Comment by kuerious** [comment]
You'd never guess ... irony.

I verified the sudoers file showed "tactical" would be able to use sudo w/o passwords. Then, I re-ran the update. It acted differently this time, and - et voila! - its working now.

**Comment by kuerious** [comment]
New problem.

The URL to download the Mesh agent no longer works. I saw in the instructions how to "recover" the password(s), but I don't see how to re-generate the Mesh agent URL to download (and then upload). I'm at a standstill ATM.

**Comment by wh1te909** [comment]
nice!!

check out the management commands docs there is one to generate a meshcentral link:
https://wh1te909.github.io/tacticalrmm/management_cmds/

**Comment by kuerious** [comment]
I don't see it. None of them sound like what I want.

**Comment by wh1te909** [comment]
you can just login to mesh.yourdomain.com using the meshcentral credentials that were printed out at the end of the install script and download the agents from there, doesn't have to be from an invite link. the tacticalrmm docs have instructions for how to reset these if you didn't save them

refer to the meshcentral documentation here https://github.com/Ylianst/MeshCentral mesh is a separate product just an integration. currently only windows agents are integrated with tacticalrmm, mac and linux are still under development. so you can install mac/linux agent's but you'll need to manage them using mesh's web interface, not tactical's.
