### ISSUE TITLE
Feature Request: Script Timeout Setting

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#352]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when scripts time out when being executed.

**Describe the solution you'd like**
For each script in script manager add a setting to specify a script time out, which is loaded when selecting the script from Run Scripts instead of defaulting to 30 Seconds, this will allow longer running scripts to not timeout so often.

**Describe alternatives you've considered**
Remembering to set longer timeouts when running the script.

**Additional context**

**Comment by bbrendon** [comment]
I agree each script should have its own default timeout. Some scripts run for 8 hours and some for 5 seconds. Not everyone knows what the proper timeout should be. 

Alternatively I have considered trying to change the default timeout to 8 hours which may cause other unknown issues.

**Comment by wh1te909** [comment]
done, will be in next release
