### ISSUE TITLE
Checks from policy not automatically applying

### ISSUE THREAD

**Issue by Omnicef** [wh1te909/tacticalrmm#36]
I have some checks set up as a policy and have the policy applied. However they do not show up until I create a check manually and then delete the check from a device. Then the policy checks show up for only that device.

**Comment by wh1te909** [comment]
this is a known bug see the discussion in https://github.com/wh1te909/tacticalrmm/issues/6

**Comment by wh1te909** [comment]
gonna re-open this for visibility and tracking

**Comment by sadnub** [comment]
@Omnicef Can you see if your issue is resolved with the latest updates?

**Comment by Omnicef** [comment]
It is working now!

**Comment by sadnub** [comment]
@Omnicef I am doing some rework on the policy checks and we look at this. Thanks for testing!

**Comment by sadnub** [comment]
@Omnicef I think this is due to policies not applying to newly installed agents. I will make a fix shortly.

**Comment by sadnub** [comment]
#78 Should fix this issue. Once it is merged, let me know if you have any issues. Thanks!
