### ISSUE TITLE
Feature Request: Common Monitoring Templates as well a community templates.

### ISSUE THREAD

**Issue by johnnyq** [wh1te909/tacticalrmm#361]
**Is your feature request related to a problem? Please describe.**
For example for an Exchange server i'm not sure all the services to monitor or the logs to look for, Exchange store Size warning, Mail Queue etc. Just some examples.

**Describe the solution you'd like**
Predefined Monitoring Templates as well as community templates similar to scripts to that have best practice predefined checks and tasks based off the server role for example Exchange-Template Active Directory SQL etc

**Describe alternatives you've considered**
None

**Additional context**

**Comment by silversword411** [comment]
I can integrate, see if you can find an example powershell script out there somewhere and post the link.

**Comment by dinger1986** [comment]
@wh1te909 @silversword411 suggest we make this just a thread for requests for scripts and we can work through them?

**Comment by silversword411** [comment]
> @wh1te909 @silversword411 suggest we make this just a thread for requests for scripts and we can work through them?

@dinger1986 That would make this one Feature Request go on forever with a huge thread. Each ask should be it's own issue (if we don't have it added already in the todo list - or discord ask and I just add it quickly). 

Easy to track, easy to finish/close. Just a lot of them.

**Comment by dinger1986** [comment]
Ok cool.

Happy to add these then and we can then close this?

Daniel

**Comment by silversword411** [comment]
I think that's best :)
