### ISSUE TITLE
Feature Request: Task Schedule command

### ISSUE THREAD

**Issue by dinger1986** [wh1te909/tacticalrmm#363]
At the moment need to add a script, so for example I have SQL databases backed up to a disk and need to keep that tidy, wanted to apply a task to delete it but had to write a script for that which just means I have more scripts and this one is specific to this server for 1 customer and is one line

It would be nice to able to schedule a command rather than only Scripts

I guess this could maybe be done by creating a script that calls cmd and then add in additional script arguments with the actual command. Maybe thats the solution?

**Comment by tremor021** [comment]
```
$Trigger= New-ScheduledTaskTrigger -At 10:00am –Daily # Specify the trigger settings
$User= "NT AUTHORITY\SYSTEM" # Specify the account to run the script
$Action= New-ScheduledTaskAction -Execute "PowerShell.exe" -Argument "YOUR COMMAND HERE" # Specify what program to run and with its parameters
Register-ScheduledTask -TaskName "SQL Tidy Up" -Trigger $Trigger -User $User -Action $Action -RunLevel Highest –Force # Specify the name of the task
```

If deletion is all you do, this will add a task in task scheduler to do it every day at 10am for example. just replace Argument with what you need done

**Comment by dinger1986** [comment]
Have got it working with a batch file as well. Does everything I need it to do but think @wh1te909 is going to add it as an option anyway

**Comment by sadnub** [comment]
In the next release you will be able to issue a command in a scheduled task
