### ISSUE TITLE
Feature Request: add search to Run script dialogue box

### ISSUE THREAD

**Issue by bbrendon** [wh1te909/tacticalrmm#374]
Finding the desired script is getting tough as more community and self-made scripts are added. A search like Windows 10 start menu where you just start typing and results appear would be awesome.

![image](https://user-images.githubusercontent.com/6364477/114091274-516eb880-986d-11eb-8c15-03449188c60d.png)

**Comment by wh1te909** [comment]
ok ya we def need to add search

**Comment by bradhawkins85** [comment]
Can probably close this now.

**Comment by wh1te909** [comment]
yep, can now search in the run script dropdown. thanks!
