### ISSUE TITLE
Feature request: Reset of the window borders in RMM

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#376]
I'm always frustrated when... i enter F5 and refresh the whole window. The window borders which separates the clients from the other two windows will reset. We have clients with longer name and would like to stretch the client window a litt more to the right.

We would also like to be able to size the text to fit more information in all windows.

**Comment by wh1te909** [comment]
Ok done, check the video below let me know if looks good

![x2VofULX5E](https://user-images.githubusercontent.com/7434746/114289758-38ae0080-9a2f-11eb-9004-c30ebd667a2c.gif)

**Comment by dinger1986** [comment]
Amazing!! Thank you

**Comment by frankemann** [comment]
Great, thank you!

**Comment by wh1te909** [comment]
Released in 0.5.3
