### ISSUE TITLE
Feature request: Make the refresh line green :)

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#377]
As we always are struggling to keep everything nice and GREEN it would be great to have the refresh line to be green instead of red.. :)

**Comment by wh1te909** [comment]
Lol ok i'll add a setting in User Preferences to set the default color :)

**Comment by wh1te909** [comment]
Done will be in next release:

![1XIQ7Iics5](https://user-images.githubusercontent.com/7434746/114291284-1326f400-9a3b-11eb-91bf-47ad2fb6a6d0.gif)

**Comment by frankemann** [comment]
Thank you! :)

**Comment by wh1te909** [comment]
Released in 0.5.3
