### ISSUE TITLE
Enable Agent Customization for Mshcentral

### ISSUE THREAD

**Issue by VINISHVV** [wh1te909/tacticalrmm#379]
Hi,

I am running meshcentral with 10K agents, Now i am planing to install TacticalRMM in all those system.

Since existing Meshagent service is running in all system i am stuck @ deployment of tactical RMM.

Is it possible to enable Meshcentral agent customization in TacticalRMM ?.

**Comment by wh1te909** [comment]
Hi, so when you install tactical, it also installs meshcentral for you with a `config.json` that allows integration via iframes and login token.

You don't have to use the meshcentral that tactical installs. You can use your existing one and just point tactical to use that.

I need to write up some docs on how to do that but basically just look at the `config.json` that tactical installs and make sure your existing mesh's config has `"AllowLoginToken": true` and `"AllowFraming": true`

Then you'll need to generate a login token on your existing mesh server:
(just change the path to to wherever your meshcentral is installed)

```bash
node /meshcentral/node_modules/meshcentral --logintokenkey
```

If you already have a meshcentral user account that has access to all device groups then you can use that, if not, create a new mesh user with full access to all mesh agents

Then from Tactical's web UI, go to Settings > Global Settings > MeshCentral

Username: the meshcentral username that has access to all device groups/mesh agents
Mesh Site: `https://mesh.yourdomain.com`
Mesh Token: copy and paste the token from the command above

**Comment by dinger1986** [comment]
If you want to customise mesh on tactical you can still do this using the standard process

**Comment by wh1te909** [comment]
Forgot to mention if you want to use your own mesh server, then you'll also need to upload your mesh agent installers to tactical.

From your existing mesh server, download the 64 and 32 bit windows agents (the one's that run as a service) and upload them in tactical's web UI in File > Upload Mesh Agent

**Comment by VINISHVV** [comment]
@wh1te909 
Thank you for detailed explanations,

**Comment by VINISHVV** [comment]
@dinger1986 
I have added agentcustomization command in config.js but it's not works well. Is there any blocking for such modifications?.

**Comment by dinger1986** [comment]
No, nothing blocking modifications, I have just changed mine and it worked fine.

What I did was:

1. Changed config file
2. Restarted service
3. Downloaded meshagent
4. Uploaded new mesh agent to tactical

Feel free to join discord if you need any further help and donations are always welcome :)

So to check you have edited /meshcentral/meshcentral-data/config.json and added in:

,
        "agentCustomization": {
        "displayname": "MyCo Remote",
        "description": "MyCo Remote Agent",
        "companyName": "MyCo Ltd",
        "serviceName": "MyCoRemote"
        }

So the complete config file is:

{
  "settings": {
    "Cert": "mesh.MyCo.com",
    "MongoDb": "mongodb://127.0.0.1:27017",
    "MongoDbName": "meshcentral",
    "WANonly": true,
    "Minify": 1,
    "Port": 4430,
    "AliasPort": 443,
    "RedirPort": 800,
    "AllowLoginToken": true,
    "AllowFraming": true,
    "_AgentPing": 60,
    "AgentPong": 300,
    "AllowHighQualityDesktop": true,
    "TlsOffload": "127.0.0.1",
    "MaxInvalidLogin": { "time": 5, "count": 5, "coolofftime": 30 }
  },
  "domains": {
    "": {
      "Title": "MyCo",
      "Title2": "RMM",
      "NewAccounts": false,
      "CertUrl": "https://mesh.MyCo.com:443/",
      "GeoLocation": true,
      "CookieIpCheck": false,
      "mstsc": true,
      "agentCustomization": {
      "displayname": "MyCo Remote",
      "description": "MyCo Remote Agent",
      "companyName": "MyCo Ltd",
      "serviceName": "MyCoRemote"}
    }
  }

**Comment by VINISHVV** [comment]
@dinger1986 @wh1te909 thanks for your support.... 

I am Confidently move to deploy 10k agents with TacticalRMM...

**Comment by VINISHVV** [comment]
@dinger1986 / @wh1te909 

I have enabled agent customization and uploaded the new meshagent exe.

But getting error during installation. since the TacticalRMM checks the default meshagent location c:\program files\Mesh Agent.

is there any option for skip this error.

**Comment by dinger1986** [comment]
Ah that's a shame. Probably not at the moment as that's a big change.

Why not rebrand and redeploy your existing mesh? That's the way I did it. Then install tactical.
