### ISSUE TITLE
Feature Request: Change color of check status

### ISSUE THREAD

**Issue by pitah81** [wh1te909/tacticalrmm#386]
When there's a check with warning status for a certain device, it shows up as orange in the check list, however the device and site shows as red so I can't tell if there's a warning och error status for that site/device unless I click myself down to the device checks view. Also same color should apply for failing checks in the summary view.

What I would like is to change the color behaviour so it is consistent, maybe make maintaince mode blue or green as to use orange for warning status.

**Comment by frankemann** [comment]
+1

**Comment by sadnub** [comment]
This is implemented and will be in the next release. Thanks!

**Comment by wh1te909** [comment]
Released in 0.6.1
