### ISSUE TITLE
Feature request: Clear check until next run

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#388]
Would be great to clear a failed check to "ok" manually until it run next time. 

F.ex: if we have a daily backup check which fails, we would fix the backupissue, and clear the check. In the check we have a 86400 second to next run (24 hour) to verify the backup check again. (if we have daily backup...)

**Comment by sadnub** [comment]
This will be in the next release. Thanks!

**Comment by wh1te909** [comment]
Released in 0.6.1 (right click on a check > Reset Check Status)
