### ISSUE TITLE
Strange agent auto connections

### ISSUE THREAD

**Issue by grigoroffbenj** [wh1te909/tacticalrmm#391]
**Server Info :**
 - OS: Docker on Debian 10
 - Browser: chrome
 - RMM Version: v0.5.3

**Installation Method:**
  - Docker

**Agent Info:**
- Agent version: Agent v1.4.14
- Agent OS: Windows 10 Pro, 64 bit (build 19042.906), for strange connexion :  Windows 7 Ultimate, 64 bit (build 7601.0) 

**Describe the bug**
After clean install, if I wait 10 minutes I can see some strange auto connections of workstation see screenshoot below.
the IP adress is : 72.12.194.94
Any body have the same ? 

**To Reproduce**
after a clean install and change of $MESH_USER and $MESH_PASS it's the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/11214033/114584941-6be8cd80-9c83-11eb-8087-bb019761635e.png)

**Comment by saulens22** [comment]
It's antivirus local / cloud sandbox. Can be ignored. See #340 comments.

**Comment by wh1te909** [comment]
yes exactly what @saulens22 said. Just add exclusions to your AV, instructions are in the docs for what to exlcude
