### ISSUE TITLE
script linking or chaining

### ISSUE THREAD

**Issue by djsvi** [wh1te909/tacticalrmm#395]
Currently I am having to copy/paste 'helper' code into the top of multiple powershell scripts. This helper code will change from time to time. While this works OK while the number of scripts is low it will be annoying to maintain once there are dozens of them.

I'd like a means of linking or chaining scripts together so each could be maintained separately. The linking could be done within the script itself (some kind of meta-command that TRMM recognises and interprets as an instruction to link another script) or in some kind of higher level script function within TRMM (e.g. there could be a script of type 'TRMM' that provides high level functions like running/scheduling one or more batch, powershell or python scripts, potentially with execution of steps dependant on the return codes of previous steps, though this conditional execution could be pretty tricky I imagine).

**Comment by sadnub** [comment]
This can be accomplished with Script Snippets. The feature was added a few months ago
