### ISSUE TITLE
Bug Report: Errors 'invalid start byte' when running scripts

### ISSUE THREAD

**Issue by alexandremottier** [wh1te909/tacticalrmm#399]
**Server Info (please complete the following information):**
 - OS: Debian 10
 - Browser: Firefox 86
 - RMM Version (as shown in top left of web UI): v.0.6.0

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v1.5.0
- Agent OS: Windows 10 Pro, 64 bit (build 18363.1441)

**Describe the bug**
Python (?) error when running a command on a workstation from TacticalRMM.
Error : `'utf-8' codec can't decode byte 0xff in position 11: invalid start byte`

**To Reproduce**
1. Right click on the Windows 10 workstation in workstations list
2. Choose "Run script"
3. Choose "Send command"
4. Shell : CMD. Timeout : 30 seconds. Command `arp -a`

**Expected behavior**
Getting the network addresses from machines of the network with MAC address.

**Screenshots**
<img width="687" alt="image" src="https://user-images.githubusercontent.com/40338703/115039856-1efa3680-9ed1-11eb-9eb4-98574779351c.png">

**Additional context**
Same problem when I am using a homemade script with the same command : 
<img width="984" alt="image" src="https://user-images.githubusercontent.com/40338703/115040153-6a144980-9ed1-11eb-8081-3061e69d8d5e.png">

<img width="995" alt="image" src="https://user-images.githubusercontent.com/40338703/115040232-80baa080-9ed1-11eb-9461-338c88c4e09e.png">

**Comment by wh1te909** [comment]
thanks, am aware of this issue actually ran into it myself recently when running the `tree` command. working on a fix.

**Comment by alexandremottier** [comment]
Thanks a lot for your quick answer. After some tests, I think that the problem is related to all CMD commands.
PowerShell commands are working just fine.

Thanks a lot for your job, your app is very nice !
I think you will be a strong competitor to the market leaders.
The Alpha version of your application is already very complete and functional from what I could test.

**Comment by wh1te909** [comment]
I've fixed (requires an agent update) will be in the next release

**Comment by alexandremottier** [comment]
FYI, I have tested with TacticalRMM v0.6.1 and agent in v1.5.1 and I had the same issue.
I am waiting for TacticalRMM v0.6.2 ;-)

Thanks for your quick answer :-)

**Comment by wh1te909** [comment]
Released in 0.6.2
You'll need to upgrade to 0.6.2 and then wait for your agents to update to 1.5.2
