### ISSUE TITLE
Let'S Encrypt Error - Cannot issue for "*.com.au"

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#40]
On a fresh Ubuntu 20.04 install I get the following error when running install.sh

Obtaining a new certificate
An unexpected error occurred:
The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "*.com.au": Domain name is a wildcard for an ICANN TLD
Please see the logfiles in /var/log/letsencrypt for more details.

The install appears to calculate the rootdomain correctly from rmm.mydomain.com.au

I managed to get the install running by doing the following to the install.sh script
Removing:
rootdomain=$(expr match "$rmmdomain" '.*\.\(.*\..*\)')

And Adding:
while [[ $rootdomain != *[.]*[.]* ]]
do
echo -ne "${YELLOW}Enter the root domain for LetsEncrypt (e.g. example.com)${NC}: "
read rootdomain
done

**Comment by wh1te909** [comment]
thank you! yea this issue came up before hadn't had a chance to update the install script yet, are you able to submit a PR with the fix? If not I will do in a bit
