### ISSUE TITLE
Feature request: Rights management by groups (users or customers)

### ISSUE THREAD

**Issue by alexandremottier** [wh1te909/tacticalrmm#400]
**Is your feature request related to a problem? Please describe.**
When a user is created on the platform, he has full rights on everything.

**Describe the solution you'd like**
User rights management menu with groups of customers and groups of users.
_Example: Make some customers hidden from some users or user groups_

**Describe alternatives you've considered**
There is no really alternative unless only create users able to change anything on the panel.

**Additional context**

Some examples of needed configurations : 

* _I don't want my employees to be able to manage my company's servers, only the customers' servers._
* _I want to partition the clients available to a user._
* _I don't want employees to be able to access the email settings or change a colleague's password._

**Comment by wh1te909** [comment]
Hi this is planned and am actually working on it in separate branch so hopefully should have something soon.
There is already a ticket for this so i'm gonna just close this one and will link to the existing ticket.
https://github.com/wh1te909/tacticalrmm/issues/162
