### ISSUE TITLE
Feature request: Sort alpabetically both by client and their status

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#402]
As it is now we can get all the failed Clients first, but their order is not alphabetically.

Would be great to have all the "good" Clients aphabetically, but also the "Warning / Failed" Clients in their status order alphabetically.

F.ex
Client D (Failed - red)
Client G (Failed - red)
Client H (Failed - red)
Client C (Warning - yellow)
Client I (Warning - yellow)
Client O (Warning - yellow)
Client K
Client P
Client Z

**Comment by dinger1986** [comment]
Failed at the moment is in reverse alphabetical order.

Just so you know

**Comment by frankemann** [comment]
lol, you are right :) Actually didnt see that.. Hopefully it makes sense to have the option to not have it in reverse order at the end..

**Comment by wh1te909** [comment]
Hi just fixed it, will be in next release

**Comment by wh1te909** [comment]
Released in 0.6.2
