### ISSUE TITLE
Cannot Delete Agentless Client or Site without moving non existing agents to another site

### ISSUE THREAD

**Issue by johnnyq** [wh1te909/tacticalrmm#409]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04.2
 - Browser: FireFox
 - RMM Version (as shown in top left of web UI): 6.1

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2]

**Describe the bug**
When an agentless site/client is created the move agents option should not be shown or required. 

**To Reproduce**
1. Create Client/Site
2. Right Click created Client or site
3. Choose delete

**Expected behavior**
When deleting an agentless site or client the option to move agents should not exist and just the delete should show up. Currently it force you to move agents that are not there to another site.

**Comment by wh1te909** [comment]
ya we can fix this, for now you can just choose a random client/site to move the agents to just so it will delete. behind the scenes it will just move 0 agents so will still work

**Comment by sadnub** [comment]
This has been fixed and will be in the next release
