### ISSUE TITLE
Information not populating 

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#41]
The Local IP, Software, Patches and Assets pages don't populate with any data.
Are there any logs to show why that I can provide?

**Comment by bradhawkins85** [comment]
It looks like my previous salt minion being installed causes issues when the rmm agent is installed.
Perhaps a check to remove an existing salt minion if it is already installed not just override the config file?

**Comment by wh1te909** [comment]
Thanks I'll add something for existing salt minion in the next agent release.

If you ever need to re-install a botched agent, first right click on the agent from the web interface and choose "remove agent". that will first try to contact the agent to send it the uninstall command. if it cannot be contacted, it will tell you the agent will need to be manually installed. but either way it will perform the proper cleanup on the server side, which needs to happen. This includes removing the old salt-minion key server server side.

So always remove first from the web interface, and if it says it's unable to contact the agent then manually uninstall the Tactical RMM Agent from Program and Features, or run 'C:\\Program Files\\TacticalAgent\\unins000.exe' which will properly cleanup the agent, mesh agent and salt minion on the agent side.

**Comment by wh1te909** [comment]
@bradhawkins85 new agent is out with an improved installer, release notes are here https://github.com/wh1te909/winagent/releases/tag/v0.10.1

going to close this ticket but please re-open if needed
