### ISSUE TITLE
Feature: Show windows 10 Version

### ISSUE THREAD

**Issue by johnnyq** [wh1te909/tacticalrmm#410]
**Is your feature request related to a problem? Please describe.**
It would be nice to show the Windows 10 Version number example 1909 or 2004 etc

**Describe the solution you'd like**
Would like it it display windows 10 version number see screen shot below

**Describe alternatives you've considered**
No other alternative 

**Additional context**
![image](https://user-images.githubusercontent.com/1812594/115125868-06edea00-9f99-11eb-9b51-1869fae091c9.png)

**Comment by wh1te909** [comment]
Done will be in next release/agent

**Comment by wh1te909** [comment]
Released in 0.6.7, requires agent 1.5.4
The version will show up next to the build number.

**Comment by johnnyq** [comment]
Super Awesome!! this has already come in handy, I spotted a few system stuck on 1709.  keep up the great Work!!
