### ISSUE TITLE
Feature: Greater depth of trees on site, customer

### ISSUE THREAD

**Issue by cm-slu** [wh1te909/tacticalrmm#413]
Having a greater depth of tree structure for site / client management would be a plus.
In our case we are missing a tree below the site.

**Comment by wh1te909** [comment]
what would you want below a site?

**Comment by cm-slu** [comment]
In the tree structure, power of another branch
Example:
In the "Test" node to be able to add Paris, in the Paris node to be able to add "Supermarket" ....
![image](https://user-images.githubusercontent.com/82769965/115157453-9f639780-a089-11eb-9e2c-7eb3bb091357.png)

**Comment by cm-slu** [comment]
Be able to add another child.
If I take some of my customers they can have up to 100 stores.

I would have classified it like that.

Name of one of our agencies> Client name> Client city> ...

The goal is to properly classify the posts.

The ideal would also be to be able to do a search in this tree (like the search function in the peripherals section which is top)

**Comment by wh1te909** [comment]
I don't get it. We have a client with almost 50 stores, so in rmm we have 1 client with 50 sites. Works great.

You have 1 client and then just use sites to categorize them. Doesn't have to be a physical location. I have a client that has a few sites which are physical location but also a site called "Remote Laptops" which is not a physical location but just a way to organize all the company laptops from ppl that work from home.

Anyway, what you want would require a major redesign so not gonna happen anytime soon if ever. I'll leave the ticket open though if someone wants to work on implementing this.

**Comment by cm-slu** [comment]
Hello, I understand then we do not touch anything, I will review the initial idea of ​​my organization that I had.
Would it then be possible to just have a site or customer search function in the tree section?

**Comment by dinger1986** [comment]
search request has already been opened check #317 and add comments to there
