### ISSUE TITLE
Allow persistent modal when script is running

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#418]
**Is your feature request related to a problem? Please describe.**
When running a script, the modal is able to be closed by clicking anywhere on screen. 

**Describe the solution you'd like**
When a script is running, the modal should be persistent unless clicking the X, I like to have the modal open until the script runs and I see the output, but accidentally close it.

**Describe alternatives you've considered**

**Additional context**

**Comment by wh1te909** [comment]
done, will be in next release

**Comment by wh1te909** [comment]
Released in 0.6.2
