### ISSUE TITLE
Feature request: Integrate with already paid Teamviewer host

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#423]
We have a corporate version of Teamviewer..
Would be great to use TW as an alternative for the remote sessions. 
Not sure how it could be implemented or deployed automatically?

**Comment by frankemann** [comment]
I think sadnub is working with a url launcher, which could launch teamviewer locally with the arguments.
I have created a script that retrieve the id from the installed teamviewer to a custom field through task/collectorhost and hopefully we can pass that as a ID argument.  And the use a Global Key Store as the password (which is the same we deployed on out teamviewer hosts.

**Comment by sadnub** [comment]
This will be possible with url actions in the next release.

**Comment by wh1te909** [comment]
released in 0.6.9 https://wh1te909.github.io/tacticalrmm/functions/url_actions/
