### ISSUE TITLE
When running task dashboard alert doesn't display

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#430]
**Server Info (please complete the following information):**
 - OS: Ubuntu20.04
 - Browser: Edge, Chrome
 - RMM Version (as shown in top left of web UI): 0.6.2

**Installation Method:**
  - [x ] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.5.2
- Agent OS: Windows 10 20H2

**Describe the bug**
Dashboard alerts do not display after running a task assigned by an automated policy.

**To Reproduce**
Create automated policy with at least one task and with dashboard alert checked
Assign policy to a PC/agent
Run task by right-clicking and selected Run Task
Dashboard alert does not display when task shows completed

**Expected behavior**
An alert displayed to me via the dashboard

**Screenshots**

**Additional context**

**Comment by wh1te909** [comment]
I followed your steps to reproduce and not able to, seems to be working for me, see screenshot:

![ticket430](https://user-images.githubusercontent.com/7434746/115970188-c12fa500-a4f5-11eb-9e0a-7fe5790d3c4f.png)

**Comment by subzdev** [comment]
Does it display only when it fails?

**Comment by wh1te909** [comment]
yea

**Comment by subzdev** [comment]
Ah ok then, nm. Was waiting for a success notice. Want me to delete this then?

**Comment by wh1te909** [comment]
u can close it, don't delete in case someone else comes across it they can see xD

**Comment by subzdev** [comment]
Alerts only display for failures, closing.
