### ISSUE TITLE
Tasks assigned by automated policy not alphabetized

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#431]
**Is your feature request related to a problem? Please describe.**
Tasks assigned by an automated policy are not alphabetized. 

**Describe the solution you'd like**
Would be nice if tasks were alphabetized by name. Appears to be by sorted by last run time, but would like a way to sort by name as well or any of the other column headers.

**Comment by sadnub** [comment]
The ability to sort tasks should be in the next release

**Comment by wh1te909** [comment]
Released in 0.6.3
