### ISSUE TITLE
Bulk add scripts to automation policy tasks

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#434]
**Is your feature request related to a problem? Please describe.**
Unable to add more than 1 task at a time when creating an automation policy.

**Describe the solution you'd like**
A multi-select list would work to be able to select multiple tasks. The descriptive name field could just default to the script name instead of having to define it for each added task and the schedule could be set for all in the list at the same time.

**Comment by sadnub** [comment]
This feels like it would be better suited for the a django shell versus the UI. It might also be problematic to have the same date/time settings since you can;t go back and modify them at this time. 

The copy function exists for automation policies, but the tasks do need to be created first.
