### ISSUE TITLE
Can't delete ping checks

### ISSUE THREAD

**Issue by lclainsg2a** [wh1te909/tacticalrmm#439]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome 90.0.4430.93 (Build officiel) (64 bits)
 - RMM Version (as shown in top left of web UI): v0.6.3 (fresh upgrade this morning)

**Installation Method:**
  - Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): Agent v1.5.2
- Agent OS: Windows 10 Pro, 64 bit (build 19041.928)

**Describe the bug**
Html error when deleting a ping check

**To Reproduce**
1. Go to 'checks tab'
2. Add a ping check
3. Try to delete the previous ping check
4. See screenshot error 

**Screenshots**

![Ping_Checks_Html_Error](https://user-images.githubusercontent.com/21194770/116210911-9a66ae00-a743-11eb-8b94-101f3b9d40f7.png)

**Others**
Maybe the same error with other checks, I didn't try.

**Comment by wh1te909** [comment]
Hi thanks, just fixed in 0.6.4
