### ISSUE TITLE
speaking of cheap clients, Agent pukes on installing on a 2008 Server

### ISSUE THREAD

**Issue by Gjeret** [wh1te909/tacticalrmm#44]
The Procedure entry point GetActiveProcessCount could not be loaded in the dynamic link library KERNEL32.dll

System is 
Microsoft Corporation, Windows Server (R) 2008 Standard (6.0.6002) (en-US)

**Comment by Gjeret** [comment]
<img width="772" alt="2020-08-14_13-44-20" src="https://user-images.githubusercontent.com/13461711/90283447-dd8f2400-de35-11ea-8dcf-39bbdc2fba81.png">

**Comment by wh1te909** [comment]
windows 7 / 2008R2 need a certain KB installed, see the discussion here

https://github.com/wh1te909/tacticalrmm/issues/38#issuecomment-673096880

**Comment by wh1te909** [comment]
Sorry just noticed you're on server 2008, not server 2008 R2. ive never tested it on just 2008 i'll have to spin up a VM and see

**Comment by dinger1986** [comment]
Ok going to test this now.

I do have a customer who still has a 2008 box so will try it on that

**Comment by bbrendon** [comment]
I don't think Vista (2008) is Supported. 2008 R2 is the Win7 equivalent.

**Comment by dinger1986** [comment]
agreed, I shall close this as it isn't supported
