### ISSUE TITLE
Bug report: "undefinied" error running tasks with collector to populate custom field

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#440]
Server Info (please complete the following information):

OS: Ubuntu 20.04
Browser: Chrome 90.0.4430.93 (Build officiel) (64 bits)
RMM Version (as shown in top left of web UI): v0.6.3 (fresh upgrade this morning)
Installation Method:

Standard
Agent Info (please complete the following information):

Agent version (as shown in the 'Summary' tab of the agent from web UI): Agent v1.5.2
Agent OS: Windows 10 Pro, 64 bit (build 19041.928)

Describe the bug
When adding a task and choosing Collector and the custom field, the picking a schedule,  we get an "Undefined" error at the top. It works on some computers but not on all.

**Screenshots**
![image](https://user-images.githubusercontent.com/82226898/116226345-2502d980-a753-11eb-9d3e-6d5462779286.png)

**Additional context**

**Comment by wh1te909** [comment]
Hi should be fixed in 0.6.4 can you update and try again?

**Comment by frankemann** [comment]
Thanks! I upgraded right to 0.6.5 and it works now!
