### ISSUE TITLE
Unable to delete tasks from Automation Manager

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#441]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Microsoft Edge 90.0.818.46 (Official build) (64-bit)
 - RMM Version (as shown in top left of web UI): 0.6.4

**Installation Method:**
  - [ x] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.5.2
- Agent OS: Windows 10 Pro, 64 bit (build 19042.928)

**Describe the bug**
Going to Settings -> Automation Manager, selecting my policy and attempting to delete tasks does not update the display, and they are still present in the list. In the dashboard view however, selecting the computer with that automation policy the view is updated and the tasks are not present.

**To Reproduce**
1. Settings -> Automation Manager
2. Create an automation policy
3. Go to Tasks
4. Add Task
5. Delete Task (should not change display and the task will remain present)

**Expected behavior**
When deleting the task it should not be present both in the Automation Manager and in the dashboard Tasks view for a computer when an Automation Policy is applied.

**Comment by sadnub** [comment]
Thanks for reporting! I just pushed a fix will be in the next release

**Comment by wh1te909** [comment]
released in 0.6.5

**Comment by subzdev** [comment]
Thank you, will update asp and report back.

**Comment by subzdev** [comment]
Just tested on 0.6.5 and working as expected. Thanks again!
