### ISSUE TITLE
Ping check error

### ISSUE THREAD

**Issue by NicolasDEVOUGE** [wh1te909/tacticalrmm#444]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Browser: Chrome
 - RMM Version  v0.6.5

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v1.5.2
- Agent OS: Win 10

**Describe the bug**
Ping check script report error but ping is ok

**To Reproduce**
1. Create ping check to fw ip by example
2. Get the status

**Screenshots**
![image](https://user-images.githubusercontent.com/1253901/116373607-cbabb080-a80d-11eb-914b-915fe7584b03.png)

**Comment by dinger1986** [comment]
My pings are working fine.

I wonder if it's a localisation issue.

**Comment by NicolasDEVOUGE** [comment]
Yes, maybe it's because my ping is in french. I don't know how to see the source of the script to check that.

**Comment by dinger1986** [comment]
Yeah probably is, I dont know, just hoping that helps the devs, guess it should be worked on allong with #39   if that is the case

**Comment by wh1te909** [comment]
yea im using windows' ping.exe and checking for english strings only atm
this will be fixed in the next agent, im switching to a pure go icmp implementation rather than checking the output for certain keywords to determine pass/fail status

**Comment by wh1te909** [comment]
This has been fixed in latest release. Requires agent v1.5.3

**Comment by NicolasDEVOUGE** [comment]
That's working perfectly, thank you !
