### ISSUE TITLE
Feature request : Assign user to Customers or Sites

### ISSUE THREAD

**Issue by MadItGuy** [wh1te909/tacticalrmm#445]
We use TRMM to manage our devices but our customers devices too.

For security reasons, we would like to limit access to devices by users. 
Some users are dedicated to supporting our customers and others to internal support.

So we need to assign users to Customers or directly to Sites that limit their access to different devices.

we could imagine two fields in the configuration page of a user which would include the list of Customers and the list of Sites with the possibility of selecting "all" for users with full rights.

**Comment by dinger1986** [comment]
This request is already open.

Please search before adding.
