### ISSUE TITLE
Feature reqguest: Auto Connect remote

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#446]
Would be great that the Take Control auto-connected. 
I guess that perhaps is a Mesh Central?

**Comment by dinger1986** [comment]
this has been requested, #320.

Wh1tes comment on that closed feature request:
yes plz open this request in meshcentral's repo. cannot script it to auto click due to browser security restrictions that prevent me changing stuff within iframes, so mesh needs to implement this
