### ISSUE TITLE
Server Error (500) when try to delete a check

### ISSUE THREAD

**Issue by el-vinz** [wh1te909/tacticalrmm#448]
**Server Info (please complete the following information):**
 - OS: Debian 10
 - Browser: Chrome (on ubuntu 20.04)
 - RMM Version 0.6.3

**Installation Method:**
  - X Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version v1.5.2
- Agent OS: Windows 7 Pro 32 b

**Describe the bug**

**To Reproduce**
1. Go to Checks
2. right click on check
3. Click on delete
5. <!doctype html> <html lang="en"> <head> <title>Server Error (500)</title> </head> <body> <h1>Server Error (500)</h1><p></p> </body> </html>

**Expected behavior**
Can delete the check

**Screenshots**
![image](https://user-images.githubusercontent.com/33762247/116431882-7771f200-a848-11eb-8a44-b0353679ac92.png)

**Additional context**

Many thanks for your job...it 's amazing. AND.......there's python Inside :)

**Comment by subzdev** [comment]
Try updating to latest RMM version of 0.6.5.

**Comment by wh1te909** [comment]
Hi yes this was fixed in latest version, please update to 0.6.5

**Comment by el-vinz** [comment]
I' hve just did it. It works. I should did that before.... Thanks  !
