### ISSUE TITLE
Modify task schedule in automation manager

### ISSUE THREAD

**Issue by AndreaChiaramonte** [wh1te909/tacticalrmm#451]
**Is your feature request related to a problem? Please describe.**
Cannot modify the scheduling of a task in a policy in automation manager

**Describe the solution you'd like**
a choice to modify the date/time of a task

**Describe alternatives you've considered**

**Additional context**
Tactical RMM v0.6.5 - Ubuntu 20.04.2

**Comment by sadnub** [comment]
This will be in the next release
