### ISSUE TITLE
Add Help menu in toolbar at the top

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#452]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem I am experiencing.

**Describe the solution you'd like**
There should be a Help menu, right after Tools, that displays a Documentation link that opens up a new tab to the documentation located here: https://wh1te909.github.io/tacticalrmm/

Other possible items could be, Submit a Bug, or Submit a Feature. or Join Discord to allow other avenues into the community aspects of TRMM.

**Describe alternatives you've considered**
An alternative is to go the website outside of TRMM, but would be nice to have a link to help documentation within TRMM.

**Comment by wh1te909** [comment]
Done will be in next release

**Comment by wh1te909** [comment]
Released in 0.6.6
