### ISSUE TITLE
Conditional checks

### ISSUE THREAD

**Issue by WouterLS** [wh1te909/tacticalrmm#454]
Hi,

Would it be possbile to have checks based on conditions or variables.
We would implement one server policy that has a basic setup like :

If (application.installed contains "Microsoft DNS") deploy check "DNS service running"
or
if (bitlocker deployed) run task "backup bitlocker key"

This would enable us to implement a large standardized template policy and use the site policy assignement to do small extra's whenever needed.

**Comment by sadnub** [comment]
You can create a script check that checks if the DNS role is installed and to makes sure the DNS server is running.

If it isn't running when the script finishes you can return a 1 or if it is running return 0 for passing.

**Comment by wh1te909** [comment]
https://wh1te909.github.io/tacticalrmm/functions/scripting/

if you need more help writing script checks please join our Discord and you can ask for help there

**Comment by WouterLS** [comment]
That's interesting.
That would make that script run on all servers.
Possibly unnecessary on a bunch of them.

I will try that for now..

It would be beneficial to the overall product to have some kind of conditionality so not all checks are done on all agents.

**Comment by wh1te909** [comment]
that's the whole point of a script check, you're in control and so you write the conditional
for example i have a script check that i have deployed to all agents. at top of script it does its conditional check and if doesn't match, simply returns without continuing

you can also deploy checks to just individual agents. or if you use the Automation Manager you can deploy them per client/site, server/workstation etc so there are already conditionals built in and then the final conditional should be done in your actual script

**Comment by wh1te909** [comment]
you can also run a task based on the condition of a script, so if you script check fails you can then have it run a task (setup an automated task from the UI and select "when check fails" as the trigger)
