### ISSUE TITLE
Bug: Deletion of checks not possible

### ISSUE THREAD

**Issue by cm-slu** [wh1te909/tacticalrmm#455]
**Server Info (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Version 90.0.4430.93 (Build officiel) (64 bits)
 - RMM Version v0.6.3

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):Agent v1.5.2
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2] Windows 10 Enterprise 2016 LTSB, 64 bit

**Describe the bug**
Following the addition of a check impossible to delete it

**To Reproduce**
1. Go to 'check menu'
2. Click on 'right + delete'
3. See error
`<!doctype html> <html lang="en"> <head> <title>Server Error (500)</title> </head> <body> <h1>Server Error (500)</h1><p></p> </body> </html>`

**Screenshots**
![image](https://user-images.githubusercontent.com/82769965/116553502-79948900-a8fa-11eb-87f2-546b2e24f3cd.png)

**Comment by sadnub** [comment]
This was fixed in the latest release. Please update and see if that works.

**Comment by cm-slu** [comment]
This ok
it's not my fault if you go too fast ;)
