### ISSUE TITLE
Show countdown or the time when next agent update will occur

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#457]
**Is your feature request related to a problem? Please describe.**
Right-clicking on an agent and selecting Pending Actions, there is a notice of update happening at next update cycle, but it is not clear when that will happen.

**Describe the solution you'd like**
A countdown timer or the exact time when the next update will occur would be useful.

**Comment by wh1te909** [comment]
agent update occurs every hour at 35 past the hour (is in the docs). I can add a tooltip button that says "at 35 past the hour" if you want

**Comment by subzdev** [comment]
> agent update occurs every hour at 35 past the hour (is in the docs). I can add a tooltip button that says "at 35 past the hour" if you want

Sure, I think that is a great idea! That kind of information is really easy to forget but having it as a tooltip really makes it easy to find and doesn't clutter the UI.

**Comment by wh1te909** [comment]
ok I ended up just adding the exact datetime lol, will be in next release

**Comment by subzdev** [comment]
:D

**Comment by wh1te909** [comment]
Released in 0.6.7
