### ISSUE TITLE
Patches and Windows Update show different status and content

### ISSUE THREAD

**Issue by itsdaveit** [wh1te909/tacticalrmm#458]
**Server Info (please complete the following information):**
 - OS: Debian 10
 - Browser: Chrome
 - RMM Version v0.6.6.

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version 1.5.3
- Agent OS: Server 2019 Standard

**Describe the bug**
Windows Updates lists 7 Updates to be installed, but in the Patches view only 2 are pending.
Some of the updates which windows update sees as pendig, are shown as installed in TacticalRMM
Some Updates seen in in Windows are not shown at all in tactical.
I see this behaviour on mutiple clients.

**To Reproduce**
1. Install Agent
2. Scan for Patches
3. Compare to results in Windows Update

**Expected behavior**
Lists should be in sync

![image](https://user-images.githubusercontent.com/9453135/116753832-05e0a200-aa08-11eb-84fd-4ecc93761aaf.png)

![image](https://user-images.githubusercontent.com/9453135/116753857-13962780-aa08-11eb-93ac-b5a395e177fd.png)

**Comment by wh1te909** [comment]
Hi, the agent uses the [windows update API](https://docs.microsoft.com/en-us/windows/win32/wua_sdk/portal-client) to manage updates, which is a bit different than what the new windows settings GUI uses so yea they're not always gonna be in sync, not something I have control of that would be up to MS to fix. 

I've got some agent updates coming soon to essentially disable auto update and stuff and just use the windows update API and when that happens they're definitely not gonna be in sync. I've seen similar behavior with other rmm's that also use the win update api.

**Comment by itsdaveit** [comment]
Thanks for your Information. Might be interesting to others also. Keep up the great Work!
