### ISSUE TITLE
Show client, site, agent id in default view

### ISSUE THREAD

**Issue by davidrudduck** [wh1te909/tacticalrmm#467]
If I want to script installation, or leveraging the API, to get the client id or site id I need to go to "Add Agent", change to "manual" and view the help to see those values.

Would be good, whether configurable or not, to show these values. Aka ConnectWise Automate style.

CompanyName1 (1)
+ Main Location (1)
+ BYOD (2)
+ New Devices (3)

CompanyName2 (2)
+ Location1 (1)
+ Location2 (2)

**Comment by wh1te909** [comment]
added in #575 will be in next release, thanks @unplugged216
