### ISSUE TITLE
Feature Request: Variables

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#47]
Need the ability to store variables against Clients/Sites/Devices and Globally which can then be used later in tasks and checks.
It would be good if these variables could be updated via tasks or checks too.
E.G. Store a software product key for a client such as #antiviruskey# and then can use this in script arguments like c:\windows\temp\myinstaller.exe #antiviruskey#

**Comment by wh1te909** [comment]
added in release 0.5.0
