### ISSUE TITLE
Custom run check interval if applied from automation manager not getting applied

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#473]
Create automation profile. 
Create check, with custom/long check run interval
Apply, and look at run history, running every 2 mins (default value)

![2021-05-04_101125 - Script check run interval](https://user-images.githubusercontent.com/13395348/117073495-fd39e580-acff-11eb-9be0-b1e251d3008d.png)

Not sure what this was about: https://discord.com/channels/736478043522072608/744282073870630912/839253714014437396 but possibly related?

**Comment by wh1te909** [comment]
released in 0.6.10
