### ISSUE TITLE
Editing checks deletes all/most checks from front end

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#474]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - RMM Version (as shown in top left of web UI): v0.6.6

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): Agent v1.5.3
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2] N/A

**Describe the bug**
When deleting a check-in Automation Manager an error is displayed (one time) saying an error has occurred, then all checks appear to be removed from Automation Manager.
Checks still appear as applied to each agent.

**To Reproduce**
1. Go to automation manager
2. Select a policy
3. Delete a check
4. See generic error message.

**Expected behavior**
Checks can be deleted without "hiding" all other checks

**Additional context**
Error only appears to occur once, new checks can be added and deleted ok.
All server logs appear to contain no errors.

**Comment by sadnub** [comment]
Thanks for reporting!  I just submitted a fix for this. Will be in the next release

**Comment by wh1te909** [comment]
Released in 0.6.7
