### ISSUE TITLE
update.sh won't run after update

### ISSUE THREAD

**Issue by davidrudduck** [wh1te909/tacticalrmm#478]
Updating from 0.6.6 to 0.6.8 the following occurred:

tactical@it-tacticalrmm01:/rmm$ bash ./update.sh
Old update script detected, downloading and replacing with the latest version...
./update.sh: line 19: /rmm/update.sh: Permission denied
./update.sh: line 19: exec: /rmm/update.sh: cannot execute: Permission denied

By default the update script does not chmod +x update.sh, so when it goes to re-run the script, it fails.
Either needs to chmod +x or execute via bash.

ie:
tactical@it-tacticalrmm01:/rmm$ chmod +x update.sh
tactical@it-tacticalrmm01:/rmm$ bash ./update.sh
Hit:1 http://au.archive.ubuntu.com/ubuntu focal InRelease

Installed on Ubuntu 20.04 in non-docker install.

**Comment by wh1te909** [comment]
don't call it with `bash` in the front just do `./update.sh` and it will work. first line in the script already tells it to use bash
you need to `chmod +x update.sh` first, just follow instructions in the docs https://wh1te909.github.io/tacticalrmm/update_server/#updating-to-the-latest-rmm-version
