### ISSUE TITLE
Feature Request: Script Arguments

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#48]
Related to Feature Request #47 it would be great to be able to pass variables to scripts at runtime when either selecting Run Now or having them execute on a schedule.

**Comment by wh1te909** [comment]
this is implemented in 48e5fc6758ae037ffb9656f34b7061d7d6a0f378 only for ad-hoc scripts from the agent's context menu (right click agent > Run Script). Will be available for script checks and tasks when I release the next agent.

**Comment by bradhawkins85** [comment]
I've done some testing today and a basic batch script with arguments is working as expected.

The script:
choco install %1 -y

Will advise once I have tested more scripts if there are any issues, but so far looking good.

**Comment by wh1te909** [comment]
this has been fully implemented including checks / tasks. needs agent 0.11.0 which I just released
