### ISSUE TITLE
Feature Request: Process monitor

### ISSUE THREAD

**Issue by wiicode** [wh1te909/tacticalrmm#480]
**Is your feature request related to a problem? Please describe.**
I would like to easily monitor processes for uptime and trigger events if they are running/not-running, memory usage, and CPU.

**Describe the solution you'd like**
Under Checks, I would like an Add Check for "Process Monitor".  
Once selected I would like to select from a dropdown a process. The dropdown aggregates all processes on all systems and groups them by process name. I would then select a process that I wish to monitor.

Once process is selected, I would like to be able to monitor it for multiple and/or conditions.
- Is the process running?
- Is the process using more/less than X MB RAM for a period of Y minutes.
- Is the process using more/less than % CPU for a period of Y minutes.

If a condition is detected, I would like the ability to run PowerShell command OR a script. On the command, I would like it to support parameters such as {{processname}}

**Describe alternatives you've considered**
Scheduled event that runs a script that does this check

**Additional context**
None at this time.

**Comment by wh1te909** [comment]
this is a very specific check and that's why we have script checks
you can translate all of this logic into a script in whatever language you're more comfortable with (python, batch or powershell) and just add it as a script check
