### ISSUE TITLE
Bug: Remove Check History older than (days): doesnt work 

### ISSUE THREAD

**Issue by dinger1986** [wh1te909/tacticalrmm#482]
Ubuntu 20.04, TRMM 0.6.8, Standard Install

When you change Remove Check History older than (days): from the default of 30 days to 4 days or something it doesnt clear until the 30 days are up.

<img width="652" alt="Screenshot 2021-05-06 at 22 51 18" src="https://user-images.githubusercontent.com/7244447/117370644-9ca4d700-aebe-11eb-8d20-f6a879ddc983.png">
<img width="1031" alt="Screenshot 2021-05-06 at 22 51 32" src="https://user-images.githubusercontent.com/7244447/117370648-9d3d6d80-aebe-11eb-8741-0085a6f221cf.png">

**Comment by wh1te909** [comment]
can you do the following and lmk what number it returns

```python
tactical@tacrmm:~$ /rmm/api/env/bin/python /rmm/api/tacticalrmm/manage.py shell
Python 3.9.2 (default, Feb 21 2021, 00:50:28)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from checks.models import CheckHistory
>>> from django.utils import timezone as djangotime
>>> import datetime as dt
>>> CheckHistory.objects.filter(x__lt=djangotime.make_aware(dt.datetime.today()) - djangotime.timedelta(days=6)).count()
```

I suspect it's a really high number and the db is having trouble deleting all at once. Might have to break it up into chunks

**Comment by wh1te909** [comment]
Actually not sure, just tried it on my instance and it deleted 1,397,969 db rows in around 1 second and now the check history only goes back 4 days. So not able to replicate. You can try running the command below and see what it does and if that fixes the problem.

```python
>>> CheckHistory.objects.filter(x__lt=djangotime.make_aware(dt.datetime.today()) - djangotime.timedelta(days=4)).delete()
(1397969, {'checks.CheckHistory': 1397969})
```

**Comment by bradhawkins85** [comment]
I recently cleared all history from my CheckHistory table (around 10,000,000 rows) only took about 10 seconds via Django shell.

**Comment by dinger1986** [comment]
Interesting, this is the output:

/rmm/api/env/bin/python /rmm/api/tacticalrmm/manage.py shell
Python 3.9.2 (default, Feb 22 2021, 09:37:06) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from checks.models import CheckHistory
>>> from django.utils import timezone as djangotime
>>> import datetime as dt
>>> CheckHistory.objects.filter(x__lt=djangotime.make_aware(dt.datetime.today()) - djangotime.timedelta(days=6)).count()
0
>>> CheckHistory.objects.filter(x__lt=djangotime.make_aware(dt.datetime.today()) - djangotime.timedelta(days=4)).delete()
(7430, {'checks.CheckHistory': 7430})

Still showing older checks for me

**Comment by wh1te909** [comment]
can you post a screenshot of one of the check run history graphs with the "Everything" date range selected plz

**Comment by dinger1986** [comment]
<img width="1144" alt="Screenshot 2021-05-07 at 08 37 16" src="https://user-images.githubusercontent.com/7244447/117414812-7b200b80-af0f-11eb-8280-3b1311b0f071.png">

So that is cleared down to the last 4 days

**Comment by dinger1986** [comment]
<img width="1061" alt="Screenshot 2021-05-07 at 08 38 36" src="https://user-images.githubusercontent.com/7244447/117414934-a3a80580-af0f-11eb-9ee7-771dea257936.png">

This check still shows up as faulty

**Comment by wh1te909** [comment]
the "remove check history older than x days" setting only removes graph history nothing else, so unless you see graph data older than may 4 then it's working as intended

**Comment by dinger1986** [comment]
ah ok, should it not clear faults then as well? I think Ill close this then and open a feature request to have that auto clear faults after x time.

**Comment by wh1te909** [comment]
ya that would be a new feature this one just removes graph data
