### ISSUE TITLE
Feature Request: Add automation policy to "all clients" level

### ISSUE THREAD

**Issue by manc74** [wh1te909/tacticalrmm#483]
It would be great to be able to apply automation policies to the top level "all clients" in addition to the current client levels.

**Comment by wh1te909** [comment]
im assuming you mean like a global policy for all clients? you can do this already from settings > global settings then just apply the policy under the default workstation/client dropdowns

**Comment by manc74** [comment]
Aah! Ok, i assumed that was just the default policy applied to a new workstation/server when the agent is installed rather than a generic top level policy - if that's the case, great and fine to close this!

**Comment by manc74** [comment]
Yes, just tested - can confirm this works as I needed - thanks, i'll close this now. :)
