### ISSUE TITLE
Feature Request: Clear faults on computers after x time

### ISSUE THREAD

**Issue by dinger1986** [wh1te909/tacticalrmm#484]
If a computer is showing in an errored state and is switched off it will stay in that errored state until it is switched on again or reconnected, I would like it tot auto clear errors after x amount of time so the client is clear again.

Ideally changing the days here would change it or something similar?
<img width="652" alt="Screenshot 2021-05-06 at 22 51 18" src="https://user-images.githubusercontent.com/7244447/117418403-4a41d580-af13-11eb-86b1-166281abb51c.png">

This si one computer thats been off for a month so whole client shows red.
<img width="1061" alt="Screenshot 2021-05-07 at 08 38 36" src="https://user-images.githubusercontent.com/7244447/117418414-4b730280-af13-11eb-8815-0a7538117fc1.png">

**Comment by wh1te909** [comment]
done will be in next release, see below

![chrome_jMIqg4atIz](https://user-images.githubusercontent.com/7434746/118223414-15afab80-b436-11eb-8bd7-152649220050.png)

**Comment by dinger1986** [comment]
thank you!

**Comment by wh1te909** [comment]
released in 0.6.10
