### ISSUE TITLE
Delete/Copy Automation Policy Issues

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#486]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Microsoft Edge Chromium 90.0.818.51 (Official build) (64-bit)
 - RMM Version (as shown in top left of web UI): 0.6.8

**Installation Method:**
  - [x ] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.5.5
- Agent OS: Windows 10 v2009

**Describe the bug**
Automation Manager does not delete policies properly, nor copy policies with all the tasks. Errors occur even though it seems to copy the policy and 1 task.

**To Reproduce**
1.) Go to Automation Manager -> New policy
2.) Add Task to policy.
3.) Try to clone policy, it will give 500 internal server error
4.) Delete policy from Automation Manager
5.) Try to recreate policy
6.) Will give error stating the policy already exists even though it was deleted from Automation Manager

Doing a refresh and coming back into Automation Manager will show the policy that was allegedly not created.

**Expected behavior**
Policies should delete completely when selected to within the Automation Manager. Policies should be able to be copied with Tasks.

**Comment by sadnub** [comment]
This will be fixed in the next release. Thanks!

**Comment by subzdev** [comment]
Thank you man, much appreciated.

**Comment by wh1te909** [comment]
released in 0.6.9
