### ISSUE TITLE
Existing MeshCentral server utilizing custom branding/custom MeshAgent.exe file path

### ISSUE THREAD

**Issue by PathfinderNetworks** [wh1te909/tacticalrmm#487]
**Server Info (please complete the following information):**
 - OS: Debian
 - Browser: Chrome
 - RMM Version (as shown in top left of web UI): 0.6.8

**Installation Method:**
  - [x ] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): No idea- can't get that far
- Agent OS: Windows 10 Pro

**Describe the bug**
We are a long time MeshCentral user with our own existing MeshCentral server containing hundreds of devices. We are trying to do a trial run of TactialRMM connected to our existing MeshCentral server.  We are able to connect TacticalRMM to the existing MeshCentral server without issue. However, the TacticalRMM agent install fails (or rather never progresses) due to it not being able to locate the MeshCentral agent on the device.  Our existing MeshCentral server is configured with custom branding and the MeshCentral agent uses a non-standard install path (C:\Program Files\Pathfinder Networks\Mesh Agent\).  Because the TacticalRMM agent installer ONLY looks for the MeshAgent at C:\Program Files\Mesh Agent\ it never progresses past the MeshCentral agent installer due to it not be able to locate the MeshAgent.exe file.  The installer continuously throws the message 'level=error msg="exec: \"C:\\\\Program Files\\\\Mesh Agent\\\\MeshAgent.exe\": file does not exit:'

**To Reproduce**
Configure TacticalRMM to utilize an existing MeshCentral server installation that uses custom branding/custom MeshAgent installer location. 

**Expected behavior**
The TacticalRMM agent should be able to be configured to look for the MeshAgent.exe in a non-standard folder.  Such as entering the file path info in the same Global Settings tab along with the MeshCentral username, Mesh Site, and Mesh Token. 

**Screenshots**
![error](https://user-images.githubusercontent.com/48607498/117590949-ddd7f980-b0ff-11eb-9ef0-57bb3f0971e2.JPG)

**Additional context**

**Comment by wh1te909** [comment]
i'll add an optional installer flag to the agent for this

atm you can pass `-local-mesh="C:\path\to\meshagent.exe"` but this is just to avoid the installer downloading the mesh agent from the rmm (the one you uploaded during install). it's still hardcoded to look in `program files\mesh agent` after the initial install.

if you want to use your own meshcentral instance and not the one tactical installs then you'll need to create a mesh user that has access to all agents and device groups

**Comment by wh1te909** [comment]
Added, please update to rmm v0.6.9 and generate a new exe (agent v1.5.6)

you can pass the directory containing `MeshAgent.exe` to the installer e.g. `rmm-trmm-client-site-server.exe -meshdir "C:\Program Files\Your Company Name\Mesh Agent"`

see https://wh1te909.github.io/tacticalrmm/install_agent/#optional-installer-args for all optional installer args

**Comment by PathfinderNetworks** [comment]
Thank you, I will give this a try.  I appreciate the quick response!

**Comment by PathfinderNetworks** [comment]
I tested this update this evening.  Works perfectly.  Thank you.

**Comment by ioscanner** [comment]
> see https://wh1te909.github.io/tacticalrmm/install_agent/#optional-installer-args for all optional installer args

This path doesn't work.

**Comment by dinger1986** [comment]
URL is now https://docs.tacticalrmm.com/install_agent/#optional-installer-args
