### ISSUE TITLE
Feature Request: Patch Management Policy

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#49]
Would it be possible to add patch management settings to the policy manager?

**Comment by sadnub** [comment]
@wh1te909 Would this need to be another tab in the policy manager? Similar to how checks/tasks are setup? It might be tricky to know when to override the agent windows update settings since they are added on agent creation.

**Comment by sadnub** [comment]
@bradhawkins85 Patching policies have been added to Automation manager. I just submitted a PR to allow bulk updating the agent patch policies to inherit from an automation policy if one exists. You can update the Agent auto approval settings to inherit and it will pull the patch policy.

**Comment by bradhawkins85** [comment]
Thank you @sadnub 
What happens with the, Installation Schedule, Reboot After Installation and Failed Patches settings. Are these automatically inherited by an agent or ignored when a patch policy is applied?
It would be good if they could inherit from the policy but also be set manually like the approvals.

**Comment by sadnub** [comment]
@bradhawkins85 Currently, if a policy is inherited, it will use the policies settings on the agent. I could allow for overriding the other settings on the agent as well. I will work on that. Thanks!

**Comment by bradhawkins85** [comment]
May or may not have just had an issue with the patch schedule. otherwise the issue is with my setup.
I applied the policy to a server to install at 2am and reboot if needed, the updates installed at 7pm instead and rebooted the server.
The client server has the correct time as does the RMM server. I have also got the correct timezone set in Default agent timezone.
Could this be a timezone thing with a component installed on the RMM server? I notice when I manually run a task the Last Run Time shows as UTC but the Last Response time shows as local time (UTC +10).

**Comment by wh1te909** [comment]
@bradhawkins85 please try now we just fixed timezone issues and im still testing but so far so good, i just had 10 workstations update at the correct local time which were not working before. Still need to work on showing the correct timezone on the frontend everywhere that there is a date, because now it's a mix of UTC and agent local time.
