### ISSUE TITLE
Bug: Lenovo Systems don't Display proper model number

### ISSUE THREAD

**Issue by johnnyq** [wh1te909/tacticalrmm#490]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - RMM Version (as shown in top left of web UI): 0.6.8

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.5.5
- Agent OS: Win 10 2009

**Describe the bug**
All Lenovo Systems display the improper model number under summary > hardware details.

For example I have a computer Lenovo ThinkPad E560 that displays LENOVO 20EV002JUS under summary > hardware details.
Digging further if you click on Assets > Computer System The model number is listed as 20EV002JUS but if you scroll down further there is a variable called SystemFamily which gives the correct model ThinkPad E560. 
I think a fix for this would be a logic statement
if Manufacturer = Lenovo then Model = SystemFamily
 
**To Reproduce**
1. Add a Lenovo System
2. Click on the added Lenovo computer
3. Click Summary
4. You will see the Model being incorrect

**Expected behavior**
Display SystemFamily instead of Model for Lenovo Systems

**Comment by johnnyq** [comment]
Looking through more Lenovo System we noticed 3 out 30 Lenovo Systems have
the variable SystemFamily as To be filled by O.E.M. under Summary > Computer System
So another Logic statement would be If SystemFamily = To be filled by O.E.M. then use Model Field for all Lenovo Computers

**Comment by johnnyq** [comment]
@dinger1986 will check and report back

**Comment by dinger1986** [comment]
I'll be honest it's only from interest, but if it does work then should be able to find out how they are doing it, if it doesn't then helps them as well!

**Comment by wh1te909** [comment]
@johnnyq i've implemented this see the commit above, if you can please try it out and lmk. just edit that file on your prod server and add the changes i made, and then do a `sudo systemctl restart rmm` and refresh your dashboard and lmk if looks good

**Comment by wh1te909** [comment]
released in 0.6.9 i tested on a lenovo laptop

**Comment by johnnyq** [comment]
@wh1te909 That is fantastic!! Thanks it works so much better now!! =]
