### ISSUE TITLE
sort GUI column Check Status doesn't quite work

### ISSUE THREAD

**Issue by bbrendon** [wh1te909/tacticalrmm#491]
If you sort the column by Check Status (screenshot below), the yellow check marks do not sort. They just get intermingled in with the green ones. The red and green sorting does work.

![image](https://user-images.githubusercontent.com/6364477/117742136-e5a7a480-b1b8-11eb-9486-395028307d40.png)

**Comment by wh1te909** [comment]
released in 0.6.9
