### ISSUE TITLE
Feature: Remove non informational text from agent summary

### ISSUE THREAD

**Issue by johnnyq** [wh1te909/tacticalrmm#498]
**Is your feature request related to a problem? Please describe.**
Taking a less is more approach (see screenshot below). Remove (R) (TM) under Summary > Hardware details for intel CPUs and Intel Graphic Cards

Also for PC Manufacturers

- Microsoft Corporation (Remove Corporation)
- Dell Inc. (Remove Inc.)

I also noticed for HP Systems that the Manufacturer is in the model number so a logic statement for this would be if manufacturer == HP OR  manufacturer == Hewlett-Packard then display just model number under summary > Hardware Details.

![image](https://user-images.githubusercontent.com/1812594/118024572-d77a9500-b32c-11eb-88e7-57a87f118989.png)

![image](https://user-images.githubusercontent.com/1812594/118024787-17417c80-b32d-11eb-9b7e-69fc04ded972.png)

![image](https://user-images.githubusercontent.com/1812594/118024850-27595c00-b32d-11eb-9760-d9e6b9bf136d.png)

![image](https://user-images.githubusercontent.com/1812594/118024904-37713b80-b32d-11eb-82bb-5d2cb0cbe3e7.png)

**Comment by sadnub** [comment]
I feel this would be too much effort to maintain given our limited resources and would most likely introduce bugs down the line as vendors change this information. We could consider this in the future.
