### ISSUE TITLE
Automation Manager - Policy Exclusions for Excluded agents add description in display

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#499]
When you have multiple machines with the same name you can't tell them apart.
Change display to: Hostname (description) - Client: Site

![2021-05-12_143453 - Adding data to menu display](https://user-images.githubusercontent.com/13395348/118027098-8ae48900-b32f-11eb-830f-e9e2ad95f32e.png)

**Comment by wh1te909** [comment]
released in 0.6.10
