### ISSUE TITLE
Automation Manager - Policy Exclusions for Excluded agents not removing checks/tasks.

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#500]
**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Describe the bug**
Excluded agents from an Automation Policy still have the Checks and Tasks applied to them (but it does clear their warnings/errors from global notification area

![2021-05-12_150452 - automation exclusion](https://user-images.githubusercontent.com/13395348/118030541-70acaa00-b333-11eb-92b2-7658fcb48f7b.png)

**To Reproduce**
1. Create Automation Policy (I'm using global workstation atm)
2. Checks are pushed to client by policy
3. Edit Policy, add agent as excluded agent (Also tested Client and does the same)
4. Expect the policies to be removed from client.

**Expected behavior**
All checks/tasks from policy should be removed from excluded agents. Looks like even though the checks are still there and erroring, they're being excluded from 

![2021-05-12_150235 - automation manager excluded agent](https://user-images.githubusercontent.com/13395348/118030378-35aa7680-b333-11eb-8abf-13a7d0f348b6.png)

**Comment by sadnub** [comment]
I tested and this is definitely an issue. I will release a fix, but you can get around it by right-clicking on the Policy you added exclusions to and syncing.

**Comment by wh1te909** [comment]
released in 0.6.10
