### ISSUE TITLE
Default script values being ignored

### ISSUE THREAD

**Issue by davidrudduck** [wh1te909/tacticalrmm#501]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - RMM Version (as shown in top left of web UI): v0.6.9

**Installation Method:**
  - [ X ] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2]

**Describe the bug**
When running a script using a Client variable (being passed to the script), if there was a default value set for the variable in Global Settings but it was not set in the individual Client page, it would use the default value. It is currently not passing that value to the script.

**To Reproduce**
1. Create {{Client.ScreenConnectService}}
2. Create Script with parameter -serviceName {{Client.ScreenConnectService}}
3. Check to see whether the value is passed to $serviceName without setting the Client value

**Expected behavior**
Global Settings defined "default values" get passed to the script when a value isn't set.
![2021-05-13_09h24_07](https://user-images.githubusercontent.com/47308254/118056324-1829eb00-b3cd-11eb-96f3-5c081b29253d.png)

**Comment by wh1te909** [comment]
im not able to reproduce, unless i'm not doing it correctly. i recorded a gif please watch it and lmk if it looks correct

![6YiTiAd7Wc](https://user-images.githubusercontent.com/7434746/118218690-d03ab080-b42c-11eb-9fa3-33b6c9df0c14.gif)

**Comment by davidrudduck** [comment]
Frack.

Is it possible the custom variable for a site has a null value in it?

If I change it from blank to "test" on one site, it works. But if I delete the contents of the field and save and re-run, it shows blank again.

**Comment by wh1te909** [comment]
ok yes i see the bug now. tagging @sadnub 

if you edit a client or site and just change the client/site name, but don't set a value for the custom field, or if there was a custom field value set for that client and you cleared it, it's still being saved in the db as an empty string and so the default value is not being applied because rmm thinks it's being overridden. so we need to exclude empty strings.

**Comment by wh1te909** [comment]
released in 0.6.10
