### ISSUE TITLE
Feature Request: Debug script from script editor

### ISSUE THREAD

**Issue by davidrudduck** [wh1te909/tacticalrmm#502]
When editing and testing scripts it is currently a little cumbersome to edit script, close modals, run script, see output, go back and edit script.

It would be AMAZING to add a "Debug Script" button next to "SAVE" script, which pulls up the "Run Script" dialogue and lets you pick a client/location/agent to run the script again and view the debug output.

Then revert back to the script editor to make any corrections.

**Comment by wh1te909** [comment]
released in 0.8.0 (see release notes)
