### ISSUE TITLE
MFA: Remember this device for 30 days

### ISSUE THREAD

**Issue by davidrudduck** [wh1te909/tacticalrmm#503]
This may be a conscious decision to enforce MFA checks upon EVERY login.

It would be great to have the ability to 'remember' the device so it's quicker to get back into when you're always on the same device.

Tell me to STFU if this is never going to happen ;)

**Comment by fred5632** [comment]
I agree, this is a nuisance

**Comment by bradhawkins85** [comment]
This would be a really nice to have feature.
Would be good if the timeout was selectable though with options ranging from 1 hour to 30 days.

**Comment by saulens22** [comment]
A week sounds like a reasonable default for RMM tool

**Comment by frankemann** [comment]
Even better would be a SSO with Azure Ad. We could then utilize Azure Ad Conditional Access based on our existing secutiry policies from ONE identity/device platform.

**Comment by davidrudduck** [comment]
Maybe an option to set the timeout in hours, and you just do the math with the maximum value being 720 hours (30 days) or something?

**Comment by wh1te909** [comment]
yea the auth token is hardcoded now to 5 hours TTL, with auto refresh happening every 600 seconds so basically if you leave your browser open forever with trmm logged in you'll never be logged out.

I can move this into `local_settings.py` and then you can just set it to whatever you want.

For now you can just edit `settings.py` which is in `/rmm/api/tacticalrmm/tacticalrmm` and look for this section https://github.com/wh1te909/tacticalrmm/blob/67cc37354a18f8a310065fe55a44044cc9a95c76/api/tacticalrmm/tacticalrmm/settings.py#L108

and change the `(hours=5)` to `(days=30)` or whatever you want

then `sudo systemctl restart rmm` for changes to take effect

note `settings.py` will be overwritten on every rmm update but `local_settings.py` will not so next release i'll move it but for now just try the above and lmk if works

**Comment by davidrudduck** [comment]
Ah-may-zing ❤️

**Comment by wh1te909** [comment]
released in 0.6.10 see https://wh1te909.github.io/tacticalrmm/functions/settings_override/ for instructions

**Comment by ventra007** [comment]
> released in 0.6.10 see https://wh1te909.github.io/tacticalrmm/functions/settings_override/ for instructions

This link is dead. The new link is https://docs.tacticalrmm.com/functions/settings_override/
