### ISSUE TITLE
Existing MeshCentral server - Invalid Mesh Token

### ISSUE THREAD

**Issue by PathfinderNetworks** [wh1te909/tacticalrmm#504]
**Server Info (please complete the following information):**
 - OS: Debian
 - Browser: MS Edge
 - RMM Version 0.6.9

**Installation Method:**
  - [x ] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.5.6
- Agent OS: Win 10 Pro 20H2

**Describe the bug**
Not sure if this is a bug or if I'm just not configuring TacticalRMM correctly.  I have an existing MeshCentral server (running version 0.8.33) that I am attempting to connect a new install of TacticalRMM to.  I have generated the login token on the MeshCentral server and have entered the token information in to the MeshCentral table under Global Settings.  
The TacticalRMM agent installer (when used with the new -meshdir argument) does go out and downloads the Mesh agent and installs it correctly.  However, when I try to take control of a device through TacticalRMM I am getting a 'Invalid mesh token 400: bad request" error (as shown in the attached screen grab).  

**To Reproduce**
1. Go to a device in Tactical. 
2. Right click on the device and choose 'Take Control' in the menu that appears. 

**Expected behavior**
Remote control of the device should initiate.  

**Screenshots**

**Additional context**
As mentioned, I'm not certain if this is a bug or if I'm just not configuring something correctly. I looked through the documentation and searched Github but wasn't able to find any mention of this error. 
![meshtoken](https://user-images.githubusercontent.com/48607498/118060423-c6e41200-b360-11eb-96d9-2c6dd0c5f74c.JPG)

**Comment by wh1te909** [comment]
what command did you run to generate the login token?

should be `node /meshcentral/node_modules/meshcentral --logintokenkey` just replace with your path to your mesh install

also check the `install.sh` script for the config.json that is generated, there are a few settings there you need to have enabled for framing to work, make sure those are in your config.json

if still not working then read through the install script and see how im setting up mesh users etc and try to replicate on your setup. lmk if need exact commands to run
