### ISSUE TITLE
Right click "run script" not sorting script folder names alphabetically

### ISSUE THREAD

**Issue by manc74** [wh1te909/tacticalrmm#506]
Right click on an agent then > Run Script > Select Script

The list of scripts should be sorted in alphabetical order first by folder then by script name to make it easier to find. It currently only seems to sort by script name, and folders they are in are randomly listed.

**Comment by wh1te909** [comment]
i am redoing the interface to add search and make it easier to select scripts so this will be fixed when i implement #374

**Comment by sadnub** [comment]
Added categories sort in scripts dropdown will be in next release

**Comment by wh1te909** [comment]
released in 0.6.10
