### ISSUE TITLE
Easy Copy and paste feature.

### ISSUE THREAD

**Issue by abraham990201** [wh1te909/tacticalrmm#509]
We know that if we want to copy or paste text, document, file we have to click in the "type" button in the bottom (in case of text) but, is there a way so you guys make this option straight forward? just typing CTRL+C and CTRL+V to paste whatever we want? such as TeamViewer does.

**Comment by wh1te909** [comment]
hi, this is handled by meshcentral. you need to open up a ticket there https://github.com/Ylianst/MeshCentral

**Comment by abraham990201** [comment]
Thanks
