### ISSUE TITLE
Feature Request: Better Downloadable Installer/Script

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#51]
Would it be possible to have an exe or msi generated when using Install Agent to automate the install process rather than downloading the winagent.exe then running the command with arguments.

Or, below is the PowerShell script I have written to install the agent, can there be a button added beside Show Install Command that generates the install ps1 script and fills the variables?

`$installversion = 'winagent-v0.10.1'
$api = '"https://api.example.com"'
$clientid = '1'
$siteid = '1'
$agenttype = '"server"'
$power = '0'
$rdp = '1'
$ping = '1'
$auth = '"authkey"'
$downloadlink = 'https://github.com/wh1te909/winagent/releases/download/v0.10.1/' + $installversion + '.exe'

$serviceName = 'tacticalagent'
If (Get-Service $serviceName -ErrorAction SilentlyContinue) {
    write-host ('Tactical RMM Is Already Installed')
} Else {

    $OutPath = $env:TMP
    $output = $installversion + ".exe"

    Try
    {
        Invoke-WebRequest -Uri $downloadlink -OutFile $OutPath\$output
        Start-Process -FilePath $OutPath\$output -ArgumentList ('/VERYSILENT /SUPPRESSMSGBOXES && timeout /t 20 /nobreak') -Wait
        Start-Process -FilePath "C:\Program Files\TacticalAgent\tacticalrmm.exe" -ArgumentList ('-m install --api ', "$api", '--client-id', $clientid, '--site-id', $siteid, '--agent-type', "$agenttype", '--power', $power, '--rdp', $rdp, '--ping', $ping, '--auth', "$auth") -Wait -RedirectStandardOutput 'C:\Program Files\TacticalAgent\output.txt' -RedirectStandardError 'C:\Program Files\TacticalAgent\err.txt'
        exit 0
    }
    Catch
    {
        $ErrorMessage = $_.Exception.Message
        $FailedItem = $_.Exception.ItemName
        Write-Error -Message "$ErrorMessage $FailedItem"
        exit 1
    }
    Finally
    {
        Remove-Item -Path $OutPath\$output
    }
}`

**Comment by wh1te909** [comment]
Yes awesome! I'll add a 2nd button for powershell that will generate your script and fill in the vars.

As for the exe, would you want it to be like generated on the spot with all the variables already baked into the exe ( no need to pass any vars so basically one time use or for however long the token is active for) or like a generic exe that you would still need to pass arguments to?

**Comment by bradhawkins85** [comment]
You're a legend, thank you.

Generated on the spot with all the variables already baked into the exe would be perfect, that way it's a straight download and install no messing around.

**Comment by wh1te909** [comment]
ok cool. I don't think that's possible with python since cross compiling is basically impossible with PyInstaller but should be pretty simple to do with Golang, I have cross compiled exe's for windows from a linux box before with go. Finally a reason to start learning Go again xD

**Comment by dinger1986** [comment]
Hello,

I wrote a bat file last night that will do it as well, its a little rough but does work well.

net use Z: "\\**servername**\**sharename**\TacticalRMM"
Z:
winagent-v0.10.1.exe /VERYSILENT /SUPPRESSMSGBOXES
"C:\Program Files\TacticalAgent\tacticalrmm.exe" -m install --api "https://api.mydomain.com" --client-id 1 --site-id 1 --agent-type "server" --power 0 --rdp 0 --ping 0 --auth "**authkey**" --local-salt salt-minion-setup.exe --local-mesh meshagent.exe
C:
net use /d Z: /y

I have thought about pulling it together into a sfx file would be cool if that can be done automatically.

**Comment by wh1te909** [comment]
WIP in 8177234b322157ee34bb5dfac0eba9f740cf6aa3 please run update script and try it out
For now I added the single binary option with cli args baked in, plus your powershell script @bradhawkins85

**Comment by KenGrant** [comment]
Hi - Great to see all this help.

Where do you get the --auth "authkey" from? Or is there no substitution for it needed?

Thanks

**Comment by dinger1986** [comment]
This is working fine from the command line with no arguments, should do everything everyone needs now.

**Comment by bradhawkins85** [comment]
Confirmed all working as expected with new Go agent. thank you.
