### ISSUE TITLE
Possibility to add multiple automation policy to one site

### ISSUE THREAD

**Issue by lclainsg2a** [wh1te909/tacticalrmm#511]
**Describe the solution you'd like**

It would be nice if we can add multiple automation policy for one site.

**Describe alternatives you've considered**

Or add the possibility to exclude specifics agents for a specific task or check from an automation policy.

Thanks

**Comment by dinger1986** [comment]
Can you please fill in the description?

**Comment by dinger1986** [comment]
Is that per machine? Or where would this be used?

**Comment by lclainsg2a** [comment]
> Is that per machine? Or where would this be used?

Actually, I want to exclude this specific agent for checking my Wireguard server.
Maybe we can add a button "Exclude" in the submenu :

![Capture](https://user-images.githubusercontent.com/21194770/118261677-2ef73d00-b4b4-11eb-8800-9b959c375c11.PNG)

**Comment by dinger1986** [comment]
But would you not be better just manually adding ping checks to the devices you want to?

EG I have one device on a network doing ping checks and speed tests for internet

**Comment by lclainsg2a** [comment]
Yes, I will do that for my 250 agents.

Thanks

**Comment by dinger1986** [comment]
I was making a suggestion, I wouldnt have thought on a network you need every machine to be pinging a server, but its your network,

I suggest reopening this and letting the dev decid. 

I was trying to fully understand what you were asking for as at the moment you can assign an automation policy to individual machines and block the inheritance so from there you could add other checks

**Comment by WouterLS** [comment]
It would be nice to have the checks have some kind of assignment policy so you could define that a certain check only gets deployed on certain agents.
for instance: ping check Wirecheck - only deploy if IP = 192.168.x.x or location is xxx
