### ISSUE TITLE
Bug: Run URL action menu item misaligned

### ISSUE THREAD

**Issue by manc74** [wh1te909/tacticalrmm#512]
On the right click context menu, the "Run URL Action" menu item is not aligned with the rest of the items in the list.

![b15711aa9241bcead81c493a81e9d8a5](https://user-images.githubusercontent.com/68019920/118257932-23514980-b4a7-11eb-972d-34f31dc1dc4c.png)

**Comment by sadnub** [comment]
Fixed will be in the next release

**Comment by wh1te909** [comment]
released in 0.6.10
