### ISSUE TITLE
Feature Request: Run Tasks on Frequency

### ISSUE THREAD

**Issue by davidrudduck** [wh1te909/tacticalrmm#513]
Presently to run a check command the options are kind of "all or nothing"

Run Once, Run At Set Date/Time, etc

It would be great if you could say:
- Run every x hours/days/weeks
- Run between this time and this time (say 9am and 5pm). ie: only run this task between certain times (and therein every however interim period as above)
- Spread execution between this time and this time. ie: Execute once every hour between 9am and 5pm, but spread the checks across the hour so it's not running on every machine at once.

**Comment by johnnyq** [comment]
+1

**Comment by wh1te909** [comment]
should be possible as long as all these settings exist in windows task scheduler cuz that's what we're using atm for automated tasks

**Comment by sadnub** [comment]
This will be in the next release
