### ISSUE TITLE
BUG: Tasks not passing value properly

### ISSUE THREAD

**Issue by davidrudduck** [wh1te909/tacticalrmm#514]
v0.6.10 on Ubuntu 20.04.

Set script as "Task" (not "Run Script") "ScreenConnect (Get ID)" with value `-serviceName {{global.ScreenConnectService}}`

The value being passed to the script is `{global.ScreenConnectService}` not the actual value of the variable.

When RUNNING script manually, variable passes fine.

```
Get-Itempropertyvalue : Cannot find path 'HKLM:\SYSTEM\ControlSet001\Services\{global.ScreenConnectService}' because 

it does not exist.

At C:\WINDOWS\TEMP\trmm\899027387.ps1:28 char:14

+ $imagePath = Get-Itempropertyvalue $regPath -Name "ImagePath"
```

**Comment by wh1te909** [comment]
ah oops forgot to set the tasks to use the new function lol. will fix in next release

**Comment by davidrudduck** [comment]
I am the bug finding master 😅
