### ISSUE TITLE
agent overdue after certificate renewal

### ISSUE THREAD

**Issue by mandelbrotmedia** [wh1te909/tacticalrmm#515]
**Server Info (please complete the following information):**
 - OS:  Ubuntu 20.04.2 LTS
 - Browser: CHROME
 - RMM Version (as shown in top left of web UI): v0.4.7

**Installation Method:**
  - [x ] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v1.4.4
- Agent OS: win10

**Describe the bug**
last week the certificate runs out on may 12th / on may 13th i renewed it / after that all agents are in status "agent overdue"
i tried to reboot and agent recovery but it still says "agent overdue"

![image](https://user-images.githubusercontent.com/11631505/118491606-746b7280-b71f-11eb-973d-a406b1d16f8c.png)

How can i get the agents back online?

**Comment by bradhawkins85** [comment]
You need to run the update script after renewing the certificate:
See the Keeping your Let's Encrypt certificate up to date section on https://wh1te909.github.io/tacticalrmm/update_server/
./update.sh --force

**Comment by mandelbrotmedia** [comment]
thanks for you reply.
After update i get this:

`10 packages can be upgraded. Run 'apt list --upgradable' to see them.
Nginx config changes required before continuing.
Please check the v0.5.0 release notes on github for instructions, then re-run this script.
https://github.com/wh1te909/tacticalrmm/releases/tag/v0.5.0
Aborting...
`

**Comment by dinger1986** [comment]
which version are you on?

**Comment by mandelbrotmedia** [comment]
for some reason i missed the part with editing rmm.conf as writen here: https://github.com/wh1te909/tacticalrmm/releases/tag/v0.5.0

i have 63 agents for now. i try to update but if it fails i reinstall it from scratch.

thanks for your help!

**Comment by dinger1986** [comment]
see how it goesm you might be able to force an update through, especially if you have everything in place, you might need to upgrade the agents manually to 1.4.12

**Comment by mandelbrotmedia** [comment]
the update was successful:

![image](https://user-images.githubusercontent.com/11631505/118639356-1b134a00-b7d8-11eb-8e60-85255889b24c.png)


the agents updated to v1.5.6

**Comment by dinger1986** [comment]
perfect!
