### ISSUE TITLE
GitHub Integration, or simply Git Clone capability, for scripts.

### ISSUE THREAD

**Issue by wiicode** [wh1te909/tacticalrmm#517]
**Is your feature request related to a problem? Please describe.**
I want to manage my scripts using Visual Code and easily make them available.  Best way for me to do that is commit them to GitHub (or maybe BitBucket). I would like my agents to routinely clone latest versions of the scripts to run as needed. 

**Describe the solution you'd like**
I see this working one of two ways:
- Agent clones a repository specified in preferences.
- TacticalRMM server clones, using keys, repositories I designated in GitHub to itself, allows me to view and work with the scripts (including commit changes), but then also ensures a cached copy is available on every agent. 

**Describe alternatives you've considered**
Manually scripting all this, it's a PITA.

**Additional context**
There is no RMM that I've seen that does this seemingly obvious thing....

**Comment by sadnub** [comment]
You can use the github https link to pull the script and run them. It will always get the latest script based on the branch you use. I don't think adding git as prereq is the right approach, but I might be misunderstanding the request.

https://github.com/wh1te909/tacticalrmm/blob/develop/scripts/Win_10_Upgrade.ps1

That as an example will pull the latest script file and you can create a runner script with the url as an argument. Or built all of the scripts into trmm with the arg statically set.
