### ISSUE TITLE
tactical rmm

### ISSUE THREAD

**Issue by Seoking007** [wh1te909/tacticalrmm#524]
i m install in ubuntu

in ubuntu my domains successful open and work also

but now  i m open link in my orther pc.. thatsmen i m sending rmm link to other when they open link message show site is not working

i think ip issue.. but i dont which ip is update on DNS

also i dont knwo how to find tactical ip in ubuntu

**Comment by dinger1986** [comment]
Did you report this on discord?

The IP will be the IP you have forwarded your DNS to.

If you need to find the local IP you should be able to type in ip -a but you can find basics on how to use Ubuntu via google.

Also tell use more about your setup? Is it a vps? Machine in your house/office? VM?

**Comment by Seoking007** [comment]
VM?

**Comment by dinger1986** [comment]
VM - Virtual Machine

**Comment by Seoking007** [comment]
??

**Comment by Seoking007** [comment]
VM - Virtual Machine

**Comment by Seoking007** [comment]
yes

**Comment by Seoking007** [comment]
can we install kali and ubuntu

**Comment by Seoking007** [comment]
can you tell me

**Comment by dinger1986** [comment]
How to use kali and Ubuntu is not anything to do with tactical rmm.

**Comment by Seoking007** [comment]
how to use tactical rmm tell me

**Comment by dinger1986** [comment]
Have you reviewed the docs?

https://wh1te909.github.io/tacticalrmm/

**Comment by Seoking007** [comment]
Can you tell how to use tactical on public ip

**Comment by dinger1986** [comment]
Have you followed the guide?

Did you open the necessary ports?

**Comment by Seoking007** [comment]
Not

**Comment by Seoking007** [comment]
Can I open or not

**Comment by Seoking007** [comment]
How can I use publicly

**Comment by Seoking007** [comment]
Plzz tell me how to find ip and how to publicly
