### ISSUE TITLE
Allow Run Scripts to Collect Custom Variables

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#527]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add the ability for Run Script / Manually Executed Scripts to run as collector tasks.
EG, ScreenConnect AIO can install / run the app but also fill in a custom field for the agent the script in executed against.

**Describe alternatives you've considered**
Run a separate collector task using automation manager.

**Additional context**

**Comment by wh1te909** [comment]
released in 0.8.0
