### ISSUE TITLE
Feature question:  Is there a simple online/offline check w/ email?

### ISSUE THREAD

**Issue by kb8zgl** [wh1te909/tacticalrmm#53]
I see where I can add PING checks, but I don't know if that will work to internal machines (my RMM is not on the same network).

What I really want is an alert via email if a machine fails to check in, stops reporting or goes offline for certain machines.

Did I miss where to set this?

Thanks!

**Comment by wh1te909** [comment]
yea just right click on an agent then Edit Agent and you'll see 'Send an overdue alert if the server has not reported in after'

Default is 30 minutes. The 2 checkboxes (SMS alert and Email alert) at the very left next to each agent on the main dashboard are for this, so checking them and you'll start getting alerts after 30 min of no check in (or whatever time you set in Edit Agent).

SMS is not working yet but email is.
