### ISSUE TITLE
Can't add return codes for script checks

### ISSUE THREAD

**Issue by guillaumebottollier** [wh1te909/tacticalrmm#537]
**Server Info (please complete the following information):**
 - OS: Debian 10
 - Browser: chrome and firefox
 - RMM Version (as shown in top left of web UI): 0.6.11

**Installation Method:**
  - [ X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.5.6
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2] Windows

**Describe the bug**
When creating a script check, it's not possible to had return codes informational or warning, pressing enter has no effects

**To Reproduce**
create a script check and try to had codes informational or warning

**Expected behavior**
code should be added

**Screenshots**
![image](https://user-images.githubusercontent.com/84961534/119952024-dd16e280-bf9c-11eb-8335-d54ac0000637.png)

**Additional context**

**Comment by sadnub** [comment]
Exit codes need to be a number. Also for powershell, make sure you set the exit code like this:

```
$host.SetShouldExit($exitcode)
exit
```

Due to the way scripts are executed the actual exit code won't come through properly with this.

Hope this helps!

**Comment by wh1te909** [comment]
https://shapeshed.com/unix-exit-codes/#what-is-an-exit-code-in-the-unix-or-linux-shell

**Comment by guillaumebottollier** [comment]
Great, this works ! many thanks !
