### ISSUE TITLE
Saving Script output to note

### ISSUE THREAD

**Issue by lifeoflejf** [wh1te909/tacticalrmm#538]
I have to run a script on all of my computers, and look at the output for an audit. Would it be possible to save the output to the notes section of the machine?

Expanding on this, it would be really cool to have a script history tab in the machines, so that I could see which scripts have been run, and their output.

One last small thing, currently when you edit a note, you can't resize it horizontally. Is that something that could be added?

Love the software!

**Comment by wh1te909** [comment]
doesn't rly make sense to save to a note, your 2nd idea is much better and sadnub is working on that (history tab with all actions for that agent including script output)

plz create separate issue for the edit note resize

**Comment by wh1te909** [comment]
added in 0.8.0
