### ISSUE TITLE
Feature Request: add event log check for all event id's

### ISSUE THREAD

**Issue by notadevcollins** [wh1te909/tacticalrmm#54]
I would love the ability to add an event id of * or all or something of the sort so that I can add a check for all error's in each of the event log categories, thank you!

**Comment by wh1te909** [comment]
will do! will be in the next agent release hoping to get it out by the end of the week

**Comment by notadevcollins** [comment]
thank you!

**Comment by wh1te909** [comment]
gonna re-open for tracking, close please once this feature is added i'll let you know when :)

**Comment by wh1te909** [comment]
this has been added in 7dd9658213ff955fc9ef70b20a251a96d206af74 you'll also need agent v0.10.2 you can update your agents from the web: Agents > Update Agents then give it a few min and try it out

**Comment by notadevcollins** [comment]
well done, works as expected, server update and workstation update was also smooth
