### ISSUE TITLE
Windows 10 21H1 showing as v2009

### ISSUE THREAD

**Issue by djsvi** [wh1te909/tacticalrmm#542]
Minor issue. Windows 21H1 (build 19043.x) is now generally available, please add this to the detected/displayed versions (instead of showing v2009).

**Comment by wh1te909** [comment]
Hi I don't maintain any list, this is handled by windows, it reports the version in `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ReleaseId` if you know of another place to get it lmk

**Comment by djsvi** [comment]
OK, how about DisplayVersion, under that same key?

**Comment by wh1te909** [comment]
hmm, that one doesn't exist on 2004 and earlier but I do see it on a 21H1 machine so maybe MS added it. I'll check for that and fallback to ReleaseId if doesn't exist, ty

**Comment by wh1te909** [comment]
done, will be in next release

**Comment by wh1te909** [comment]
released in 0.6.14 (requires agent 1.5.8)
