### ISSUE TITLE
Disable Patch Management after having enabled it

### ISSUE THREAD

**Issue by guillaumebottollier** [wh1te909/tacticalrmm#546]
**Server Info (please complete the following information):**
 - OS: [Debian 10]
 - Browser: chrome,firefox
 - RMM Version (as shown in top left of web UI):

**Installation Method:**
  - [X ] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version : 1.5.6
- Agent OS:  Windows server 2019

**Describe the bug**
After creating am automation policy containing a patch mangement policy, i have applied it on some agents, and then remove the policy.
Now the agents still shows the pending patches.

**To Reproduce**
as described before

**Expected behavior**
Remove all the patch actions/reports when no patch policy is applied

**Screenshots**
![image](https://user-images.githubusercontent.com/84961534/120155255-e8624c00-c1f0-11eb-92d9-3614e6fcc04b.png)
![image](https://user-images.githubusercontent.com/84961534/120155306-f3b57780-c1f0-11eb-95b0-bd4c6b8406de.png)

**Additional context**

**Comment by sadnub** [comment]
Removing the patch policy won't unapprove patches that it previously approved, but it won't approve any future patches.

**Comment by guillaumebottollier** [comment]
ok then after reanalyse the device, message disappear
