### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by krystophe** [wh1te909/tacticalrmm#552]
Hello,

I'm deploying the rmm agent on my laptop and I have exit status 1 
and a log level=error msg="exec c:\Program files \Mesh agent \Mesh agent.exe   files doesn't exist 

How can I solve that ?

**Comment by bradhawkins85** [comment]
Couple of things to check.
1) Did you upload the mesh agent to TRMM, File > Upload Mesh Agent?
2) Is your Anti-Virus removing the Mesh Agent.exe file

**Comment by krystophe** [comment]
Ok thanks I can see my laptop now
