### ISSUE TITLE
Running Tactical RMM Behind existing NPM Proxy

### ISSUE THREAD

**Issue by natoleet** [wh1te909/tacticalrmm#557]
Hi,

I'm after some advice in running Tactical RMM docker through an existing NPM Proxy (this reverse proxy currently handles my Wildcard certificates)

Essentially I just added my cert base64 from the existing NPM proxy into the .env file, then pointed NPM proxy addresses to the http port provided by the Tactical Nginx proxy (Double reverse proxy type setup)

The problem is, the Tactical reverse proxy seems to be doing some redirection as well, so now I end up in a redirection loop.

Would I be best to simply remove the Tactical Nginx Reverse proxy?

Any help with best practices with regards to integrating with an existing reverse proxy would be much appreciated.

**Comment by silversword411** [comment]
Personalized Proxy configuration is not supported by the TRMM devs, but there has been some documentation posted related to HAProxy and it's configuration requirements to work with TRMM and mesh (which I believe is similar to what you're asking about)

https://wh1te909.github.io/tacticalrmm/unsupported_scripts/

HTH

**Comment by silversword411** [comment]
...you could ask in Discord, maybe someone there can help: https://discord.com/channels/736478043522072608/736478043958149191

**Comment by wh1te909** [comment]
im not familiar with npm proxy, you'll need something that speaks wsgi tho to communicate with the django backend thru unix sockets so maybe research that
