### ISSUE TITLE
Feature Request: Set Meshcentral Consent/Notifications per automation policy

### ISSUE THREAD

**Issue by Brodur** [wh1te909/tacticalrmm#559]
I'd love to see the automation policy settings also have the ability to include the notification and consent settings in MeshCentral.
Would also be nice to see individual agent control too of course for overrides and exceptions.
Currently I set these in Mesh manually - would be nice to have them in the dashboard for sensitive clients/devices.

**Comment by dinger1986** [comment]
The issue with mesh is currently can't be controlled externally.

I'll close this but if you find info on changing these settings using the api or something we can always reopen this.

Otherwise you could open a feature request with mesh and then if they implement that control reopen this

**Comment by Brodur** [comment]
Spawned MeshCentral issue: https://github.com/Ylianst/MeshCentral/issues/2749

**Comment by Brodur** [comment]
As per https://github.com/Ylianst/MeshCentral/issues/2749#issuecomment-859812838

There should be an API available soon!
