### ISSUE TITLE
Add Ability to Search Applications & Services Logs to Event Log Tasks Functionality

### ISSUE THREAD

**Issue by rfost52** [wh1te909/tacticalrmm#560]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
When setting up a task for Event Log check, I'd like to be able to use event IDs that are logged outside of the "Big 3" Logs (Application, System, Security); in the Applications & Services Logs section when using Windows Event Viewer for example.

**Describe alternatives you've considered**
Haven't considered any alternatives as of yet.  This is a very promising solution for what I aim to do as a 1 person consulting firm.

**Additional context**

**Comment by rfost52** [comment]
What I'm hoping to do is create tasks that can alert me if certain event IDs generated by Windows Defender are logged.  This may be useful for monitoring other applications that log entries in this general area as well.

**Comment by silversword411** [comment]
Check the script library (Settings | Script Manager): search for 
defender

already does what you're asking for.
Also if you want to query any event log type you want, here's an example querying the "Veeam Backup" log, customize to your taste:
https://github.com/wh1te909/tacticalrmm/blob/develop/scripts_wip/Win_Veeam_Backup_Script_Notification.ps1

**Comment by wh1te909** [comment]
the built in event log check is most likely going away and will just be converted into a community script check, like @silversword411 said you can probably use that one as an example and build off it to accomplish this. if you need help you can join our discord and ask in the scripts channel, i know people have definitely written script checks for exactly what you're trying to do
