### ISSUE TITLE
Github/fastly outage during update caused broken installation

### ISSUE THREAD

**Issue by fred5632** [wh1te909/tacticalrmm#563]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04, 
 - Browser: [e.g. chrome, safari]
 - RMM Version - going from 0.6.11 -> 0.6.13

**Installation Method:**
  - [x] Standard

**Describe the bug**
Im sorry I dont have the SSH output, so cant give you any great detail. But there is an outage at the moment affecting Github - it seems to be caused by Fastly CDN. I ran the update script during this outage, and it was unable to download some stuff, but it proceded with the update anyway. Afterwards the install was broken. It was just saying "Network error" on the login screen when i tried to login.

I kept trying the update script, and it eventually got what it needed and fixed itself. 

**Expected behavior**
I dont know how hard this is, but it might be worthwhile, whenever the update script needs to download a file, to check if this is successful before proceeding.

Just thought I would let you know, I am not sure how fixable this is.
Thanks

**Comment by dinger1986** [comment]
Forcing the update to run should have fixed the issues once GitHub was accessible again.

Being fair this is not something that's a common occurrence, the script does check in with GitHub before running so it's got checks in it.

I wouldn't imagine it's worth doing more with it but up to the devs.

**Comment by wh1te909** [comment]
hi yea you can just run `./update --force` to fix a botched update https://wh1te909.github.io/tacticalrmm/update_server/
