### ISSUE TITLE
Feature Request: list all network adaptors under LAN IP 

### ISSUE THREAD

**Issue by notadevcollins** [wh1te909/tacticalrmm#57]
Under my test machine it lists a network adaptor I dont care about, it would be great if it listed all attached network adaptors

**Comment by wh1te909** [comment]
fixed in edb3998c698f98f5e9ff6fdfd7a6e51abe4ec2ac (this is a bug, the intended behavior was to show all lan ips, but I indented one tab too much lol!)

please update using the update.sh script and let me know if working

**Comment by notadevcollins** [comment]
will update and post an update (hopefully tomorrow)

**Comment by notadevcollins** [comment]
updated, followed installation note for nginx and all went well, 
now I see the address of all the adapters, looks like you fixed it

thank you!
