### ISSUE TITLE
Have failing tasks color the Client/site in left tree

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#571]
**Server Info (please complete the following information):**
 - Browser: chrome
 - RMM Version (as shown in top left of web UI): 0.6.14

**Installation Method:**
  - [x ] Standard
  - [ ] Docker

**Describe the bug**
When task fails left list doesn't turn red
Also, emails for error tasks not sending. You want a 2nd issue report for those?

![2021-06-11_141411 - Task email alerts and left side color not changing](https://user-images.githubusercontent.com/13395348/121732139-da011380-cabf-11eb-97b5-99ded4227f95.png)

**Comment by wh1te909** [comment]
please provide full steps to reproduce from scratch. steps to create automation policy, policy check, alert template etc with all the settings

**Comment by silversword411** [comment]
I uninstalled and reinstalled the agent today, because....what doesn't that fix. I'll confirm tomorrow the status, see if problem is still there or resolved.

Only found the problem because it was hanging around in notifications.

**Comment by silversword411** [comment]
Doesn't look like it's coloring still for this agent. It's a task assigned by automation profile. Here's all the screens to re-create. The script is the default library script

![2021-06-16_101317 - 571 Agent colorization 1](https://user-images.githubusercontent.com/13395348/122235647-dbe62080-ce8b-11eb-9acc-a743317ae8e4.png)

![2021-06-16_101317 - 571 Agent colorization 2](https://user-images.githubusercontent.com/13395348/122235666-e0aad480-ce8b-11eb-886b-0a155e641d58.png)

The error the agent is throwing is this...but what kind of error shouldn't matter to the task

![2021-06-16_101317 - 571 Agent colorization 3](https://user-images.githubusercontent.com/13395348/122235964-19e34480-ce8c-11eb-9d01-0b0a52dce984.png)

**Comment by wh1te909** [comment]
OH lol. my bad, thought this was a script check 🤦 
so tasks currently don't make anything appear red in the clients tree, only failing checks
so i guess this would be a new feature to add

**Comment by silversword411** [comment]
> so i guess this would be a new feature to add

So let it be written....so let it be done: Enhancement

**Comment by wh1te909** [comment]
> > so i guess this would be a new feature to add
> 
> So let it be written....so let it be done: Enhancement

lmfao. done, will be in next release or if you don't want to wait, just manually add the changes i made and then `sudo systemctl restart rmm` and try it out

**Comment by silversword411** [comment]
Ummm...at some point I'm sure someone 👀 is going to ask for another column for task status (same as checks) 

![2021-06-29_013359 - tasks summary column](https://user-images.githubusercontent.com/13395348/123742857-5e061a00-d87a-11eb-9e78-c9652d7fc06c.png)
