### ISSUE TITLE
Random Agents Appearing

### ISSUE THREAD

**Issue by factulas** [wh1te909/tacticalrmm#572]
**Server Info (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04, Debian 10]Ubuntu 20.04.2 LTS
 - Browser: [e.g. chrome, safari] Chrome  91.0.4472.101 64-bit
 - RMM Version (as shown in top left of web UI): 0.6.14

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):1.5.7
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2] Multiple

**Describe the bug**
Having ghost connections to agents that I never added.

**To Reproduce**
Agents randomly appear
**Expected behavior**

**Screenshots**
![picture](https://user-images.githubusercontent.com/9405782/121733160-23059780-cac1-11eb-8fbc-702c3711b2db.png)

**Additional context**

**Comment by dinger1986** [comment]
This is a fairly common issue which is attributed to AV doing sandboxed installs.

Plenty about it in the discord channels and other opened and now closed issues.

**Comment by factulas** [comment]
Good to know, thanks. I looked an couldn't get answers. Makes perfect sense.

**Comment by silversword411** [comment]
I have built a test TRMM to put some honeypot agent installers around your network. Contact me if you'd like to have some so we can monitor
