### ISSUE TITLE
Feature: application logs match server timezone

### ISSUE THREAD

**Issue by bbrendon** [wh1te909/tacticalrmm#573]
Right now some of the logs are in UTC. Is it possible logs could match the server timezone?

/var/log/celery
/rmm/api/tacticalrmm/tacticalrmm/private/log/debug.log

**Comment by sadnub** [comment]
I am actually in the process of moving the debug log to the database and this will be implemented.

**Comment by bbrendon** [comment]
I can’t say I’m a big fan of logs in a database because it prevents simple automated monitoring of them.

**Comment by sadnub** [comment]
There are some pretty major improvements over the debug.log file.

-There was no way to distinguish logs for agents with the same name
-log entries can now be categorized. Windows Updates, agent issues, etc.
-Logs can be viewed directly on the agent for easy debug log access via new Debug tab
-Configurable log retention
-Simplifies backup/restore

**Comment by wh1te909** [comment]
the `debug.log` was never meant to be permanent or used in production i only added it until we got logging into the database

celery logs will however remain files. celery logging is optional i just enabled them for debugging. I am not sure if there is a setting just to change the timezone for celery logging, will have to check celery docs

**Comment by wh1te909** [comment]
released in 0.8.0
