### ISSUE TITLE
Optimize API endpoints

### ISSUE THREAD

**Issue by unplugged216** [wh1te909/tacticalrmm#578]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem per se. For documentation and logic it is. 

**Describe the solution you'd like**
Reorganize the API endpoints to pertain to the intended use cases. An example is the Clients URLs definition. 
[Clients URLs](https://github.com/wh1te909/tacticalrmm/blob/b31c13fcae938a7f2f00deb93c2264b57d4e48de/api/tacticalrmm/clients/urls.py)

Instead I propose something like the following:

```python
urlpatterns = [
    # GET / POST: list clients or create client and first site
    path("", views.GetAddClients.as_view()),
    # GET / PUT: Returns client object or updates client object
    path("<int:pk>", views.GetUpdateClient.as_view()),
    # DELETE: Delete client and move agents
    path("<int:pk>/<int:sitepk>/", views.DeleteClient.as_view()),
    # GET: returns the UI tree data
    path("tree/", views.GetClientTree.as_view()),
]
```

**Additional context**
This will require some modifications in the API structure such maybe a new view for sites. I am working on documentation and would like to work the API to a RESTFul standard that is consistent. 

Also making endpoint endings consistent as well such as `/` or slash. 
**Example:** `https://api.example.com/agents/listagents` **VS** `https://api.example.com/agents/listagents/` 

Thoughts? Im not opposed to being told to get bent lol.

**Comment by wh1te909** [comment]
good request yea i like it, we def can make endpoints more restful, atm not really following proper rest standards lol.
as for the consistent endpoint endings that shouldn't be an issue cuz django by default forces all urls to end with a `/` and if not it will throw errors

**Comment by unplugged216** [comment]
Excellent. I am working on a bit of this now. Leaving old infrastructure there till a phase out can happen. 

I thought similar. But, testing the API is proving that is a selective application of the rules lol.

**Comment by sadnub** [comment]
I think there is a switch in the Django settings that will remove the requirement trailing slash.

Also, I have a local branch that I am moving any api calls to its own JS module and importing that into components or composition functions. That way the API urls are all in one spot.

I am building it on top of this branch though. https://github.com/wh1te909/tacticalrmm/pull/516 

So hopefully it doesn't mess with anything you are doing or documenting. I am rebasing the changes from develop ever so often so it will merge cleanly.

**Comment by silversword411** [comment]
@sadnub you finished that branch and released, is this issue completed?

**Comment by silversword411** [comment]
Was this part of #43 and is now resolved? Closing, reopen if incorrect.
