### ISSUE TITLE
Feature request: built-in check for CPU temperature

### ISSUE THREAD

**Issue by DjMagicFingers** [wh1te909/tacticalrmm#579]
It would be very helpful when solving issues, if we had a way to check current CPU temperature and keep a log for it over time like we have the wonderful info about CPU load and the great graph we can produce to understand if there is some kind of problem with the hardware.

A way to set intervals would be also great.

This is sent as a feature request so it would be easy to create, for example, an alert when the CPU goes over a certain threshold.

A way to determine the output as Celsius or Fahrenheit is needed.

[Here is a script I found online ](https://www.codegrepper.com/code-examples/shell/how+to+monitor+cpu+core+temperature+using+powershell)- I do not have the ability to do anything with this

**Comment by johnnyq** [comment]
Great request, maybe even extend that to GPU temp as well would be extremely helpful.

**Comment by dinger1986** [comment]
We can cover this off with a community script but would need to agree on thresholds, also that script only monitors but monitoring without alerts is pointless.

Worth discussing on the scripts channel on discord.

**Comment by dinger1986** [comment]
Probably based off of something like this...

https://github.com/MikeLierman/TempProber

But needs updated

**Comment by dinger1986** [comment]
I have mentioned in scripts channel feel free to comment there
