### ISSUE TITLE
Feature Request: patch managment in automation manager

### ISSUE THREAD

**Issue by notadevcollins** [wh1te909/tacticalrmm#58]
It would be great to set a patch policy across clients or sites, I was thinking adding this in to policy manager makes the most sense

PS I hope Im not to anoying with feature requests because I am sure I will be able to come up with a bunch more
also Im trying to learn django and python just so I can help with this project, this project is awesome!

**Comment by wh1te909** [comment]
yes this will be added eventually, see https://github.com/wh1te909/tacticalrmm/issues/49

and no not at all! there's no such thing as too many feature requests :) 
and that's awesome, feel free to message me on discord if you need any help with python/django!

**Comment by notadevcollins** [comment]
same as #49 closing, thank you for all the hard work!
