### ISSUE TITLE
agent.logged_in_user variable not working

### ISSUE THREAD

**Issue by eric-robbins** [wh1te909/tacticalrmm#580]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: chrome, FireFox
 - RMM Version (as shown in top left of web UI): v0.6.15

**Installation Method:**
  - [x] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v1.5.8 
- Agent OS:   Win 10 

**Describe the bug**
The agent.logged_in_user variable doesn't work.

**To Reproduce**
1. Create a script with argument -logged_in_user {{agent.logged_in_user}}.
2. Add content of:
Param (
     [string]$logged_in_user
)
Write-Host "The logged in user is: $logged_in_user"
3. Output is:
The logged in user is: {agent.logged_in_user}

**Expected behavior**
Should get output of:
The logged in user is: someUserName

**Screenshot**
![image](https://user-images.githubusercontent.com/39501983/122252613-1c946880-ce91-11eb-8162-dbcc7010e986.png)

**Additional context**
I have tested with all other agent variables as listed at https://wh1te909.github.io/tacticalrmm/script_variables.html. All other variables work except {{agent.logged_in_user}}. I have made sure to go back and use a copy past method with the agent variable to assure that there is no typo etc.

**Comment by wh1te909** [comment]
Hi, thanks this is actually a typo in the docs. should be `{{agent.logged_in_username}}` just pushed an update to the docs
not all the variables are documented, you can always check the `models.py` file in each django app to get the full list of available vars (assuming they're not like json fields) https://github.com/wh1te909/tacticalrmm/blob/99f2772bb39ecb87c52046668cfe7bc16d079e80/api/tacticalrmm/agents/models.py#L46

**Comment by silversword411** [comment]
@wh1te909 Adding my todo list to update all the items in models.py to the docs. Should I skip the #Deprecated ones?

**Comment by wh1te909** [comment]
@silversword411 awesome ty, yea skip the deprecated ones and also skip any of the `models.JSONField` since those won't render properly as strings

**Comment by silversword411** [comment]
....also, if I re-arrange all those items into alphabetic order it's not going to break anything is it?

**Comment by wh1te909** [comment]
best to leave it as is, cuz changing stuff in the models will trigger a database migration which should only happen if we add or delete new db fields
