### ISSUE TITLE
Feature: View script run logs on an agent

### ISSUE THREAD

**Issue by davidrudduck** [wh1te909/tacticalrmm#582]
Whilst we can view the script output if we run it on a single agent and wait for the results, there's no way to view the output of a script run on an agent when it is run in bulk - and sometimes it doesn't work in bulk.

It would be good if there was a tab on the agent view that showed "previously run scripts" and the ability to view the output of that script run attempt.

**Comment by rfost52** [comment]
I like this idea.  I feel that including script jobs (like in Dameware Remote Everywhere) in the core set of agent logs will be a great tool to help folks fine tune their automations.

**Comment by silversword411** [comment]
I think this is coming, @sadnub posted a screenshot of 3 new upcoming tabs (I think once vue 2-3 gets finalized). #Staytuned

**Comment by wh1te909** [comment]
> I think this is coming, @sadnub posted a screenshot of 3 new upcoming tabs (I think once vue 2-3 gets finalized). #Staytuned

yes already being worked on

**Comment by wh1te909** [comment]
released in 0.8.0 (new History tab, see release notes)
