### ISSUE TITLE
Windows Update KB2267602 keeps appearing w/o being auto-approved by patch policy based on severity (Other)

### ISSUE THREAD

**Issue by rfost52** [wh1te909/tacticalrmm#586]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: chrome
 - RMM Version (as shown in top left of web UI): 0.6.15

**Installation Method:**
  - [ X ] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.5.8
- Agent OS: Win 10

**Describe the bug**
I couldn't find a bug request for this.  but lately, I've noticed with my automation policy that it's auto approving my "OTHER" policies with exception to Microsoft KB2267602 (Security Intelligence Update for Microsoft Defender Antivirus)  Quick check at Microsoft's website seems to show this KB is for definition updates.  I'm guessing that since they are releasing it daily pretty much, or more often, my TRMM instance is not catching that one KB patch.

**To Reproduce**

- Created entirely new automation policy and applied to a site of a few agents
- Set patch policy to auto approve all severity levels and to run daily at a fixed time
- Agents were reporting relevant patches being auto-approved (except for KB2267602)

**Expected behavior**
All updates, including KB2267602, should automatically give blue check for approved and the blue pending icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/85522106/122630696-c6dbde00-d093-11eb-85c4-aa0d80896816.png)

![image](https://user-images.githubusercontent.com/85522106/122630719-f5f24f80-d093-11eb-9780-05da7c6b447b.png)

**Additional context**
This KB is related to Windows Defender definition and, perhaps, signature updates.  Microsoft uses the same KB everytime they update the definitions.

**Comment by rfost52** [comment]
I've watched my agents over the last 24 hours and it seems some of them auto approved the KB, but others did not.  However, the Windows Defender signature version, in parenthesis, is continuing to update, so it seems to me my computers are applying the KB daily.  It may depending on the timing when the agent checks for patches maybe?

**Comment by wh1te909** [comment]
yes update approval happens every 8 hours or once a day i think so just give it some time and eventually will be approved
