### ISSUE TITLE
Task with email alert set missing Hostname in Email subject and body

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#589]
**Server Info (please complete the following information):**
 - RMM Version (0.6.15):

**Describe the bug**
Have a Tasks, with Email alert set (applied from automation policy, but don't think this matters). 

In the email that is sent the subject and body is missing the hostname eg
Client, Site, Name of Task Check failed
Should be:
Client, Site, Hostname, Name of Task Check failed

SMS Alert also missing Hostname

**Comment by wh1te909** [comment]
ty, just fixed will be in next release
