### ISSUE TITLE
method of executing

### ISSUE THREAD

**Issue by therealelyayo** [wh1te909/tacticalrmm#59]
can the agent be run on my pc without a popup or something

**Comment by wh1te909** [comment]
what do you mean by popup
installation is done through the command line, and the agent runs as a windows service so there are no popups

**Comment by wh1te909** [comment]
this has been implemented in 8177234b322157ee34bb5dfac0eba9f740cf6aa3 you can now generate a single exe that will handle the entire installlation. please update using the latest update.sh script
