### ISSUE TITLE
Bug: Bulk script not passing values

### ISSUE THREAD

**Issue by davidrudduck** [wh1te909/tacticalrmm#591]
When running BULK SCRIPT against agents, client side keys are not passed.

Instead of passing (for example) {{client.huntresskey}} to the powershell script, we're ending up with {client.huntresskey}

**Comment by silversword411** [comment]
Are you running the latest version? This was a bug that was fixed.

**Comment by davidrudduck** [comment]
Tactical RMM v0.6.15 🤷‍♂️

**Comment by wh1te909** [comment]
I don't think I applied the fix to the bulk script. Will fix
