### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by Kptainflintt** [wh1te909/tacticalrmm#594]
**Server Info (please complete the following information):**
 - OS: Debian 10
 - Browser: Firefox& Chrome
 - RMM Version (as shown in top left of web UI): No version number shown on top left

**Installation Method:**
  - [X ] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): Not yet used
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2]

**Describe the bug**
After successful installation, all subdomain is responding but when I connect to rmm one, I've got a "Network error" Message on the top of the window.
All of computer's domain can reach this page (and mesh one), host file on the debian server have been modified witch 127.0.0.1 for each subdomain (GET on URL is OK from command line).

Firewall checked, nothing is blocked (I suspected a problem with 2FA).

**To Reproduce**
1. Go to 'rmm.whatever.com'
2. Enter credentials
3. Clic on login
4. "Network Error"

Note : unfortunately, I didn't follow the script so I don't know if errors occurs.

Anyway to troubleshoot?

**Comment by silversword411** [comment]
If this is a new/clean install, did you save the install log? Were there errors?

Install mt system again, and retry install. Don't modify hosts file

**Comment by wh1te909** [comment]
yes please wipe / reinstall and DM me on discord the entire output of the install script

**Comment by wh1te909** [comment]
also paste screenshot of your browser's console tab from dev tools that will show the real "network error"

**Comment by Kptainflintt** [comment]
Hi,

I'm just an idiot... Problem found with Firebug. when LOGIN is cliqued, the api URL is not good (.n instead of .net).

In wich config files I can change this (if I can change this of course).

Thank you and sorry

**Comment by wh1te909** [comment]
there are too many places to change. will be faster to just wipe and reinstall
