### ISSUE TITLE
remove enhancement "Have search clear when switching to another client/site"

### ISSUE THREAD

**Issue by bbrendon** [wh1te909/tacticalrmm#597]
I find the removal of this feature very annoying. When I'm trying to do a task across many clients I'm constantly having to reapply my search. I preferred it the old way :)

Please revert https://github.com/wh1te909/tacticalrmm/commit/369fac9e38ea9efe1db0af990bf680a899203c03

**Comment by Brodur** [comment]
I'd suggest instead having this a toggle-able option somewhere, that way we can please everyone.

**Comment by bbrendon** [comment]
@Brodur  no. we only need to please me :)

**Comment by wh1te909** [comment]
i've made this optional by adding it to user preferences:

![chrome_cqohWMlGCd](https://user-images.githubusercontent.com/7434746/123584343-0db58c00-d796-11eb-9ff1-b2ac4a0111d8.png)
