### ISSUE TITLE
After creating a task in Automation Manager, it is not assigned to agents.

### ISSUE THREAD

**Issue by cm-slu** [wh1te909/tacticalrmm#604]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: chrome
 - RMM Version: 0.7.1 

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.5.9

**Describe the bug**
When creating a task in automation manager which is executed following a script error, it is not assigned to the agents.
Whereas if I create the same task with a manual trigger, it is indeed assigned to the agents.

**To Reproduce**
For reproduce look this video
https://drive.google.com/file/d/1KIgDwCZ24Ah0I3_YBRh-UgW3UzNY46J_/view?usp=sharing

below is the download link of the script I want to run
https://drive.google.com/file/d/1Y2vHLkT5j4nIICw_4lo3gQgZGFCa9Szm/view?usp=sharing
**Additional context**
I want to run a task when the "Disk space check" is in error

**Comment by cm-slu** [comment]
where is the policy applied?
Client (no exclusion)

my policy is recent. It was created a few days ago
I just created a new test font and it works.

Do I still have to delete my policy?
It's a lot of work.

**Comment by wh1te909** [comment]
no need to delete. ok thanks let me try to reproduce

**Comment by cm-slu** [comment]
ok good news lol.

if you need more trace of debug or other tell me no problem.

I think the reproduction on your side will be complicated as when I create a new policy it works. It has to be in my context.

**Comment by silversword411** [comment]
I think there was a fix about policies not applying. If still a problem please provide further info and we'll reopen.
