### ISSUE TITLE
Feature Request: Bandwidth Usage, Graphing and Alert Triggering

### ISSUE THREAD

**Issue by johnnyq** [wh1te909/tacticalrmm#607]
**Is your feature request related to a problem? Please describe.**
It would be great to see current bandwidth usage up and down as well as historic graphing of bandwidth being used.
I would also like to see an alert trigger for example if bandwidth stays at 5Mbit in either direction up or down for X mins straight then alert.

**Describe alternatives you've considered**
haven't thought about any other alternatives

**Comment by silversword411** [comment]
May be able to get some of this functionality with getting this into the Community script library: https://www.cyberdrain.com/monitoring-with-powershell-monitoring-network-traffic/

**Comment by silversword411** [comment]
I have a feeling this is a wontfix because it can be done via powershell and script library. @wh1te909 can reopen if incorrect.
