### ISSUE TITLE
Feature Request: User logged in log and External IP Log

### ISSUE THREAD

**Issue by johnnyq** [wh1te909/tacticalrmm#608]
**Is your feature request related to a problem? Please describe.**
Sometimes I get asked by some of our managed clients who was logged into the computer today and if a laptop was taken home.

**Describe the solution you'd like**
These two can be resolved with a historic log when a user thats logged in is different then the current user then log the date and time and the user in a log that can be viewed via the rmm.

Another solution I would like would be to log the external IP address if they are different then log it with the IP and the date time, if it changes again then log it again.

**Describe alternatives you've considered**
You check the event view manually if security auditing is turned on
You could login to the RMM and check the current IP

**Additional context**

**Comment by silversword411** [comment]
Let's hope the upcoming new tabs (audit etc) will help with this. If it doesn't, then maybe those can be enhanced but @sadnub magic 😉

**Comment by sadnub** [comment]
I have this feature completed and I just need to submit my changes. Stay tuned!

**Comment by wh1te909** [comment]
released in 0.8.0
