### ISSUE TITLE
Sort error only by server

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#609]
Would be nice to be able to just filter error device by type (server or workstation).
We have different consultants working towards server and workstations; would be great to be able to filter this view so they can take action on customers with yello/red in their server/workstation filter.

**Comment by silversword411** [comment]
Can you expand a little more, will this be fixed with #553 and search/based clients/sites?

**Comment by frankemann** [comment]
Hmm yeah, seems like that could be fixed with.
As long as we can sort error state by difference states (in my case just servers) that is just perfect.

**Comment by frankemann** [comment]
not sure if this really worked out for us. 
Would be great to actually have the client/devices status (red/organge) just based on the server in that site/client and ignore the workstations error eventually.
