### ISSUE TITLE
Permissions issue trying to use the latest update.sh

### ISSUE THREAD

**Issue by rtwright68** [wh1te909/tacticalrmm#61]
Having a issue with the latest update.sh

did the following steps:
su - tactical
wget https://raw.githubusercontent.com/wh1te909/tacticalrmm/develop/update.sh
chmod +x update.sh
./update.sh

I saw a huge amount of permission errors and it did not update properly.  I should run as tactical (user I created during install), correct?

that's how I did the previous update and it did work correctly.

**Comment by wh1te909** [comment]
ive added the commands to fix permissions to the update.sh script so no matter what now perms will be fixed on every update, just never run it as root
