### ISSUE TITLE
agent_id empty in table alerts_alert

### ISSUE THREAD

**Issue by Nini81** [wh1te909/tacticalrmm#611]
Using Tactical RMM v0.7.2
When alert is poping, the field "agent_id" is empty in the "alerts_alert" table, So we're loosing the relation between the alert and the host. There's the hostname in the message, but if 2 clients use the same hostname ...

**Comment by silversword411** [comment]
Can you provide a screenshot with the problem?

**Comment by Nini81** [comment]
[https://imgur.com/a/PWh2h0p](url)

here is it

**Comment by wh1te909** [comment]
what exactly is the bug i don't understand

**Comment by Nini81** [comment]
i thought taht the "agent_id" should contain the id of the agent that poped the alert, no ?

**Comment by silversword411** [comment]
That doesn't look like a standard TRMM screen. Are you using a 3rd party tool like grafana to look at the postgres database?

**Comment by sadnub** [comment]
If the alert is triggered by a check or task, you need to get the agent through those relationships.
