### ISSUE TITLE
Adding a field in the hard disk check

### ISSUE THREAD

**Issue by Scaff31** [wh1te909/tacticalrmm#612]
Hello, 

And thank you for the work done !!

Is it possible to have the "Alert severity" field in the hard disk check form ?

![image](https://user-images.githubusercontent.com/16442430/124133619-4ac59b00-da82-11eb-914b-1e3ec680cf2c.png)

Like this

![image](https://user-images.githubusercontent.com/16442430/124133918-98420800-da82-11eb-84f0-5f7636d51387.png)

**Comment by bbrendon** [comment]
What’s the use case?

**Comment by Scaff31** [comment]
> 
> 
> What’s the use case?

To answer the SLA and I have some virtual disks used for raspberry on the network, I don't need to receive an alert for them, just an information is enough

**Comment by sadnub** [comment]
You can put in a 0 for the Error threshold and just set the warning threshold

**Comment by silversword411** [comment]
I think this was resolved? Closing, can reopen if incorrect.
