### ISSUE TITLE
Copying Automation Policy creates multiple tasks.

### ISSUE THREAD

**Issue by technoicon** [wh1te909/tacticalrmm#617]
**Server Info (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Browser: chrome 91.0.4472.77
 - RMM Version (as shown in top left of web UI): 0.7.0

**Installation Method:**
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):  v1.5.9
- Agent OS: Various Windows

**Describe the bug**
When copying an automation policy, the tasks on the new created copy have lots of duplicate tasks.

!!!!Only happens on one of my policies!!!!

**To Reproduce**
![automation copy bug](https://user-images.githubusercontent.com/17463110/124369099-8d1df080-dcab-11eb-99d0-538545b956b5.png)

1. Open Settings, Automation Policy.
2. Select a previous policy.
3. Right click, select Copy.
4. Check Tasks and there is 10-20 tasks of the same Name.

**Expected behavior**
An exact copy of the pervious policy.

**Comment by silversword411** [comment]
You're running latest? There was a previous issue like this that was patched.

**Comment by silversword411** [comment]
No, you're running 0.7.0, update to 0.7.2 and retest

**Comment by silversword411** [comment]
Also, there was a known issue where automation profile got corrupted, you need to delete your old problem automation profile and manually recreate. If it keeps happens on newly created profile let us know
