### ISSUE TITLE
Question about taking control

### ISSUE THREAD

**Issue by krystophe** [wh1te909/tacticalrmm#619]
Hi,

Is it possible to take control of a remote workstation with a validation of user first ?
For exemple I want to take control of a remote pc and the user must accept first to give me the authorization to take control of his pc.

Thanks for response

**Comment by dinger1986** [comment]
yes, this is controlled within meshcentral.

Login to the mesh portal and from there change the setting sunder the tactical device group.

as this is a mesh question rather than tactical, I am going to close this now but if you require more assistance with this we can help on the discord chat.
