### ISSUE TITLE
Bug: Checks Disappear After Adding Task

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#62]
I have a policy setup called Default Checks in Automation Manager 

which has the basic CPU, Disk, Ping checks set up, when I added and event log check then a task linked to the failure of the check all the checks disappeared as did the task.

![Automation Manager](https://user-images.githubusercontent.com/15325110/90885172-756fad80-e3f4-11ea-802b-c3944d542c53.png)

The new check has been applied to one site and is returning data however it has not applied to all sites where the policy is configured, but will show if I re-add the policy to the client/site.

![Checks Applied By Policy](https://user-images.githubusercontent.com/15325110/90885176-77d20780-e3f4-11ea-8821-4be2cef807a2.png)

I have checked Django administration but can't see anywhere that contains the info for the checks/tasks.

The debug log also only shows the new check being added to some machines but no errors as to why the checks are no longer visible in the interface.

**Comment by bradhawkins85** [comment]
It happened again.
I tried the same on another policy because why not and it did the exact same thing.

**Comment by bradhawkins85** [comment]
It looks like the issue is related to a policy being applied somewhere.
I can create a new policy with checks and tasks, then close out and go back in and everything is still there.
If I assign that new policy to a site everything disappears from the automation manager for that policy.
It also only seems to happen when a task is linked to a check in the policy.

**Comment by wh1te909** [comment]
thank you @bradhawkins85 we have found the source of the bug and sadnub is working on a fix

**Comment by sadnub** [comment]
@bradhawkins85 This should be fixed now. Let me know if you have any issues.
