### ISSUE TITLE
api domain certificate x509 error!

### ISSUE THREAD

**Issue by magicshow1** [wh1te909/tacticalrmm#624]
**Server Info (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Browser: [chrome]
 - RMM Version (as shown in top left of web UI):

**Installation Method:**
  - [ x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2]

**Describe the bug**

![Capture](https://user-images.githubusercontent.com/76628802/124721424-f70de400-debd-11eb-9edb-a351c6d17122.JPG)

**Comment by magicshow1** [comment]
/rmm/api/tacticalrmm/tacticalrmm/local_settings.py

CERT_FILE = "/path/to/your/fullchain.pem"
KEY_FILE = "/path/to/your/privkey.pem"

It still fails after configuration and restart...

**Comment by wh1te909** [comment]
where did you purchase the cert from and is it wildcard?

**Comment by wh1te909** [comment]
paste nginx configs also

**Comment by magicshow1** [comment]
how can I solve this problem....

**Comment by silversword411** [comment]
Your screenshot shows that the DNS names aren't matching (1st doesn't match 2nd), am I missing something?

If the dns names actually match, is the cert chain unbroken when you view it?

**Comment by wh1te909** [comment]
> nats wildcard, all are default

nats doesn't sell SSL certs lol. if you are using self signed cert then that definitely is not supported and will fail.

and if you are using a purchased ssl cert (not self signed) you'll need to update the nginx configs as well to point to the certs. the default nginx config generated by the install script uses the letsencrypt path. as @silversword411 said, read the error message it should give you a hint. 

anyway at this time we don't really support using custom certs. you're welcome to do so if you know what you're doing but there is no official support until we get docs up for it so i'm closing this
