### ISSUE TITLE
No uninstallation of rmm agent on deletion of computer

### ISSUE THREAD

**Issue by guillaumebottollier** [wh1te909/tacticalrmm#625]
**Server Info (please complete the following information):**
 - OS: [Debian 10]
 - Browser: [chrome]
 - RMM Version (as shown in top left of web UI): 0.7.2

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version : 1.5.9
- Agent OS: Win10, Win server 2019

**Describe the bug**
When deleting an computer/server from the console, agent is not uninstalled form the target computer/server

**To Reproduce**
Delete a computer form the console, confirm with the copy past of the name.
Even if machine is online, agent is not uninstalled

**Expected behavior**
Agent should be uninstalled form deleted computers

**Screenshots**

**Additional context**

**Comment by wh1te909** [comment]
run this from elevated cmd on the pc

`C:\Program Files\TacticalAgent\unins000.exe /VERYSILENT /SUPPRESSMSGBOXES /FORCECLOSEAPPLICATIONS`

if it uninstalls then probably AV is blocking the uninstaller from running. add `C:\Program Files\TacticalAgent\*` to your AV exclusions and it will work

**Comment by silversword411** [comment]
No answer, closing
