### ISSUE TITLE
Popup on remote control - RGPD (GDPR).

### ISSUE THREAD

**Issue by Nyphew** [wh1te909/tacticalrmm#629]
Hi there,

**Is your feature request related to a problem? Please describe.**
Not a technical problem, but with law on RGPD (GDPR) in europe this could be a great improvement.

**Describe the solution you'd like**
When taking control on remote device, the default action is to connect without notifying. Of course it's not a problem when we connect to a server, but when we want to go on a workstation we really need to notify the user. Would be nice to have an option to choose/set the default behaviour to "notify and ask permission" and use right-click to bypass.

**Describe alternatives you've considered**
Make a default action which is different for servers and workstations. If we are in the server tab, no need to notify. If we are in the workstation tab, we need to notify.

**Additional context**
Nothing to add.

Thanks a lot for your work.
Nyphew.

**Comment by dinger1986** [comment]
This is a mesh request not for tactical. You can search for meshcentral user notifications on google but essentially if you log into mesh central you can enable notifications in the device group.

**Comment by Nyphew** [comment]
> meshcentral user notifications

Hi dinger1986,

Thanks for your reply, I could create a dedicated group to workstations and change the default behaviour as requested in my firse post. Is there a way to manage those meshgroups from tacticalrmm ? Maybe this can be a feature improvment ?

Have a good day.

**Comment by dinger1986** [comment]
You can change the default behaviour for the tacticalrmm group.

You can't move anything as it won't work in tactical.

Mesh and tactical are 2 separate systems I would doubt this will be implemented.

**Comment by Nyphew** [comment]
Well it's working as intended whereas I have renamed the default "tacticalrmm" group to "servers" and create a new "workstations" group (and moved computers in). Both with different default behavior on "take control" command. I even rebooted the server.

![MESH1](https://user-images.githubusercontent.com/83342905/125168052-d2f32100-e1a3-11eb-841a-4d3b5965b5d0.PNG)
![MESH2](https://user-images.githubusercontent.com/83342905/125168053-d4244e00-e1a3-11eb-8a5e-c6753cb15f77.PNG)

**Comment by dinger1986** [comment]
Ok.

Fair enough, have you tried adding new machines?

**Comment by Nyphew** [comment]
Yes, I even tried to move from one group to another and the default behaviour works as expected.
Really thanks for your support because I would have had to stop using this amazing piece of software if I could not achieve this.

++

**Comment by dinger1986** [comment]
Perfect!

No problems at all!
