### ISSUE TITLE
BUG: Uploading and editing scripts with umlauts not possible

### ISSUE THREAD

**Issue by ghosty212** [wh1te909/tacticalrmm#634]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: chrome
 - RMM Version (as shown in top left of web UI): 0.7.2

**Installation Method:**
  - [X ] Standard

**Describe the bug**
Scripts that contain special characters like umlauts "äöüß" cannot be edited/saved
Uploading them works without error, but the characters are removed from the scripts.
When trying to edit a script and adding those characters, the script can't be saved.

**To Reproduce**

1. Create Umlauts.ps1 `write-output "äöüß"`
2. Upload Umlauts.ps1
3. View Code of Umlauts.ps1

And

1. Go to script manager
2. Click new script
3. Type code `write-output "äöüß"`
4. Save new script
5. View code of new script

And

1. Go to script manager
2. Press Edit Code of previously created/uploaded Umlauts.ps1
3. Add `write-output "äöüß"`
4. Try to save

**Expected behavior**
1. The script should be uploaded containing the code `write-output "äöüß"`
2. The script should be created and have `write-output "äöüß"` as code
3. The script should be saved and have `write-output "äöüß"` as code

**Additional context**
In previous versions it was possible to at least upload or create a new script containing umlauts, without them being removed from the script

**Comment by silversword411** [comment]
Please retest, there has been lots of changes to scripts

**Comment by sadnub** [comment]
I just make some modifications to how the scripts are stored in the database. This should help with the special characters. Please test in the next release
