### ISSUE TITLE
Certain Agents unable to contact MeshCentral

### ISSUE THREAD

**Issue by FrinkMan** [wh1te909/tacticalrmm#639]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Microsoft Edge
 - RMM Version (as shown in top left of web UI): v0.7.2

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v1.5.9
- Agent OS: Windows 10 Enterprise LTSC 2019, 64 bit v1809 (build 17763.2029)

**Describe the bug**
Installed the agent, and it populated in TacticalRMM fine, although nothing appears in MeshCentral. MeshAgent is installed but unable to contact the server. Stopping the Mesh Agent service and running it manually from the .exe in Program Files shows it's sticking at connecting to the server

**Expected behavior**
Start MeshAgent, receive connecting to, connected, etc. Can confirm that most other computers I've installed on work fine, so far only two have had this issue.

**Screenshots**
No screenshots really necessary imo, the agent isn't registered in MeshCentral, and command line just shows "Connecting to: wss://mesh.myserver.com:443/agent.ashx

**Comment by wh1te909** [comment]
Hi mesh is a separate product please check https://github.com/Ylianst/MeshCentral for docs and see if can run the mesh agent in debug mode to see where it's getting stuck

your title says certain agents cant connect, does that mean some are working? if so maybe on those machines websocket traffic being blocked?

**Comment by FrinkMan** [comment]
I'm assuming it's something with websocket traffic, but I haven't traced down anything in event logs yet. Will do some digging and let you know if I figure anything out

**Comment by FrinkMan** [comment]
Not sure if you want me to start a new issue for this or not, but I'm also trying to deploy to some agents and I'm getting this error when I run the script using ConnectWise:

```
Waiting for network
C:\WINDOWS\TEMP\ScreenConnect\21.8.3663.7830\ea634c0f-e424-4e28-8765-2c9285d3a4e7run.ps1 : The remote server returned 
an error: (403) Forbidden. 
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,ea634c0f-e424-4e28-8765-2c9285d3a4e7ru 
   n.ps1
 
Remove-Item : Cannot find path 'C:\WINDOWS\TEMP\winagent-v1.5.9.exe' because it does not exist.
At C:\WINDOWS\TEMP\ScreenConnect\21.8.3663.7830\ea634c0f-e424-4e28-8765-2c9285d3a4e7run.ps1:76 char:13
+             Remove-Item -Path $OutPath\$output
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\WINDOWS\TEMP\winagent-v1.5.9.exe:String) [Remove-Item], ItemNotFound 
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```

**Comment by dinger1986** [comment]
I'd suggest getting on discord and hopefully others can help there

**Comment by FrinkMan** [comment]
Ok

**Comment by silversword411** [comment]
Sounds like AV issue

**Comment by FrinkMan** [comment]
I don't think it's antivirus either because I run SentinelOne, and it's installed on all the other machines in the corporation with SentinelOne just fine

**Comment by dinger1986** [comment]
Can you telnet from those agents to your mesh server? Use putty if you don't have telnet client installed.

Have you added exclusions to your antivirus? We have seen it for some customers where av is fine on some PCs and on others can't even install.

**Comment by silversword411** [comment]
You're using the screenconnect script from docs to deploy TRMM?

That is a deployment url?

The deployment url works from the browser on the machine? (Not an expired link?)

If it downloads fine in the browser, you're getting a forbidden error. 

Uninstall SentinelOne and retest. If it works with no av, then you have your answer.

**Comment by dinger1986** [comment]
I strongly suggest if you require more support then get it on discord where a number of users can help.

I am going to close this now.

**Comment by FrinkMan** [comment]
Was able to get this resolved, it turns out something specific to the proxy on those machines was performing SSL Inspection, and so the hashes for the certificates weren't matching serverside/clientside. Disabling that temporarily fixed it, and I'm working with the proxy provider now to get an exclusion added. Thank-you for your help!

**Comment by silversword411** [comment]
What proxy do you have client side?

**Comment by FrinkMan** [comment]
[Streamline3](https://streamline3.com/home)
