### ISSUE TITLE
Message Popup To User not displaying message

### ISSUE THREAD

**Issue by rebootit** [wh1te909/tacticalrmm#646]
- OS: Debian 10
 - Browser: Firefox
 - RMM Version: v0.7.2

**Installation Method:**
  - [*] Standard

**Agent Info (please complete the following information):**
- Agent version: Agent v1.5.9
- Agent OS: Windows 10 Home, 64 bit v21H1 (build 19043.1110)

**Describe the bug**
The script to message popup to user only display "message from it" and a drop down time menu but no message

**To Reproduce**
1. Go to run script
2. Click on Message Popup To User 
3. Add the message, type enter and run

**Expected behavior**
A pop up appears on the user desktop with my message showing

Thanks for this awesome tool !

**Comment by dinger1986** [comment]
this is a community script with such they are supported via the community on discord https://discord.gg/HtxwfbX6.

closing now
