### ISSUE TITLE
Code Signing?

### ISSUE THREAD

**Issue by fred5632** [wh1te909/tacticalrmm#648]
Hi,
Lately i have been having trouble getting the agent installed by users over the phone.
Basically their browser and windows smart screen give them a heap of security warnings which are hard to get past without me being able to see their screen.

I just saw the code signing bit in the doco.
Does this fix this issue? 
Thanks

**Comment by dinger1986** [comment]
Yea code signing greatly helps with a lot of these prompts.

I think it'll still show on smartscreen but otherwise should be fine.

Chrome seems to work best.

**Comment by fred5632** [comment]
thanks, i am interested and might end up setting up the donation
