### ISSUE TITLE
Feature Request: Service Checks, PASS if service does not exist

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#65]
Can you please add the option to have a service check Pass if the service does not exist.

This will allow the policy to apply to all machines and only alert/restart a service if it is installed on a machine and can then also kick in when if the service is installed in the future.

**Comment by wh1te909** [comment]
will do, have to release a new agent for this though cuz I hardcoded it to fail automatically if service doesn't exist.

**Comment by wh1te909** [comment]
Have support for this in the new agent just need to add it to the web interface. Will do tmrw.
