### ISSUE TITLE
Full access to Mesh Commander after logging out of Tactical RMM

### ISSUE THREAD

**Issue by epete99** [wh1te909/tacticalrmm#655]
**Server Info (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04, Debian 10] Ubuntu 20.04
 - Browser: [e.g. chrome, safari] Chrome and Firefox (no access to Safari to check)
 - RMM Version (as shown in top left of web UI): 

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2]

**Describe the bug**
I setup a new Tactical RMM installation to test.  I was able to log out of Tactical RMM and immediately log into Mesh with full access to all machines with no login credentials needed.

**To Reproduce**
1. Log out of Tactical RMM
2. In the same browser window, enter in the mesh URL
3. Mesh was immediately logged in with no credentials needed
4. Mesh allowed full access to all machines
5. This does not occur when you close out of the browser

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dinger1986** [comment]
This is due to having used the login token via take control and remote background.

Logging out of tactical doesn't log you out of mesh as it's 2 separate systems.

I don't believe that can be changed

**Comment by wh1te909** [comment]
yea this is working as intended. You can play with mesh settings if you want to change it. I'm not really concerned with mesh settings other than the minimum settings required to get integration working.
