### ISSUE TITLE
Default settings in scripts for "Fire and Forget" or "Email Results"

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#656]
**Is your feature request related to a problem? No

**Describe the solution you'd like**
Default settings in scripts for "Fire and Forget" or "Email Results"

**Describe alternatives you've considered**
None

**Additional context**
Would be good if scripts could default to the desired output method this would also allow for favourite scripts to "Email Results" instead of just "Fire and Forget"

**Comment by sadnub** [comment]
I reworked the favorite scripts menu to load the run script dialog with the script pre-populated with default timeout and args so that the output method can be selected.

Are you suggesting have a default output method per script?

**Comment by bradhawkins85** [comment]
Awesome about the dialogue but yes was also thinking default output method per script.
