### ISSUE TITLE
Alert template is not applied to new agent when the default automation policy is applied

### ISSUE THREAD

**Issue by NiceGuyIT** [wh1te909/tacticalrmm#658]
**Server Info (please complete the following information):**
 - OS: openSUSE Leap 15.3
 - Browser: Firefox 91.0
 - RMM Version (as shown in top left of web UI): v0.7.2

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v1.5.9
- Agent OS: Windows 10 Pro, 64 bit v21H1 (build 19043.1165)

**Describe the bug**
A new agent install on a new computer assigned to client/site with an automation policy assigned has the checks and tasks assigned but not the alerts. I have a default automation policy for workstations and servers, and the alert template is assigned to the base policy, not the client or site.

- Global Settings:
  - Default server policy: Base server
    - Alert template: Base alert
  - Default workstation policy: Base workstation
    - Alert template: Base alert
  - Default alert template: *Not set*
- Client settings:
  - Server automation policy: *Not set*
  - Workstation automation policy: *Not set*
  - Alert template: *Not set*
- Site settings:
  - Server automation policy: *Not set*
  - Workstation automation policy: *Not set*
  - Alert template: *Not set*

**To Reproduce**
1. Create a global automation policy.
2. Assign an alert template to the automation policy.
3. Clear any automation policies and alert templates from the client and site.
4. Add a new agent to the site.
5. The alerts are not "checked".

**Expected behavior**
When the default automation policy is applied, it's expected the alert template associated with the policy will also be applied.

**Screenshots**
The middle agent is new. The other two are existing.
![image](https://user-images.githubusercontent.com/7763429/129624439-2c35daa0-41d2-4189-9621-595b4953870d.png)

**Additional context**
Settings > Alert Manager > Uncheck "Enable Template" and then checking applies the alerts to the agent (and all others) as expected.

It's possibly this may happen on any automation policy, not just the default automation policy.

**Comment by sadnub** [comment]
Just pushed a fix for this. Will be in the next release

**Comment by wh1te909** [comment]
fixed in release 0.8.3
