### ISSUE TITLE
Bug: Save results to custom field returns blank line / extra line

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#669]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Edge
 - RMM Version (as shown in top left of web UI): v0.8.0

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v1.6.0
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2] Windows

**Describe the bug**
When running a task and selecting "Save results to custom field" or using a collector task the last line returned is blank. Using Save all output returns two lines of text when only one should be returned

**To Reproduce**
1. Run a simple powershell script, write-output "This is a test"
2. Save output to a custom text field, or select save all output
3. Returned value will either be blank or contain two lines of text with the second being blank

**Expected behavior**
Return the last non-empty line of text or omit the empty line when save all output is selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/15325110/131327893-a6e3ecde-0674-43e7-9df3-0c9a96b2d8ec.png)

Result:
![image](https://user-images.githubusercontent.com/15325110/131327948-9731c37f-0aad-446a-989d-f0b46c04c0b3.png)

**Comment by sadnub** [comment]
Thanks for reporting! I just pushed a fix for this. Will be in the next release

**Comment by wh1te909** [comment]
released in 0.8.1
