### ISSUE TITLE
Feature Request: Specify sender email per customer / site

### ISSUE THREAD

**Issue by dan578** [wh1te909/tacticalrmm#67]
Hi,

If possible could it be added so we can set a sender address on a customer basis? Looking to send them from the same domain just different emails so our ticketing system can differentiate per customer.

Thanks,
Daniel

**Comment by wh1te909** [comment]
sure, great request i've been wanting to implement this actually not the sender but different recipients for clients but while im doing that i'll also add option for different sender email

**Comment by wh1te909** [comment]
released in 0.4.8
