### ISSUE TITLE
BUG: Save results to Agent Notes only recording "NULL" in audit log details

### ISSUE THREAD

**Issue by manc74** [wh1te909/tacticalrmm#675]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04.3
 - Browser: Chrome
 - RMM Version (as shown in top left of web UI): 0.8.1

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):1.60
- Agent OS: Windows 10

**Describe the bug**
When executing a script, the new option to save results to agent notes only records "NULL" in the details panel.

**To Reproduce**
1. Right click on a workstation
2. Click on "run script"
3. Select a script that give an output such as "get serial number"
4. Select "Save results to Agent Notes"
5. Run script. Script executes and results show at bottom of the pane.
6. Click on audit tab
7. click on the line for the script ran
8. the detail pane shows "After  NULL"

**Expected behavior**
The same output on the run pane should be displayed in the audit details pane.

**Screenshots**
![f0eb40276566baa0917bc0cff1a3ab2c](https://user-images.githubusercontent.com/68019920/131463697-4e340220-1cd0-4289-92bd-ea8a977ca2bc.png)

**Additional context**

**Comment by wh1te909** [comment]
I don't think the script output is meant to be stored in the audit log, so this really isn't a bug more like a feature request. @sadnub will correct me if i'm wrong
it's already stored in the "History" tab which we added so that there is always a history of every script/cmd that was run and it's output
And if you are saving it to Notes then it will be stored there as well
adding it to audit log is overkill IMO

**Comment by subzdev** [comment]
I would agree it does seem to be overkill as well, but if everything is null in the modal window probably no need to even have the ability to click at all for audit log entries?

**Comment by wh1te909** [comment]
there are still use cases for clicking, like if you edit an agent you can see the before and after values to see what changed. maybe if it's null we can make it not clickable

**Comment by manc74** [comment]
Ah ok, I was looking in the wrong tab for the output, just assumed it would be in the audit tab - I can see the history output fine in the history tab now.
