### ISSUE TITLE
Show installed printers at the PC details tabs

### ISSUE THREAD

**Issue by DjMagicFingers** [wh1te909/tacticalrmm#676]
Knowing about the installed printers and getting as many details about them as possible, like is the printer online or offline, details about ink or toner levels would be a great time saver.

![image](https://user-images.githubusercontent.com/32017425/131511765-ef42588e-3f9d-4514-a198-df009d147b15.png)

Additional information about the printers that I would love to know about:
* Printer name
* Printer IP address
* Ink or toner levels
* Online / Offline state
* Drum life
* Quantity of printed items
* Is the printer shared
* Last printed item
* and more...

Other related features I think would be lovely to have:
* Set an alert for toner life, x% before it turns to 0
* Send periodic printing report to specific email address with on / off button to this feature
* Send an alert for drum life x% before it turns 0
* Send an alert for empty paper tray

**Comment by dinger1986** [comment]
That's a massive job to implement that!!

Too list printers would be easy enough but to get details on printers you would need SNMP or something similar.

**Comment by DjMagicFingers** [comment]
Using SNMP is a good way to get the details if we scan the network (I have already published my dream feature [here](https://github.com/wh1te909/tacticalrmm/issues/112)).
But this current feature request is about extracting as much info as possible from Windows - I guess things like IP address, TCP/UDP port and more such information about the installed printer would be available even without using SNMP.

**Comment by dinger1986** [comment]
Yeah theres a difference between a displaycard (part of the pc) and a printer which is really independent. A collector script would maybe be the answer though? Or written to notes?

**Comment by DjMagicFingers** [comment]
I am no expert, but it makes sense to me that if we can ask Windows about the installed drivers it has for any internal device (VGA, CPU, HD etc), it should be at least as easy to ask it for any other, already installed, external devices that are also connected to the PC - not to an internal slot, sure, but through the network - but still, Windows do know about them and does possess a lot of information that in my opinion would be stored with the installed driver - wouldn't it?

**Comment by dinger1986** [comment]
Yeah thats fine, Like I said "Get-Printer | Format-List Name,DriverName,PortName,Shared,DeviceType" would get all of that info and could be output to notes, please try it and let me know

**Comment by vantzs** [comment]
Just by the by, I added a custom field called printers, I have an onboarding automation policy that collects data for custom fields and I literally run @dinger1986 script and it outputs this:
![image](https://user-images.githubusercontent.com/7843257/135811276-075f81d1-2d0b-4228-b3a4-3303f57b2df2.png)

**Comment by dinger1986** [comment]
If we add that as a community script with a guide can be consider this closed?

**Comment by silversword411** [comment]
I'll be adding community script and closing this soon.

**Comment by dinger1986** [comment]
https://github.com/amidaware/community-scripts/pull/3#

This is implemented as a community script now
