### ISSUE TITLE
Easier way to renew cert ?

### ISSUE THREAD

**Issue by lapourgagner** [wh1te909/tacticalrmm#678]
I'm always frustrated when I have to renew my certificate, it's time-consuming.

I've undertood that it is not easy to automate it, ok.

At the end of the renewing process, I got the message `To obtain a new or tweaked version of this certificate in the future, simply run certbot again. To non-onteractively renew *all* of your certificates, run "certbot renew"`

This is my only certificate managed on this machine, will this work ?

**Comment by dinger1986** [comment]
its not possible to automate renewing a wildcard cert and it needs TXT records added. It has been done using dns and 3 separate certificates but that is not supported. 

If you require more assistance with this then please join the discord channel

**Comment by silversword411** [comment]
@dinger1986 Might be nice to add to the "Unsupported" docs a way to use purchased certs with TRMM. Do you know who may be doing this now?

**Comment by casaresjm** [comment]
It would be nice to be able to use existing wildcard certificates we do not need to renew every 3 months with a really complex setup.

**Comment by dinger1986** [comment]
its all on docs https://docs.tacticalrmm.com/functions/settings_override/#using-your-own-wildcard-ssl-cert and also how to use the http certbot
