### ISSUE TITLE
Can't kill process in Remote Background feature

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#679]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Edge
 - RMM Version (as shown in top left of web UI): 0.8.1

**Installation Method:**
  - [x ] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.6.0
- Agent OS: Windows 10 Pro, 64 bit v21H1 (build 19043.1165)

**Describe the bug**
When trying to kill a process Dev tools reports:
Failed to load resource: the server responded with a status of 400 (Bad Request)
api.comain.com/agents/100/17820/killproc/:1 Failed to load resource: the server responded with a status of 400 (Bad Request)

**To Reproduce**
Right-click on an agent - Remote Background - Processes - Right-click - End Process

**Expected behavior**
Process should kill when ending.

**Comment by wh1te909** [comment]
fixed will be in next release (will require agent update). bug is present only in latest version of golang 1.17 which was just recently released. reverting back to 1.16.7

**Comment by wh1te909** [comment]
fixed in 0.8.2 (requires agent 1.6.1)
