### ISSUE TITLE
Feature Request: Ability for users to reset their own passwords 

### ISSUE THREAD

**Issue by r3die** [wh1te909/tacticalrmm#686]
**Is your feature request related to a problem? Please describe.**
Users cannot change their own passwords without having the 'Manage User Accounts' permission which would give them the ability to change other user passwords as well.

**Describe the solution you'd like**
'Change Password' option upon signing in for users without the 'Manage User Accounts' permission/ 'Forgot Password' option prior to login.

**Comment by MrPangzhan** [comment]
I don't think this is a good suggestion. There is a certain risk. The password and token can be reset by the administrator. The user only needs to confirm with the administrator.

**Comment by r3die** [comment]
I don't think it is unreasonable for users to have the ability to change their own passwords. Every Enterprise platform has this functionality- in fact I find it less secure that I am creating passwords for technical users that they cannot change. To mitigate your concern, as long as they don't have the 'Manage User Accounts' permission the Global/Super admin can still go in and lock their account if they are terminated from the organization.

**Comment by wh1te909** [comment]
yea this is more like a bug than a feature request, users should already be able to reset their own passwords. will fix

**Comment by r3die** [comment]
@wh1te909 Sounds good- Are standard users intended to perform the action by right clicking on their user account within Settings>User Administration?

**Comment by wh1te909** [comment]
> @wh1te909 Sounds good- Are standard users intended to perform the action by right clicking on their user account within Settings>User Administration?

yep

**Comment by wh1te909** [comment]
changes pushed, will be in next release

**Comment by wh1te909** [comment]
added in release 0.8.3
