### ISSUE TITLE
Feature Request: Email Task Results was Veeam Backup check

### ISSUE THREAD

**Issue by dan578** [wh1te909/tacticalrmm#69]
Hi,

I'm looking to set the event checker to check for veeam status logs. However it saves them into Applications and Services Logs (Under Veeam Agent) rather than Windows logs is it possible to pull event ID's from this location?

I would be looking for event 190 which denotes a successful backup.

Thanks,
Daniel

**Comment by wh1te909** [comment]
yea not sure if it's possible with pywin32 cuz I know it uses the old eventviewer api which I don't think supports the applications and services logs but i'll look into it.

but this is where the script checks come in, you can just write your own bash or powershell script, upload it (Settings > Script Manager) and then choose it as a check. Maybe just copy and paste this and just modify it to your liking. Just make sure the script returns 0 if passing and any number but 0 for failing.

https://github.com/oneoffdallas/nagios_scripts/blob/master/check_veeam_eventlogs.ps1

**Comment by dan578** [comment]
@wh1te909 Great thanks for that managed to get it to work. Although its not working 100% as the check runs all the time could it be possible to set scheduled checks? e.g. run at 7am the check and email if it fails rather than running it every 2 mins? The problem now is if it fails but works on the retry the retry can take a while to put the success in so it triggers the probe even on 10.

**Comment by wh1te909** [comment]
you can change the interval for the check alerts, default is 120 seconds (right click agent > edit agent then set check interval) but it sounds like you should just add it as a Task instead of a Check. (Tab right next to Checks in the web interface).

Tasks can be set to run on a schedule or on check failure so maybe just add it as a task and have it run daily at 7am? I will need to enable email alerts for tasks though right now they are only available for checks.

**Comment by dan578** [comment]
I have checked the checks but that seems like changing that changes it for all checks rather than just the one? 

Task would be good if it could email on fail. Or maybe if you could add the scheduler in task scheduler as an option to the checks so you can choose between every x mins or a set time.

Thanks

**Comment by dinger1986** [comment]
testing tasks are emailed now and then will confirm and close

**Comment by dinger1986** [comment]
this shows up in dashboard but doesn't send email alerts for the task @wh1te909 @sadnub can this be added so email alerts are sent?

**Comment by sadnub** [comment]
@dinger1986 I'm still writing tests for the new alerting changes and pushed some fixes I found yesterday. I believe the email/text alerts were indeed broken for checks and tasks, but should be working now. Still writing tests though and hope to have those finished this week!
