### ISSUE TITLE
Feature Request: Add URL Action to Audit Log

### ISSUE THREAD

**Issue by r3die** [wh1te909/tacticalrmm#690]
**Is your feature request related to a problem? Please describe.**
Industry compliance requires logging of remote access connections to devices,  Tactical currently only reports 'Take Control' remote sessions in the audit log.

**Describe the solution you'd like**
I love the integration with Screen Connect, however, logging when a user performs the 'Run URL Action' to access a 3rd party platform would be ideal.

**Comment by silversword411** [comment]
Logging all actions are probably a good thing, so having that in the audit log is a good add.

For compliance, your 3rd party platform is the one that needs logging though if you URL Action is a Take Control-like thing for another technology.

**Comment by sadnub** [comment]
This is added. Will be in next release

**Comment by wh1te909** [comment]
added in release 0.8.3
