### ISSUE TITLE
[Feature Request] Mac/Linux Agent

### ISSUE THREAD

**Issue by athornfam2** [wh1te909/tacticalrmm#691]
**Is your feature request related to a problem? Please describe.**
Pretty simple and clear request... Just looking for a linux/Mac agent that can be deployed to computers/servers

**Describe the solution you'd like**
Build a .sh script or agent to run in the backgroup

**Additional context**
I have about 20-50 virtual servers that are linux I manage and my fathers growing business that uses macs for developement

**Comment by wh1te909** [comment]
duplicate of #461 the linux and mac agents are already in the works
