### ISSUE TITLE
Audit tab not refreshing when selecting different endpoint

### ISSUE THREAD

**Issue by RVL-Solutions** [wh1te909/tacticalrmm#694]
**Server Info:**
 - OS: Ubuntu 20.04
 - Browser: FireFox
 - RMM Version: 0.8.3

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version: v1.6.1
- Agent OS:  Windows 10 Enterprise, 64 bit v21H1 (build 19043.1110)

**Describe the bug**
When having the Audit tab open for Endpoint A, then select Endpoint B (or C, D, E, etc) the Audit tab continues to show information about Endpoint A.
All other tabs refresh and show info about newly selected endpoint.

**To Reproduce**
1. Go to endpoint overview.
2. Click on any endpoint
3. Open Audit tab
4. Select different endpoint
5. Audit tab shows info about initially selected endpoint.

**Expected behavior**
The Audit tab should refresh and show information about newly selected endpoint.

**Comment by wh1te909** [comment]
fixed in 0.8.4
