### ISSUE TITLE
Export  Computer Inventory in csv

### ISSUE THREAD

**Issue by buzzzo** [wh1te909/tacticalrmm#701]
Would be useful to export computer inventory in csv format.
In this way we could import it in inventory software .

Thx

**Comment by dinger1986** [comment]
This can be done via mesh at the moment and the request to add to tactical is duplicated from #523

**Comment by DjMagicFingers** [comment]
Mesh is keeping duplicates - this makes the inventory unreliable.
Also, mesh keeps all computers in one long list while we are MSPs dealing with multi tenants - the client and client site separation does not exist in mesh.

**Comment by dinger1986** [comment]
Mesh was a suggestion to help do something in the short term nothing else.
You can manually select machines, myself (as an MSP) have been able to use mesh when needed for inventory purposes, admittedly not as simple as as a one click option but it does work (changing the view to online only helps. 

You can also delve into django admin and do exports form here but you have to be extremely care! https://wh1te909.github.io/tacticalrmm/functions/django_admin/

This ticket is closed as again I will reference #523 which makes this a duplicate.
