### ISSUE TITLE
Expose script parameters in Run dialogs

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#702]
Can never remember what the command parameters are for scripts.

Option 1
Add a new item in the .json tip and show under script name selection. In this example I tried to emulate powershell notation (successfully=unsure)
Maybe call it "syntax"? Eg
```
,
  {
    "guid": "6c78eb04-57ae-43b0-98ed-cbd3ef9e2f80",
    "filename": "Win_Chocolatey_Manage_Apps_Bulk.ps1",
    "submittedBy": "https://github.com/silversword411",
    "name": "Chocolatey - Install, Uninstall and Upgrade Software",
    "description": "This script installs, uninstalls and updates software using Chocolatey with logic to slow tasks to minimize hitting community limits. Mode install/uninstall/upgrade Hosts x",
    "syntax": "[[Mode] {install,uninstall,upgrade}] [[Hosts] <string>]"
    "shell": "powershell",
    "category": "TRMM (Win):3rd Party Software>Chocolatey",
    "default_timeout": "600"
  }
```

Option 2
Display the description I can work on a standardized format for parameters. Support for new line (with /n?) a bonus.

![2021-09-10_074601 - trmm script descriptions1](https://user-images.githubusercontent.com/13395348/132850282-9bc50a3e-404b-4590-8367-4b461e918882.png)

![2021-09-10_074601 - trmm script descriptions2](https://user-images.githubusercontent.com/13395348/132850295-fc303977-b626-4c5b-9faa-70873d486e5c.png)

**Comment by bradhawkins85** [comment]
This will add script arguments to the community scripts json

    "args": [
      "-serviceName {{client.ScreenConnectService}}",
      "-url {{client.ScreenConnectInstaller}}",
      "-clientname {{client.name}}",
      "-sitename {{site.name}}",
      "-action install"
    ],

They will be pre-filled then, you can just remove and re-add to change the values.

**Comment by silversword411** [comment]
Would probably work just dandy :)

Gonna be a booger to write the defaults, lots of different scripts with different defaults. 

@bradhawkins85 Can you think of how to write up something similar to the powershell syntax that would be TRMM specific (looking for something for the docs). 

I look at this
```powershell
SYNTAX
    Get-Help [[-Name] <string>] [-Path <string>] [-Category {Alias | Cmdlet | Provider | General | FAQ | Glossary | 
    HelpFile | ScriptCommand | Function | Filter | ExternalScript | All | DefaultHelp | Workflow | DscResource | 
    Class | Configuration}] [-Component <string[]>] [-Functionality <string[]>] [-Role <string[]>] [-Full]  
    [<CommonParameters>]
```

and only when I get it color-coded in VSCode does it help to be more readable

<img width="683" alt="2021-09-14_225634 - powershell command syntax map" src="https://user-images.githubusercontent.com/13395348/133363100-73faa061-f25e-400a-8931-c6b0176b51a5.png">

**Comment by silversword411** [comment]
As an example what would the one for https://github.com/wh1te909/tacticalrmm/blob/develop/scripts/Win_Chocolatey_Manage_Apps_Bulk.ps1

Look like?

**Comment by silversword411** [comment]
So trying to follow powershell's example from here: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_command_syntax?view=powershell-7.1

```powershell
<command-name> -<Required Parameter Name> <Required Parameter Value>
[-<Optional Parameter Name> <Optional Parameter Value>]
[-<Optional Switch Parameters>]
[-<Optional Parameter Name>] <Required Parameter Value>
```

TRMM Standard format would look some:
```
"args": [
  "[-Hosts <string>]",   <- optional because surrounded by []
  "-$PackageName <string>",    <----required because no []
  "[-mode {(install) | update | uninstall}]"
],
```

eg for https://github.com/wh1te909/tacticalrmm/blob/develop/scripts/Win_User_Create.ps1
json would be

```
"args": [
  "-username <string>",
  "-password <string>",
  "[-description <string>]",
  "[-fullname <string>]",
  "[-group <string>]"
],
```

So TRMM docs description on a structured format should be:
```
"args": [
  "[-<Optional Parameter Name> <string>]",
  "-<Required Parameter Name> <string>",
  "[-<string> {(<default string if not specified>) | <string2> | <string3>}]"
],
```

Anyone see any problems?

**Comment by dinger1986** [comment]
looks right to me using that script as an example

**Comment by silversword411** [comment]
Considering this from the docs: `There is also an option on the agent context menu called **Run Favorited Script**. This will essentially Fire and Forget the script with default args and timeout.`

If we standardize the args field to this format, all community scripts with args that someone is going to want to run using that favorite menu will need to be duplicated and customized to their instance before being practical in that menu...if I'm thinking this thru correctly. 

Am I right? Any other thoughts? Any other considerations to think about?

**Comment by silversword411** [comment]
This commit is a test of the concept. Not sure how it'll go, can back it out if necessary. 

https://github.com/wh1te909/tacticalrmm/commit/8f9ad15108441bf373062f43c5810e10937f02a9

**Comment by sadnub** [comment]
This will break the existing arg functionality since that arg file is copied right to the script default args. Can we use another field like "help" or "syntax"?

**Comment by sadnub** [comment]
> Can never remember what the command parameters are for scripts.
> 
> Option 1 Add a new item in the .json tip and show under script name selection. In this example I tried to emulate powershell notation (successfully=unsure) Maybe call it "syntax"? Eg
> 
> ```
> ,
>   {
>     "guid": "6c78eb04-57ae-43b0-98ed-cbd3ef9e2f80",
>     "filename": "Win_Chocolatey_Manage_Apps_Bulk.ps1",
>     "submittedBy": "https://github.com/silversword411",
>     "name": "Chocolatey - Install, Uninstall and Upgrade Software",
>     "description": "This script installs, uninstalls and updates software using Chocolatey with logic to slow tasks to minimize hitting community limits. Mode install/uninstall/upgrade Hosts x",
>     "syntax": "[[Mode] {install,uninstall,upgrade}] [[Hosts] <string>]"
>     "shell": "powershell",
>     "category": "TRMM (Win):3rd Party Software>Chocolatey",
>     "default_timeout": "600"
>   }
> ```
> 
> Option 2 Display the description I can work on a standardized format for parameters. Support for new line (with /n?) a bonus.
> 
> ![2021-09-10_074601 - trmm script descriptions1](https://user-images.githubusercontent.com/13395348/132850282-9bc50a3e-404b-4590-8367-4b461e918882.png)
> 
> ![2021-09-10_074601 - trmm script descriptions2](https://user-images.githubusercontent.com/13395348/132850295-fc303977-b626-4c5b-9faa-70873d486e5c.png)

What you did here will work. Creating another key for the command usage. 

I just need to then created a db field for the usage data and display it in the UI

**Comment by sadnub** [comment]
Yeah should be able to work that out too
