### ISSUE TITLE
Permissions not available for Custom Field

### ISSUE THREAD

**Issue by dinger1986** [wh1te909/tacticalrmm#703]
when creating a new role you cant allow access to custom fields.

To reproduce go to Settings, Permission's Manager, new role and there isnt a tick box for custom fields.

Reported by SebCashmag on Discord and confirmed

**Comment by sadnub** [comment]
Are you suggesting that we add a field to the role to allow access to viewing/editing all custom fields on Agents, Clients, and Sites?

I am currently reworking permissions to restrict user access to specific clients and sites, so I could add a "can view/edit custom fields" for each of those.

**Comment by wh1te909** [comment]
this was added in latest release
