### ISSUE TITLE
Automation Policy 'Block Policy Inheritance' Not Functioning

### ISSUE THREAD

**Issue by r3die** [wh1te909/tacticalrmm#713]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome & Edge
 - RMM Version (as shown in top left of web UI):0.8.4

**Installation Method:**
  - [X ] Standard
  - [ ] Docker

**Describe the bug**
When an Automation Policy is set to a Client or Site and 'Block Policy Inheritance' is checked on a specific agent, the checks from the policy are still inherited from the Automation Policy of the Parent OU

**To Reproduce**
1. Select a Client Site , right click and Assign Automation Policy
2. Select an agent under that site, right click and Assign Automation policy (choose a different policy and check 'Block Policy Inheritance')
4. Refresh checks/ Sync policies and review checks of the agent that should have the policy blocked to find the original checks are still present

**Expected behavior**
After Syncing Automation Policies and Refreshing the checks on the agent the checks from the policy assigned to the parent OU should not be present.

**Comment by sadnub** [comment]
It looks like the checkbox wasn't actually saving when set in the UI. I just submitted a fix for this. Will be in the next update.

**Comment by silversword411** [comment]
Closing, as there is no PR to link for auto-closing
