### ISSUE TITLE
Have Task runs appear in History tab

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#716]
Have manual and automatic runs of items from Tasks appear under the History tab for agents.

Optional: Should there be a setting under general to enable/disable this?

**Comment by evilexecutable** [comment]
I would have expected this to be default behavior. Any task run against a machine/agent should be in the history. It might be nice to have a toggle for those used to the "old ways" though.

**Comment by silversword411** [comment]
Could also have some indicator (color difference)/filter of show all/manual only/automatic only.

**Comment by wh1te909** [comment]
this should have been the default but just never got implemented, i've just added it, will be in next release
