### ISSUE TITLE
Enhancement-Permission Manager : Limit access to certain Clients and/or sites to certain access roles

### ISSUE THREAD

**Issue by r3die** [wh1te909/tacticalrmm#719]
**Is your feature request related to a problem? Please describe.**
The goal is to limit access of certain clients/sites/or individual devices to 

**Describe the solution you'd like**
An 'Agent Access Exclusions' section/parameter in the Permissions Manager/ Edit Role window. The section would ideally allow you to include exclusions of clients, sites, and individual devices.

**Additional context**
Example: You want to limit access of lower tier technicians from highly sensitive endpoints

**Comment by Thalooka** [comment]
Would like to see that one as of now we got a few on-site it ppl who dont have any relation to other customers and need to set up a new rmm instance for them

**Comment by silversword411** [comment]
This is probably a duplicate/covered by #494

**Comment by wh1te909** [comment]
it's actively being worked on and yes there is already an issue to track this in #494
