### ISSUE TITLE
Add security policy and document how to report security issues

### ISSUE THREAD

**Issue by NiceGuyIT** [wh1te909/tacticalrmm#725]
**Is your feature request related to a problem? Please describe.**
Tactical RMM does not have a security policy. Nor does it provide any information on how to report security-related issues.

**Describe the solution you'd like**
Please implement a security policy and describe how security-related issues can be reported.

**Describe alternatives you've considered**
DM developers on Discord.

**Additional context**
This feature request is to report security related issues outside GitHub's issue tracking which is public.

**Comment by bbrendon** [comment]
Here is an example to steal. https://www.home-assistant.io/security/

**Comment by wh1te909** [comment]
added https://wh1te909.github.io/tacticalrmm/security/ thanks
and thanks @bbrendon for the example, stolen :)
