### ISSUE TITLE
Reinstalling agent causes error

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#727]
Same happens with a clean traditional install. The Server last for about 2 hours and its already broken because of a attempt to reinstall a single client.

(Yes I followed the guide exactly with a clean ubuntu 20.04)

To unstable for my needs. Looking for another solution now.

_Originally posted by @Traace in https://github.com/wh1te909/tacticalrmm/issues/3#issuecomment-923918429_

**Comment by silversword411** [comment]
You posted this on an almost 1.5 year old resolved issue. Testing here, I can reinstall agents without issue. Can you provide further details/screenshots about what you encountered?

**Comment by silversword411** [comment]
Closing, post if you have info.

**Comment by Traace** [comment]
This content was meant as a comment, not a issue. Now i can't even edit this because you copy&paste it into a new issue.. Why?!

**Comment by wh1te909** [comment]
@Traace not documented but you can use your own certs (needs to be wildcard) in standard install too. instructions here https://github.com/wh1te909/tacticalrmm/issues/196#issuecomment-737079364
