### ISSUE TITLE
SMS Alerts not working

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#728]
Testing with 0.8.4

SMS test alerts working
If agent online, or task selected with email and SMS alert email alert is received, but not SMS (last working Aug 11)

Verified problem: https://discord.com/channels/736478043522072608/889513877124042762/890260168804278332

**Comment by sadnub** [comment]
Can you post you django_debug.log file? Wondering if you are running into any errors in the celery tasks

**Comment by silversword411** [comment]
Fixed in https://github.com/wh1te909/tacticalrmm/commit/d1d6d5e71e9ac9736d6b077bcc3a332f388151f1

`and` vs `or` Line 199

Thx @sadnub !
