### ISSUE TITLE
[Feature Request] SIte/Customer based secrets

### ISSUE THREAD

**Issue by LefflerMediaLLC** [wh1te909/tacticalrmm#729]
I love having secrets. I would love to have site or customer based secrets though. For example I install SentinelOne and it'd be nice to have a different secret/variable to use in the script based on the site/customer that I'm running the script on. 

If that's already a thing let me know. I know there's a custom field, but I'm not sure if that's safe/encrypted.

**Comment by silversword411** [comment]
TRMM is safe (it does have root Command and Control of all machines connected to it), and that's what custom fields is designed for.
