### ISSUE TITLE
FR: Export all assets from all computers in a .csv

### ISSUE THREAD

**Issue by Codixer** [wh1te909/tacticalrmm#730]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem

**Describe the solution you'd like**
A button to export all **assets** from all computers at once. This way we can import all computers and their details in our inventory management system (Topdesk)

**Describe alternatives you've considered**
Making a script to import them through the API

**Additional context**
NA

**Comment by dinger1986** [comment]
please add to report feature request already open #523
