### ISSUE TITLE
Rework script testing in Script editor

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#734]
The "Test Script" function being another popup dialog makes for constant choosing agent and entering arguments every time you want to make a change and test. Is it possible to have it look more like this:

![2021-09-25_174153 - script editor rework testing](https://user-images.githubusercontent.com/13395348/134786742-a865b5b5-13f5-4bab-a245-a110d75b4e3a.png)

and then the output log is the popup window instead?

**Comment by silversword411** [comment]
When this is worked on, can you have additional display items appear in the Select Agent field. If there's 3 computers called "laptop2018" can't pick the right one. Have something like:
`$hostname | Client: $clientname | Site: $sitename | Description: $description`

**Comment by sadnub** [comment]
I just added this. Will be in the next release

**Comment by silversword411** [comment]
Looks like all the magic was in this commit. Reference for future generations ;)

https://github.com/wh1te909/tacticalrmm/commit/3fff56bcd76c738f397158d242dfa97827646447
