### ISSUE TITLE
Question backup 

### ISSUE THREAD

**Issue by krystophe** [wh1te909/tacticalrmm#741]
Hello,

How to backup tacticalrmm with docker ?
Can I just copy /var/lib/docker/volumes/tacticalrmm_*  ?

Thanks for response

**Comment by dinger1986** [comment]
The backup script isn't setup for docker so will be the same process as backing up any docker containers. https://docs.docker.com/desktop/backup-and-restore/

**Comment by silversword411** [comment]
Marking closed, post if further questions
