### ISSUE TITLE
See which package is installed by Chocolatey and allow to upgrade

### ISSUE THREAD

**Issue by bdrayersyno** [wh1te909/tacticalrmm#745]
It will be great if there is a way to see which Software have been installated using Chocolatey and allow, with a right click to upgrade it or remove it (I know it's possible to do everything using powershell but it will be more integrated with such thing)

**Comment by bdrayersyno** [comment]
One default of Winget (but it will perhaps evolve) is the ability to only have one repository. I forget it on my side for this reason, ...

**Comment by silversword411** [comment]
The script is updated and should be working now
