### ISSUE TITLE
Feature Request: Maintenance mode

### ISSUE THREAD

**Issue by dan578** [wh1te909/tacticalrmm#75]
Hi,

Is it possible to get a Maintenance mode? Right clicking on the server/workstation for example them Maintenance mode which would suppress all alerts while active? Maybe a reminder every few days that the server is in maintenance mode by email so it doesn't get left permanently. They could show a different colour in the dashboard too?

Thanks!
Daniel

**Comment by wh1te909** [comment]
good request i'll work on it

**Comment by sadnub** [comment]
#148 @dan578 Adds maintenance mode support. You can enable/disable at the Client, Site, and Agent Level. Clients and Sites will turn yellow when they contain agents in maintenance mode. The agent check icon and summary will also indicate if the agent is in maintenance mode.

**Comment by wh1te909** [comment]
merged!
