### ISSUE TITLE
Docker behind HAProxy, port 4222 issue

### ISSUE THREAD

**Issue by ninjamonkey198206** [wh1te909/tacticalrmm#752]
I've managed to get everything else working seemingly without issue, and was even able to cut out some of the somewhat redundant HAProxy (on PFSense) ACLs.

However, I cannot get the agent to work properly because port 4222 refuses the connection.

I've tried port forwarding with opening the port on the server firewall, and it still fails.

The only thing I have t tried is setting up an HAProxy listener on 4222 to direct the traffic, only because I have no idea what URL it uses.

Any thoughts?

**Comment by ninjamonkey198206** [comment]
I'm using a LetsEncrypt cert managed by the PFSense.

Exported the cert and key, input them into the env file per instructions.

Everything else seems fine. I can log in, go through set up, access the site, download the agent, etc, all using that imported cert info.

So dumb question: when port forwarding, it should be forwarded to the host IP address, as docker listens for exposed ports on all interfaces, prior to any other rules, correct?

**Comment by dinger1986** [comment]
Yes I think it should be port forwarding to the docker host (I don't use docker).

SSL setup sounds fine, was just checking.

Feel free to give us the HAProxy setup steps you used if you don't mind to help others.

**Comment by ninjamonkey198206** [comment]
@silversword411 I'm aware it's an unsupported config. Unfortunately that example has nothing aside from making sure the port is forwarded included for 4222.

It would be remarkably simple to forward it with HAProxy if I could simply find out what URL it's supposed to be directed to.

**Comment by dinger1986** [comment]
It should be pointed at the host as it's a port forward URLs/haproxy etc are irrelevant

**Comment by silversword411** [comment]
But yes dinger is right....a port forward is IP:port only, no URL's necessary :)

**Comment by dinger1986** [comment]
Gotta be something else wrong. Do you have ufw enabled on the host? Maybe need to open ports on there? It's TCP port forward you need

**Comment by ninjamonkey198206** [comment]
I use iptables with no management interface.

I'll work on getting things ready to post images of current configs.

**Comment by ninjamonkey198206** [comment]
It's fully functional using a let'sencrypt cert, exporting it, and importing it into the env file. I edited the docker-compose file to use different exposed ports (rather than 80 and 443) since I have multiple services running on my server.

HAProxy config on my PFSense device, edited to remove actual URLs and other services:

# Automaticaly generated, dont edit manually.
# Generated on: 2021-10-09 14:34
global
	maxconn			10000
	stats socket /tmp/haproxy.socket level admin  expose-fd listeners
	uid			80
	gid			80
	nbproc			1
	nbthread			1
	hard-stop-after		15m
	chroot				/tmp/haproxy_chroot
	daemon
	tune.ssl.default-dh-param	2048
	server-state-file /tmp/haproxy_server_state

listen HAProxyLocalStats
	bind 127.0.0.1:2200 name localstats
	mode http
	stats enable
	stats refresh 30
	stats admin if TRUE
	stats show-legends
	stats uri /haproxy/haproxy_stats.php?haproxystats=1
	timeout client 5000
	timeout connect 5000
	timeout server 5000

frontend http_shared
	bind			0.0.0.0:80 name 0.0.0.0:80   
	mode			http
	log			global
	option			http-keep-alive
	option			forwardfor
	acl https ssl_fc
	http-request set-header		X-Forwarded-Proto http if !https
	http-request set-header		X-Forwarded-Proto https if https
	timeout client		30000
	acl			rmm	var(txn.txnhost) -m str -i rmm.example.com
	acl			api	var(txn.txnhost) -m str -i api.example.com
	acl			mesh	var(txn.txnhost) -m str -i mesh.example.com
	http-request set-var(txn.txnhost) hdr(host)
	http-request redirect scheme https  if  rmm 
	http-request redirect scheme https  if  api 
	http-request redirect scheme https  if  mesh 

frontend https_shared-merged
	bind			0.0.0.0:443 name 0.0.0.0:443   ssl crt-list /var/etc/haproxy/https_shared.crt_list  
	mode			http
	log			global
	option			socket-stats
	option			dontlognull
	option			http-server-close
	option			forwardfor
	acl https ssl_fc
	http-request set-header		X-Forwarded-Proto http if !https
	http-request set-header		X-Forwarded-Proto https if https
	timeout client		30000
	acl			aclcrt_https_shared	var(txn.txnhost) -m reg -i ^([^\.]*)\.example\.com(:([0-9]){1,5})?$
	acl			rmm	var(txn.txnhost) -m str -i rmm.example.com
	acl			api	var(txn.txnhost) -m str -i api.example.com
	acl			is_websocket	hdr(Upgrade) -i WebSocket
	acl			mesh	var(txn.txnhost) -m str -i mesh.example.com
	http-request set-var(txn.txnhost) hdr(host)
	http-request set-var(txn.txnpath) path
	use_backend rmm.example.com_ipvANY  if  rmm 
	use_backend rmm.example.com_ipvANY  if  api 
	use_backend mesh.example.com-websocket_ipvANY  if  is_websocket mesh 
	use_backend mesh.example.com_ipvANY  if  mesh 

frontend api.example.com
	bind			0.0.0.0:4222 name 0.0.0.0:4222   ssl crt-list /var/etc/haproxy/api.example.com.crt_list  
	mode			http
	log			global
	option			socket-stats
	option			dontlognull
	option			http-server-close
	option			forwardfor
	acl https ssl_fc
	http-request set-header		X-Forwarded-Proto http if !https
	http-request set-header		X-Forwarded-Proto https if https
	timeout client		30000
	acl			api	var(txn.txnhost) -m str -i api.example.com
	acl			aclcrt_api.example.com	var(txn.txnhost) -m reg -i ^([^\.]*)\.example\.com(:([0-9]){1,5})?$
	http-request set-var(txn.txnhost) hdr(host)
	use_backend api.example.com_ipvANY  if  api aclcrt_api.example.com

backend rmm.example.com_ipvANY
	mode			http
	id			122
	log			global
	timeout connect		30000
	timeout server		30000
	retries			3
	server			rmm 10.0.2.4:4443 id 125 ssl  verify none 

backend mesh.example.com-websocket_ipvANY
	mode			http
	id			126
	log			global
	timeout connect		15000
	timeout server		15000
	retries			3
	timeout tunnel      3600000
	http-request add-header X-Forwarded-Host %[req.hdr(Host)]
	http-request add-header X-Forwarded-Proto https
	server			mesh-websocket 10.0.2.4:4443 id 125 ssl  verify none 

backend mesh.example.com_ipvANY
	mode			http
	id			127
	log			global
	timeout connect		3000
	timeout server		3000
	retries			3
	timeout tunnel      15000
	http-request add-header X-Forwarded-Host %[req.hdr(Host)]
	http-request add-header X-Forwarded-Proto https
	server			mesh 10.0.2.4:4443 id 125 ssl  verify none 

backend api.example.com_ipvANY
	mode			http
	id			128
	log			global
	timeout connect		30000
	timeout server		30000
	retries			3
	server			api 10.0.2.4:4222 id 125 ssl  verify none

Photos of PFSense gui and functional rmm and mesh connection coming after editing.
