### ISSUE TITLE
Celery uses 50-80% of cpu most of time

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#773]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: [e.g. chrome, safari]: All browsers
 - RMM Version (as shown in top left of web UI): 0.8.5

**Installation Method:**
  - [x] Standard - Yes
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2]

**Describe the bug**
Celery process is using high cpu all the time

**To Reproduce**
Just boot the server. after a few hours the cpu starts to get high

**Expected behavior**
Not be so high usage all the time...

**Screenshots**
![image](https://user-images.githubusercontent.com/82226898/139406208-5546d2bd-8be3-4966-a365-c91f7c22f5b0.png)

**Additional context**

**Comment by silversword411** [comment]
Looks like we're going to punt this till after the agent refactor. For now, monitor server and if celery goes CPU crazy just reboot.

Temp workaround for now.
