### ISSUE TITLE
Bulk removal of agents

### ISSUE THREAD

**Issue by ampl1tude** [wh1te909/tacticalrmm#775]
From time to time we need to offboard agents in bulk (our use case it generally temporary for each site). At present there doesn't seem to be a way to remove agents in bulk. Manually removing 300+ agents one at a time especially if that agent is offline is therefore quite problematic.

It would be good to have an option to firstly run the removal process across multiple agents and then throw in the option to force the removal for offline devices.

**Comment by dinger1986** [comment]
please search before adding a new request, already covered in #708 

feel free to add comments to there
