### ISSUE TITLE
Legacy User with no roles

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#778]
Older installs pre-user permissions never have roles, should that be fixed to make sure proper permissions get set?
 
![2021-11-04_182406 - brave_Tactical_RMM_-_Brave](https://user-images.githubusercontent.com/13395348/140429015-63f2cdad-168c-4744-9028-1b23d25a4bac.png)

Same thing with as new user permissions are added they aren't enabled by default in manager:

![2021-11-04_182857 - brave_Tactical_RMM_-_Brave](https://user-images.githubusercontent.com/13395348/140429199-2c132ea8-1d5e-4a7d-bd95-ecfa9e1e27d8.png)

Assuming super till it's restricted makes my gut say **danger**

**Comment by sadnub** [comment]
Non-superusers that have no role assigned won't have permissions for anything in the latest changes.
