### ISSUE TITLE
Add client to allowed clients when it was created by a limited user

### ISSUE THREAD

**Issue by FrBillyD** [wh1te909/tacticalrmm#782]
Hello, 👋

It would be interesting to automatically add the clients created in the list of authorized clients when a user has limited permissions.
I created a role with the following permissions:
- List Customers
- Manage Clients
- List Sites
- Manage Sites

This agent then has permission to create new clients but he does not see them because he does not have the right to do so. However, he does see the clients that already exist in "Allowed clients". 🙃

For now, we need to ask a user with more power to be able to add him to this role.

It would be interesting to be able to do that to delegate the creation of clients.
For example, I imagine someone who should act as a technician for a customer who does not yet exist.

![image](https://user-images.githubusercontent.com/4552702/140636850-f8ab7d36-69af-4007-8298-a4db7b65ad05.png)

I think this is achievable but we should see the impacts.

Thanks a lot for your consideration. 🥰

**Comment by sadnub** [comment]
That is a great idea! Will definitely add this since it makes sense.

**Comment by sadnub** [comment]
This has been implemented and will be in the next release!

**Comment by FrBillyD** [comment]
Great ! 😎 I didn't think it would be implemented so quickly. 😱
Thank you very much, glad my idea makes sense. 🤗

**Comment by wh1te909** [comment]
added in release 0.9.1
