### ISSUE TITLE
Mandatory fields missing (need at least 1 recipient) when there is indeed a recipient

### ISSUE THREAD

**Issue by cm-slu** [wh1te909/tacticalrmm#783]
**Server Info (please complete the following information):**
 - OS: [Ubuntu 20.04,]
 - Browser: [chrome]
 - RMM Version (as shown in top left of web UI): 9.0

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Describe the bug**
In the configuration of the smtp server during the email sending test, a message indicates that a recipient is missing even though it is present.

**To Reproduce**
1. Go to Global seting
2. Click on Email Alerts
3. Click on button Save and test email
4. See error Mandatory fields missing (need at least 1 recipient) when there is indeed a recipient

![image](https://user-images.githubusercontent.com/82769965/140642725-a582d2f5-5f4d-4438-a4a6-cd7064c2b74b.png)

**Comment by sadnub** [comment]
This has been fixed and will be in the next release

**Comment by wh1te909** [comment]
fixed in release 0.9.1
