### ISSUE TITLE
A user without permission to view configuration can view and modify smpt configuration

### ISSUE THREAD

**Issue by cm-slu** [wh1te909/tacticalrmm#784]
**Server Info (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Browser: [chrome]
 - RMM Version (as shown in top left of web UI): 9.0

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Describe the bug**

A user without permission to view configuration can view and modify smpt configuration and save

![image](https://user-images.githubusercontent.com/82769965/140642781-a737a786-5aae-4cd2-a223-4831edf626e7.png)

**Comment by sadnub** [comment]
This has been fixed and will be in the next release

**Comment by wh1te909** [comment]
fixed in release 0.9.1
