### ISSUE TITLE
Audit Log for user with no permission to view keeps loading

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#785]
**Server Info (please complete the following information):**
 - OS: 20.04
 - Browser: Edge
 - RMM Version (as shown in top left of web UI): 0.9.0

**Installation Method:**
  - [x ] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.6.2
- Agent OS: Windows 10

**Describe the bug**
When a user without permission goes to view the Audit Log tab for an agent, the table is in a constant state of loading. This is different than other tabs where it will load and just say No data available.

**To Reproduce**
1. Create user with List Agents, Edit Agents, List Clients, List Sites permissions.
2. Log in as user
3. View Audit tab for any agent
4. Table continues to load.

**Expected behavior**
Table should eventually load with a message of No data available like other tabs.

**Comment by sadnub** [comment]
This has been fixed. Will be in the next release!

**Comment by wh1te909** [comment]
fixed in release 0.9.1
