### ISSUE TITLE
No scroll bar in Take Control - can't see Mesh options at the bottom

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#786]
**Server Info (please complete the following information):**
 - OS: 20.04
 - Browser: Edge and Chrome
 - RMM Version (as shown in top left of web UI): 0.9.0

**Installation Method:**
  - [ x] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.6.2
- Agent OS: Windows 10

**Describe the bug**
Right-clicking on agent and going to Take Control, there are Mesh options at the bottom that cannot be accessed due to the lack of a scroll bar.

**To Reproduce**
1. Right-click on agent and click Take Control
2. Try to scroll to see options at the bottom

**Expected behavior**
A scroll bar should be present, or the entirety of the Mesh Central Take Control feature should be present on screen.

**Comment by sadnub** [comment]
I submitted a potential fix for this. It works on my laptop, but white is going to test on his as well

**Comment by wh1te909** [comment]
fixed in release 0.9.1
