### ISSUE TITLE
Tasks tab continuous loading

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#790]
**Server Info (please complete the following information):**
 - OS: 20.0.4
 - Browser: Edge
 - RMM Version (as shown in top left of web UI): 0.9.1

**Installation Method:**
  - [ x] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.6.2
- Agent OS: Windows 10

**Describe the bug**
When logging in as a user that does not have permission to List Tasks and you click on that tab for an agent, it is continually loading.

**To Reproduce**
1. Log in with a user that does not have permission to view Tasks
2. Click on an agent and click on the Tasks tab.

**Expected behavior**
Task tab should finish loading and produce a No data available message or something similar.

**Comment by wh1te909** [comment]
thanks there are probably more, i'm going through and fixing
