### ISSUE TITLE
When trying to delete an automation task html content is shown in alert

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#791]
**Server Info (please complete the following information):**
 - OS: 20.0.4
 - Browser: Edge
 - RMM Version (as shown in top left of web UI): 0.9.1

**Installation Method:**
  - [ x] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.6.2
- Agent OS: Windows 10

**Describe the bug**
When trying to delete a task from an automation policy, an alert displays with HTML content stating the Requested resource could not be found.

**To Reproduce**
1. Go to Settings -> Automation Manager
2. Select an existing Automation Policy
3. Go to the Tasks tab and then try to delete a task

**Expected behavior**
The task should delete successfully with no error

**Screenshots**

![Capture](https://user-images.githubusercontent.com/74523447/140664660-af9edbb4-71dc-413d-8ba8-4d8c1a0dc5e9.PNG)

**Comment by sadnub** [comment]
This is fixed now. Will be in the next release

**Comment by wh1te909** [comment]
fixed in release 0.9.2
