### ISSUE TITLE
Unable to turn on AOF after version updates

### ISSUE THREAD

**Issue by evolantechnology** [wh1te909/tacticalrmm#792]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - RMM Version (as shown in top left of web UI): 0.9.1

**Installation Method:**
  - [ x] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.6.2
- Agent OS: Win 10

**Describe the bug**
"ERR Unable to turn on AOF. Check server logs." Getting this error at the end of a version update, after all services are automatically started back up.

**To Reproduce**
1. After running ./update.sh and waiting for it to complete, the above error displays after the update completes and services start up.

**Expected behavior**
The update should complete successfully with no errors.

**Screenshots**

![Screen Shot 2021-11-07 at 8 02 38 PM](https://user-images.githubusercontent.com/79764766/140674421-a48d524d-4640-48d4-957c-f116f619137c.png)

**Additional context**

**Comment by silversword411** [comment]
I get the same here. I think it's something to do with redis and log replaying feature. Haven't found a side-effect from it yet.

**Comment by silversword411** [comment]
We're going to close this, you can ignore. Let us know if you see something come of it
