### ISSUE TITLE
No scroll bar in Remote Background | Terminal - can't see Mesh options at the bottom

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#793]
Same as this
https://github.com/wh1te909/tacticalrmm/issues/786

Just Remote Background | Terminal

**Comment by subzdev** [comment]
I am able to see the options. Are you on the latest version?

**Comment by wh1te909** [comment]
we didn't change the terminal/file browser those are still using the old iframe settings. will just update with same changes we made to take control

**Comment by sadnub** [comment]
This has been fixed and will be in the next release

**Comment by wh1te909** [comment]
fixed in release 0.9.2
