### ISSUE TITLE
Issue Script

### ISSUE THREAD

**Issue by darkh89** [wh1te909/tacticalrmm#796]
![Capture](https://user-images.githubusercontent.com/17270382/141104534-fbbcdef3-c957-4e04-ad79-3c93741f4e04.PNG)

Please, remove the , after "install"

**Comment by dinger1986** [comment]
What script?

**Comment by darkh89** [comment]
Sorry, I forgot.

It's Win_Chocolatey_Manage_Apps_Bulk.ps1

**Comment by dinger1986** [comment]
ok, thats a community script and not maintained by ourselves, they are maintained by the community on discord and submitted via pull request @silversword411 might be able to change this however

**Comment by silversword411** [comment]
Yes, extra comma and typo are wrong in the live script but I'm trying to get that fully reworked.

Join discord #scripts to help rework.
