### ISSUE TITLE
Policies assigned to clients - Block Policy Inheritance

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#797]
I had some clients prior to 0.9.0 that had a workstation policy, with Block policy inheritance checked. They now show with "-" sign

![2021-11-10_102256 - brave_Tactical_RMM_-_Brave](https://user-images.githubusercontent.com/13395348/141143330-f028d950-0ef7-48c5-9863-7a002b9066d8.png)

and the global policy is no longer blocked. 

Can't re-enable check (doesn't get remembered)

**Comment by sadnub** [comment]
This has been fixed. Will be in the next release
