### ISSUE TITLE
Policies not applying tasks

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#80]
When applying a policy to a client or site checks are applied as expected however tasks do not apply.

Applying a policy directly to an agent pops up an error "Something went wrong" but nothing appears in the debug logs although the policy does apply, this also pulls down the site policy to the agent and creates the tasks.

**Comment by sadnub** [comment]
I think I found the issue with this. Getting a fix together now. I wasn't able to replicate the policies being applied directly to the agent though. Does anything show up in the JS console when that happens?

**Comment by sadnub** [comment]
Just submitted the PR that will fix this. It appears the policy task creation would happen before the checks were created on the agent. Thanks for testing!
