### ISSUE TITLE
Change drive progress bar colour depending on fullness

### ISSUE THREAD

**Issue by gurizz** [wh1te909/tacticalrmm#802]
**Is your feature request related to a problem? Please describe.**
Nope.
**Describe the solution you'd like**
When a drive reaches near capacity, change the colour of the below progress bar accordingly
![image](https://user-images.githubusercontent.com/44413296/141823121-2c469f7c-505f-492b-b366-020e87dbd052.png)

Could possibly be done as 80% turns orange, 95% turns red? Whatever it is, it would be nice to visually see at a quick glance that a drive is low on space.

**Comment by wh1te909** [comment]
done will be in next release

![z5AJp6S32I](https://user-images.githubusercontent.com/7434746/142373595-28603f60-2f54-49f8-bbfe-944ec2da093c.png)
