### ISSUE TITLE
Move Custom Fields in Edit agent

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#804]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
The Custom Fields should be moved to it's own vertical tab in the Edit Agent modal.

**Describe alternatives you've considered**

**Additional context**
Because Custom Fields is a major feature of Tactical RMM, it makes sense for it to have it's own spot as a tab within the Edit Agent modal.

**Comment by sadnub** [comment]
I implemented this and will be in the next release
