### ISSUE TITLE
Last Response doesn't update

### ISSUE THREAD

**Issue by ThanosAntmanEntrance** [wh1te909/tacticalrmm#805]
Hey Guys, 
I don't know if it should be so but i think the "Last Response" dont update. It just shows the Date and Time I installed the Agent on the Computer.

**Comment by dinger1986** [comment]
Can you share a screenshot?

Also you haven't given any info at all about the client computer

**Comment by ThanosAntmanEntrance** [comment]
Oh Sorry,
Server runs on Raspi 400
OS of Server Ubuntu 20.04
Server is local and every client can communicate with it
OS of Computer Win10 Home 64 Bit
all Intel i5, i7, i9
![Unbenannt](https://user-images.githubusercontent.com/89837637/142197695-3e96b084-d9bd-4f38-8ecf-6e5b0d09a712.PNG)

**Comment by dinger1986** [comment]
Have they ever communicated?

I didn't think tactical was supported on arm yet so maybe nats isn't running?

**Comment by dinger1986** [comment]
I would suggest discussing this on discord as its unsupported and looks like the arm version of nats isnt compatible
