### ISSUE TITLE
Script Check and Task Issues

### ISSUE THREAD

**Issue by inathanb6** [wh1te909/tacticalrmm#808]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - RMM Version 0.9.2

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version: Agent v1.6.2
- Agent OS: Win 11

**Describe the bug**
Not sure if bug, or I'm misunderstanding the "Script Checks" option. Currently I have a Powershell script check that looks for installed software, if the software is installed it exit's with code 0 (success, as I want the software to be installed), if the software is not installed it exit's with code 1. Under my test device that check shows "Error" which is the result I want, as the software is not installed on the test machine. If the check fails, I have a task set to run that will install the software, that task just sits with "Synced with Agent", "Awaiting output", "Has not run yet" even though the schedule is set to "Every time check fails" and the "Assigned Check" is the script check that is in failed status. My script check for the software is here: https://ghostbin.com/QdWNE ("Software Name Here" is the name of my program in Programs and Features, verified it returns codes correctly depending on whether software is installed)

The "Script Output" returns 1 as expected, just the task never executes:
Last Run: Nov-18-2021 - 09:38
Run Time: 0.5215 seconds
Return Code: 1

**To Reproduce**

**Expected behavior**
If the script check returns code 1, then the task will execute installing the software

**Screenshots**
![image](https://user-images.githubusercontent.com/67111712/142436334-86964660-b6a1-465f-ab65-4ce40be6cff1.png)
![image](https://user-images.githubusercontent.com/67111712/142439788-9f392f97-f706-4bd1-a904-b6a8d0346650.png)
![image](https://user-images.githubusercontent.com/67111712/142436383-b1c1b37e-3605-474b-b1bc-924059a70751.png)
![image](https://user-images.githubusercontent.com/67111712/142439925-0cc28654-62df-4fb3-a32c-1ed7fef13c40.png)
![image](https://user-images.githubusercontent.com/67111712/142439974-fc8ffce6-3d0f-4cd2-b736-e93d922d9b6f.png)

**Comment by dinger1986** [comment]
was the check already in the failed state before you created the task?

**Comment by inathanb6** [comment]
> was the check already in the failed state before you created the task?

It is possible, I created the task right after creating the check though and I'm not sure how to wait for the task before the check? 

The check is set to go every "0" seconds which seems to be every minute... Maybe it's not long enough for the task to run?

**Comment by dinger1986** [comment]
I dont know but I cant replicate it. 

I created a ping test going to 10.11.11.11 (which doesn't exist) and a task runs to check defender status if that fails, 

I have done that and then changed the ping to another ip so it passes and then make it fail again and it works fine.

I also tried adding a task after it was already in a failed state and it ran fine.

Can you try it with a ping test? Maybe its the script check? Can you add the task into the check?

**Comment by inathanb6** [comment]
> Can you try it with a ping test? Maybe its the script check?

I'm able to run the built-in checks and tasks execute successfully on those, it appears to only be the script checks that are not working for me. 

> Can you add the task into the check?

Are you saying can I add the software install into the check script? If so, I can and I'm sure that would work. Just was thinking this way might be more bullet proof as I can see if the task ran or not, but I guess I could script that part as well...

**Comment by dinger1986** [comment]
I'll try script checks later on when I am back in front of my machine and see if I can replicate the bug then.

**Comment by inathanb6** [comment]
> I'll try script checks later on when I am back in front of my machine and see if I can replicate the bug then.

This was my fault... When copy-pasting my task script it looks like either myself or the computer removed a space in one of the arguments, adding the space resolved this. 

Sorry for the false bug report lol

**Comment by dinger1986** [comment]
No worries.

Glad it's sorted!
