### ISSUE TITLE
Saving Scripts Error

### ISSUE THREAD

**Issue by inathanb6** [wh1te909/tacticalrmm#809]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome/Brave/Edge/Firefox
 - RMM Version: v0.10.0

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version: v1.7.0
- Agent OS: Win11

**Describe the bug**
After updating this morning to the new version, when going to save a script we are receiving "filename: This field may not be blank. 400: Bad Request", but there is no filename field, and no matter what you fill out it still prompts the error.

**To Reproduce**
1. Go to "Settings>Script Manager"
2. Click on A script that you'd like to edit
3. Select "Save"

**Expected behavior**
For the script to save

**Screenshots**
![image](https://user-images.githubusercontent.com/67111712/142648904-4cdcf324-4406-4aeb-861c-e465f643cca9.png)
![image](https://user-images.githubusercontent.com/67111712/142648947-659a1a54-c817-4a4d-9b60-b0b065c7a6ff.png)

**Comment by dinger1986** [comment]
Hello,

Yes there is a known error with the script editor.

**Comment by inathanb6** [comment]
> Hello,
> 
> Yes there is a known error with the script editor.

Okay, thank you!

**Comment by sadnub** [comment]
Check this thread in the discord. You can run the commands on the server to fix this before the next release
https://discord.com/channels/736478043522072608/888474369544847430/911273411853053993

**Comment by inathanb6** [comment]
> Check this thread in the discord. You can run the commands on the server to fix this before the next release https://discord.com/channels/736478043522072608/888474369544847430/911273411853053993

That worked, boom. Thank you!

**Comment by wh1te909** [comment]
fixed in release 0.10.1
