### ISSUE TITLE
Feature Request: 32 bit agent

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#81]
Have customers who still have 32 bit machines, can we please have a 32 bit rmm agent.

**Comment by wh1te909** [comment]
Can you try with the attached binary.
You'll need to do the manual installation for now and then pass these arguments to the end of the install command generated from the web
```
--local-salt "C:\\path-to-your\\saltminion32bit.exe" --local-mesh "C:\\path-to-your\\meshagent32bit.exe"
```
[winagent-v0.10.2-x86.zip](https://github.com/wh1te909/tacticalrmm/files/5143623/winagent-v0.10.2-x86.zip)

**Comment by bradhawkins85** [comment]
I'm sure it's something I'm doing wrong but I'm getting an error.

The install command I'm using: 
winagent-v0.10.2-x86 /VERYSILENT /SUPPRESSMSGBOXES && timeout /t 20 /nobreak > NUL && "C:\Program Files\TacticalAgent\tacticalrmm.exe" -m install --api "https://api.......com.au" --client-id 1 --site-id 1 --agent-type "workstation" --power 1 --rdp 1 --ping 1 --auth "authkey" --local-salt "C:\\Users\\Win7x32\\Desktop\\Salt-Minion-3001.1-Py3-x86-Setup.exe" --local-mesh "C:\\Users\\Win7x32\\Desktop\\meshagent32-TacticalRMM.exe"

The error:
Traceback (most recent call last):
  File "C:\Users\Public\Documents\tacticalagent\env\Lib\site-packages\PyInstalle
r\hooks\rthooks\pyi_rth_multiprocessing.py", line 17, in <module>
  File "c:\users\public\documents\tacticalagent\env\lib\site-packages\PyInstalle
r\loader\pyimod03_importers.py", line 493, in exec_module
  File "multiprocessing\__init__.py", line 16, in <module>
  File "c:\users\public\documents\tacticalagent\env\lib\site-packages\PyInstalle
r\loader\pyimod03_importers.py", line 493, in exec_module
  File "multiprocessing\context.py", line 6, in <module>
  File "c:\users\public\documents\tacticalagent\env\lib\site-packages\PyInstalle
r\loader\pyimod03_importers.py", line 493, in exec_module
  File "multiprocessing\reduction.py", line 16, in <module>
  File "c:\users\public\documents\tacticalagent\env\lib\site-packages\PyInstalle
r\loader\pyimod03_importers.py", line 493, in exec_module
  File "socket.py", line 49, in <module>
ImportError: DLL load failed while importing _socket: The parameter is incorrect
.
[892] Failed to execute script pyi_rth_multiprocessing

I've tested installing the salt minion and mesh agent manually and they work fine, I suspect the issue is in tacticalrmm.exe
I get the same error if I run tacticalrmm.exe from an admin command prompt.

Perhaps I am missing a prerequisite for the agent? I am testing on a fresh Win 7 x32 image.

**Comment by wh1te909** [comment]
yea fresh install needs a few KB's, im attaching the 3 KB's plus visual c++ redist that I had to install to get it working try that plz

[win7-reqs.zip](https://github.com/wh1te909/tacticalrmm/files/5148549/win7-reqs.zip)

**Comment by bradhawkins85** [comment]
that did the trick, everything looks to be working as expected.

**Comment by bradhawkins85** [comment]
any idea when you'll get a chance to add 32 bit installer to the web interface to generate the installer?

**Comment by wh1te909** [comment]
Hopefully this weekend. Sorry been crazy busy at work have not had much time. Still working on the new agent with some big changes and it will support 32 bit as well, need to also build the salt-minion 32 bit and upload that and 32 bit nssm to github cuz right now agent is hardcoded to download the 64 bit versions during install.

**Comment by bradhawkins85** [comment]
@wh1te909 Not a problem at all, I understand crazy busy. Thank you.

**Comment by wh1te909** [comment]
@bradhawkins85 new agent is out and updated web interface please try it out and let me know. You'll need to upload your 32 bit mesh agent first. File > Upload Mesh Agent. Haven't updated the powershell script though just the generated exe and manual methods.

**Comment by wh1te909** [comment]
closing this as 32 bit is fully implemented now and the powershell script has been fixed.
