### ISSUE TITLE
Make clicking name in agent removal dialog copy name to clipboard

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#810]
Make clicking name in dialog copy agent name to clipboard. Time Saver! :)

![2021-11-19_125749 - brave_Tactical_RMM_-_Brave](https://user-images.githubusercontent.com/13395348/142669654-86acfbd6-ae77-48dc-98cf-3bdc82ca9a6a.png)

**Comment by wh1te909** [comment]
hahaha I think I can just remove the need to type the name. Just was being extra cautious but I think just an "are you sure" prompt is enough. Plus we need to add a way to bulk delete agents.

**Comment by silversword411** [comment]
I'm good with either. :) 

You want to just rename this to bulk delete agent feature request?

**Comment by sadnub** [comment]
I like the Azure approach in that it makes you type "yes" when you delete anything. Easy and will cut back on accidental deletions
