### ISSUE TITLE
Enable agent automatic self update always enabled

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#816]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Edge Chromium
 - RMM Version (as shown in top left of web UI): v0.10.1

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v1.6.2
- Agent OS: Any

**Describe the bug**
Disabling "Enable agent automatic self update" in global settings does not stop agents from automatically updating the agent.

**To Reproduce**
1. Disable "Enable agent automatic self update"
2. Upgrade TRMM to a newer version where an agent upgrade is available
3. Agents get upgraded anyway

**Expected behavior**
Agents don't get automatically updated unless this setting is enabled.

**Additional context**
I need automatic updates disabled as upgrading the agent without first allowing the new version in ThreatLocker causes the agent to go offline, this would also effect other security software where whitelisting is required.

**Comment by wh1te909** [comment]
sorry about that, added a new management command in 0.10.0 that runs at the end of `update.sh` to trigger an agent update. forgot to check the global setting. the automatic agent update background task that runs once an hour is not affected that still honors the global setting.
