### ISSUE TITLE
List of applied policies in the edit agent window

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#819]
Be able to see from the edit agent dialog all the applied policies (automation, alert, and patch).

Something like this?

![2021-11-23_134056 - policies](https://user-images.githubusercontent.com/13395348/143084898-a1991d00-3377-41c8-8260-14c94fbb15e4.png)

**Comment by sadnub** [comment]
Added the tab to the agent edit window. Will now show:

-Applied policies
-Applied Alert Template
-Effective patch policy
