### ISSUE TITLE
Alert template not cleared when moving agent from Server to Workstation

### ISSUE THREAD

**Issue by meuchels** [wh1te909/tacticalrmm#821]
**Server Info (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Browser: [Brave]
 - RMM Version (0.10.1):

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (1.7.0):
- Agent OS: [Win 10 v21H1]

**Describe the bug**
When changing agent from server to workstation  the automation policy changes but the alert template from server is not removed.

**To Reproduce**
1. Go to 'Edit Agent'
2. Change type to 'workstation'
3. Wait template application.
4. See alerts are still sent via original alert policy and cannot be cleared.

**Expected behavior**
Alert policy from new Automation template should be applied.
If none exist all alerts should be removed.

**Additional Info**
Work around by clearing the alert template from the automation policy and re-adding it.

**Comment by sadnub** [comment]
This has been fixed and will be in the next release

**Comment by silversword411** [comment]
https://github.com/wh1te909/tacticalrmm/commit/b8eda37339fafb517c695f2abb441ba0e39a0420
