### ISSUE TITLE
Add syntax field to Script Manager for non-Community Script

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#822]
Right now the only place to get the syntax tooltip to work is in the json. 

Add a syntax field so custom/local scripts can have syntax tooltips created

![2021-11-23_231759 - trmm script syntax](https://user-images.githubusercontent.com/13395348/143174264-e076f495-9200-4c10-8444-37acc8cfc137.png)
.

**Comment by sadnub** [comment]
Fixed in 4d5bddb4135bc43d06ddd4b13d7b91d5faec95ea
