### ISSUE TITLE
Remote Background > Processes. Sort by CPU doesn't seem to sort in any order

### ISSUE THREAD

**Issue by af7567** [wh1te909/tacticalrmm#831]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox 94.0.2
 - RMM Version: v0.10.2

**Installation Method:**
  - [*] Standard
 
**Agent Info (please complete the following information):**
- Agent version: Agent v1.7.0
- Agent OS: Windows 10 Pro, 64 bit v21H1 (build 19043.1348)
- OS locale: UK English

**Describe the bug**
When sorting the processes by CPU, either ascending or descending, the sort order is not correct. Sorting by ascending CPU seems to work better but some things are still not in ascending order.

**Screenshots**
![screen-2021-11-28-21-27-31](https://user-images.githubusercontent.com/12093847/143786669-c7e40fe0-af5a-44d9-a036-4b582f65903f.png)
![screen-2021-11-28-21-27-22](https://user-images.githubusercontent.com/12093847/143786670-869f9aa8-c599-460f-b431-340060d4a2b7.png)

**Comment by sadnub** [comment]
I just pushed a fix for this. Will be in the next release!
