### ISSUE TITLE
Add logo to titlebar

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#839]
We would like to be able to upload a transparent .png logofile to the top of the titlebar and able to add a slogan wordphrase..
Because it would just look awsome at our wall.... :)

**Comment by silversword411** [comment]
Are you talking tactical or mesh?

**Comment by frankemann** [comment]
on tactical

![image](https://user-images.githubusercontent.com/82226898/144637827-63236a2c-4c9e-4458-8e47-d32527dd8d36.png)

**Comment by silversword411** [comment]
I'm actually going to close this issue since it's basically whitelabel support requested: https://github.com/wh1te909/tacticalrmm/issues/463
