### ISSUE TITLE
Feature Request: Add Run Script Option on Right Click Menu

### ISSUE THREAD

**Issue by Omnicef** [wh1te909/tacticalrmm#84]
It would be awesome if we could right click on an agent and have a run script option added to the menu. Right now I have to add it as a task. But if it's a one time thing, it would be easier that way.

**Comment by wh1te909** [comment]
ha yea great point I was running into this hassle myself, adding a task and choosing "manual" then having to right click it and "run task now" and then deleting the task immediately after LOL. Should be an easy addition I'll add soon.

**Comment by Omnicef** [comment]
Awesome!

**Comment by wh1te909** [comment]
done in 3afd20f3e2656d63c8e03c8b0faccccdbe2b2d14 please try it out and lmk
