### ISSUE TITLE
Reset Check Status

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#849]
It would be great to be able to reset the check status for X amount of hours (or 24 h), or until next day (00.00).

The use case is if we have a backup check, we investigate the error and fix it, the error check will return at next check because our scripts are checking for error in eventlogs for the last 24hours.

**Comment by silversword411** [comment]
If you click the flag (resolve alert) and the task checks once a day, for the previous 24hrs....isn't that the same thing?

**Comment by frankemann** [comment]
It's just that we actually don't work with the flag in the right corner..
We usually check all the Red/Orange status of the client/sites. Then go to their check, and fix whatever the check is reporting. In tat case the checks on the agent run (every 2 mins?) and the error will return..

Perhaps we are working somehow wrong..? :)

**Comment by dinger1986** [comment]
The flag resolves it until the next check is done. What's been suggested is changing the schedule to run once every 24 hours and then the flag will resolve it for 24 hours.

I mean for the majority of things a 24 hour check would suffice

**Comment by silversword411** [comment]
It's not wrong, but I would recommend doing it another way. 

First If the check is a script check with a 24hr window to query, why are you running it every 2mins? That's a LOT of excess data/cpu usage on client and server.
Second, if you snooze something from the top right menu...you can choose how long to snooze so the function is there already.

**Comment by frankemann** [comment]
It's a good point to move it from check to task actually, it makes totally sense.

But I guess it would then be nice to clear that task in the same way we clear the check also until next run (which then would be 24h on a daily schedule)

Wouldn't it also be good that the rask run as soon as the computer is online if it was not online during the scheduled run for the task?

**Comment by silversword411** [comment]
Being a task, if it didn't run just manually run it again. Takes like 2 seconds. Refresh, and look at the output. That's what's nice about it being a task. 

If it's in an error state, resolve it and it'll clear from agent list.

![2021-12-10_095835 - resolve](https://user-images.githubusercontent.com/13395348/145594411-8efb8d38-84ad-42c7-8f37-0e495c6169e0.png)

**Comment by silversword411** [comment]
I have one for defender logs. If it appears, I review (usually PUP stuck in vss snapshots) because backup touched it and it's been there a while. 

I erase source file
Flush VSS snapshots
Create new system restore point
Clear Defender logs
Clear alert.

Works great

**Comment by silversword411** [comment]
Consider this fixed unless we hear otherwise
