### ISSUE TITLE
Feature Request: Script Sorting

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#85]
It would be good if,
1) Scripts could be in "folders" as script lists will get very long over time. Perhaps when naming script something like Folder name/Folder name/Script name then you can click through "folders" when selecting a script

2) Scripts and folders sorted alphabetically

3) Scripts can be tagged as Checks or Tasks and only show in the appropriate sections, this will prevent tasks from being accidentally run as a check.

**Comment by dinger1986** [comment]
I had also thought it would be good to search scripts as the list gets longer and maybe even favourite them?

**Comment by wh1te909** [comment]
great points will work on it!

**Comment by wh1te909** [comment]
released in 0.2.19
