### ISSUE TITLE
Update Demo

### ISSUE THREAD

**Issue by MalteKiefer** [wh1te909/tacticalrmm#855]
Hello,

is it possible that you update the demo to the latest version?

Thanks

**Comment by dinger1986** [comment]
It will be updated, we are waiting for big gui changes before updating

**Comment by MalteKiefer** [comment]
What are the big GUI changes?

**Comment by dinger1986** [comment]
Reporting etc

**Comment by silversword411** [comment]
The demo is a franken-beast, and difficult to update because of the nature of TRMM. It'll be updated at some point...but you can set it up your own fully functional server in less than 15mins. Going to close this issue.

**Comment by wh1te909** [comment]
demo site has been updated
