### ISSUE TITLE
Under agent history tab | Search not matching items

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#859]
Shouldn't that "defe" search give the defender results? See pic

![2021-12-13_015121 - trmm history search bug](https://user-images.githubusercontent.com/13395348/145765673-da1b24a4-ba46-4a88-96b5-41e96200ea7e.png)

**Comment by bc24fl** [comment]
It appears to be searching on the action column.

**Comment by silversword411** [comment]
Search is only matching the "Initiated by" column, I'm expecting it to se3arch in script/command names
