### ISSUE TITLE
Task applied by automation policy on server not removed on policy

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#864]
0.10.4

**Installation Method:**
  - [x] Standard

**Describe the bug**

**To Reproduce**
Create automation policy that is enabled.
Add 1 task
Open task scheduler on server (tested with 2012)
edit server in trmm, assign automation policy to agent.
See task create
remove automation policy from agent.

Bug
Policy isn't deleted from scheduled tasks on machine

**Comment by silversword411** [comment]
...maybe it does delete, just takes longer?

I'm so used to trigger command...everything happens within 10 seconds.

**Comment by silversword411** [comment]
Just takes longer....nevermind. So used to thing happening in 2 seconds. Takes about 3-5mins to update ;)

**Comment by bbrendon** [comment]
I was just looking to see if this issue was opened and after waiting a bit longer it finally cleared up.
