### ISSUE TITLE
Editing task triggers a date format error "Datetime has wrong format"

### ISSUE THREAD

**Issue by orugari** [wh1te909/tacticalrmm#865]
**Server Info (please complete the following information):**
 - OS: [Debian 10]
 - Browser: [chrome]
 - RMM Version (0.10.4):

**Installation Method:**
  - Standard

**Describe the bug**
Unable to edit a Task, trigger a date format error, even if it is not possible to setup a new date. 
run_time_date: Datetime has wrong format. Use one of these formats instead: YYYY-MM-DDThh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z].
400: Bad Request

**To Reproduce**
1. Create a new task
2. Add a date using icons (day and time)
3. Save
4. Right click on the task, Edit, save.

**Expected behavior**
Saving change.

**Comment by silversword411** [comment]
Confirmed, this will be changing soon though so fix is imminent.

![2021-12-14_111743 - trmm editing task error](https://user-images.githubusercontent.com/13395348/146037214-a125f0db-c3f6-4ee4-a487-47431a7120e8.png)

**Comment by wh1te909** [comment]
already fixed in latest release
