### ISSUE TITLE
Feature request: LDAP Authentication

### ISSUE THREAD

**Issue by adamjrberry** [wh1te909/tacticalrmm#868]
It would be great in a future release if admins could log in with LDAP credentials, and have the accounts auto provision based on group membership. i.e. if I add a user into the 'TRMM Admin' group in AD then they can then log into TRMM.

**Comment by dinger1986** [comment]
duplicate request, please search before adding request.

#508

**Comment by adamjrberry** [comment]
Apologies, will do!
