### ISSUE TITLE
Disk Space Check w/o drive letter dependency

### ISSUE THREAD

**Issue by DigitekSolutions** [wh1te909/tacticalrmm#869]
In other RMM systems you can set you policy to do disk space checks based on if the volume is a "system drive" or "All other drives". This makes monitoring one off volumes automatic by policy instead of having to manually add a check because the computer has a drive letter that is not standard. 

Example of adding drive monitoring via policy in SyncroMSP
![image](https://user-images.githubusercontent.com/93954536/146256367-3b661bf2-cf0a-4d87-a3af-26b2e2780ffe.png)

**Comment by dinger1986** [comment]
This is handled by a community script, there is already one in the works to include volumes without letters.

Scripts channel on discord is where to discuss scripts 

Regards,
