### ISSUE TITLE
Feature Request - Ability to sort Locations within Clients (alpha or manual?)

### ISSUE THREAD

**Issue by rtwright68** [wh1te909/tacticalrmm#87]
Not a big deal, but would be nice to be able to sort the location within a client. Either alpha or manual if possible?
Thanks!

**Comment by wh1te909** [comment]
Should already be possible, hover your mouse over the "Site" label and you should see an arrow, click on it and it will change directions and sorts alphabetically

![sortsite](https://user-images.githubusercontent.com/7434746/91754090-b0ed4300-eb7d-11ea-9998-0f343007248f.png)

**Comment by rtwright68** [comment]
Ahh, thanks.  I was mainly thinking of the far left list.  Under the Site, the locations there.  They are listed in the order they were created.

**Comment by wh1te909** [comment]
ha sorry got it, fixed in dbf9c30abe704ff3d6d2fc9c8bd4c6cb569155e2 will sort alphabetically now

**Comment by rtwright68** [comment]
Thanks much!
