### ISSUE TITLE
Summary Tab - Customize

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#870]
Would be great to be able to customize the data on the summary tab.(f.ex from Custom Fields?) 
I think both installation date for the windows os (or somehow the age of the computer) and also the serial number itself would be great to show on the summary tab.

**Comment by silversword411** [comment]
You already have an existing issue about summary tab customization. 
https://github.com/wh1te909/tacticalrmm/issues/605

Closing this one
