### ISSUE TITLE
Initial screen after install support x32 and x64 mesh agents

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#876]
Have 1st screen in rmm admin gui on new server install support x32 and x64 mesh agent uploads.

**Comment by dinger1986** [comment]
Optionally support 32 and 64 upload I would suggest as some won't need both.

**Comment by silversword411** [comment]
Looks like it's in here :) 

https://github.com/wh1te909/tacticalrmm/blob/develop/web/src/views/InitialSetup.vue

Hmmm...maybe I'll be able to do this one if it doesn't get too complex ;)

**Comment by wh1te909** [comment]
the "upload mesh agents" is going away not needed anymore we will be dynamically downloading mesh agent during tactical agent install
