### ISSUE TITLE
Feature Request: Event Log Check, Filter Source and/or Details

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#88]
Would it be possible to update the Event Log check to also take the event source and/or possibly even a string in the details in to consideration when running the check.
Some event id's belong to multiple sources and can trigger false alerts if just checking for a specific event id.

E.G. Event ID 5 belongs to VDS Basic Provider, IsolatedUserMode and Hyper-V-VmSwitch and not all of these need to be alerted when detected.

**Comment by wh1te909** [comment]
will do! I am making big changes to how checks work on the agent, right now the status of pass/fail is being calculated agent side but instead will be sending the raw data to the RMM and calculate it there, this way have more flexibility in determining status and not having to release a new agent for a new request like this so can implement alot faster.
