### ISSUE TITLE
Export table as csv feature is not working version v0.10.5

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#895]
### Discussed in https://github.com/wh1te909/tacticalrmm/discussions/891

<div type='discussions-op-text'>

<sup>Originally posted by **multispeed** December 22, 2021</sup>
Hi,

I would like to export a CSV from all the software installed on a particular system, but the blue export button isn't providing me with a csv. i Then tried the button on another page (debug) and the button isn't working there either.

I could find any other issue in Discussions or a clue why it isn't working in the Documentation.</div>

**Comment by wh1te909** [comment]
@multispeed this is fixed, will be in next release
