### ISSUE TITLE
{{agent.local_ip}} returns None

### ISSUE THREAD

**Issue by DavidAamcomp** [wh1te909/tacticalrmm#896]
**Server Info (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Browser: [firefox]
 - RMM Version (as shown in top left of web UI):0.10.5

**Installation Method:**
  - [*] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):Agent v1.7.2
- Agent OS: Windows 10 Pro, 64 bit v21H2 (build 19044.1415

**Describe the bug**

When entering {{agent.local_ip}} in the script arguments, the variable returns None

test script :

param (
   [string] $PrivateIp
)

Write-Output "Private IP: $PrivateIp"

Script Arguments :

-PrivateIP {{agent.local_ip}}

Script Output:

Private IP: None

**To Reproduce**
1. Go to script manager
2. Run Test script

**Expected behavior**
{{agent.local_ip}} to return local ip address

**Comment by wh1te909** [comment]
that field is deprecated see https://github.com/wh1te909/tacticalrmm/blob/196aaa5427bab90a32474940ed0e0e8b7d2e47ad/api/tacticalrmm/agents/models.py#L38

you can use `{{agent.local_ips}}` instead: https://github.com/wh1te909/tacticalrmm/blob/196aaa5427bab90a32474940ed0e0e8b7d2e47ad/api/tacticalrmm/agents/models.py#L229

**Comment by DavidAamcomp** [comment]
Gotcha, Thank you!

also,
Documentation at 
https://wh1te909.github.io/tacticalrmm/script_variables/
shows {{agent.local_ip}}

**Comment by wh1te909** [comment]
ah thanks, re-opening until docs are updated so i don't forget
