### ISSUE TITLE
Additional Users to Tie Into Mesh Central

### ISSUE THREAD

**Issue by jacksonsystems** [wh1te909/tacticalrmm#897]
At present TRMM uses one accoun in Global Settings > Mesh Central.

It would be handy if another account could be set up per TRMM User. At the moment only one mesh account can be used for all TRMM users.
For auditing sake, this makes it messy to find out who has accessed what. A seperate mesh login per user would be easier to audit and check logs. 

For example, I log into TRMM as tech1, my Mesh Settings in Global Settings are Username and Password for tech1. My engineer may log in as tech2, this would require a user account in mesh to match tech2 added to the Global Settings > Mesh Central for that user.

**Comment by dinger1986** [comment]
please add comments to #182 

closing as duplicate
