### ISSUE TITLE
Feature Request: All Clients Server and Workstation Policy

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#90]
Can the All Clients section be enabled to assign policies.

I currently have a check that runs and renames the Add/Remove Programs entry to My Company RMM Agent instead of the default as customers were querying the new software that was showing up on their PC, it would be good to be able to assign this check to All Clients once and just know it's doing its thing.

Code for anyone else wanting it:
`$NewAgentName = "My Company RMM Agent"

$AgentName = (Get-ItemProperty "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{0D34D278-5FAF-4159-A4A0-4E2D2C08139D}_is1").DisplayName
if ($AgentName -eq "Tactical RMM Agent") {
    Set-ItemProperty -Name DisplayName -Path "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{0D34D278-5FAF-4159-A4A0-4E2D2C08139D}_is1" -Value $NewAgentName
    $AgentName = (Get-ItemProperty "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{0D34D278-5FAF-4159-A4A0-4E2D2C08139D}_is1").DisplayName
    if ($AgentName -ne $NewAgentName) {
        exit 1
    } else {
        exit 0
    }
}`

**Comment by dinger1986** [comment]
Great idea!! Maybe worth having a customisation setting in the GUI and from there can apply this to all agents at the same time. Then also be able to change the logo and branding on tactical to your own?

**Comment by wh1te909** [comment]
@dinger1986 I have always planned to eventually make this rmm custom branded which should be pretty easy to do for the web part, I can just add a section in global settings for company name and remove all hardcoded instances of 'Tactical RMM'. 

For the agent you would need to build it yourself though, which is pretty simple and would just have to edit the setup.iss file and just change "Tactical RMM Agent" to your company name, and for the icon just replace 'onit.ico' in the 'bin' folder with your own icon and then just follow the instructions to build on the agent's readme.

I also do plan on adding batch agent targeting like being able to send a command or run a script on more than 1 agent, either every single agent or filtering by client / site, I should have this done soon cuz it's extremely simple to implement just need to add the frontend for it.

As for adding a policy for all clients I'm hoping it should be pretty simple right @sadnub ? Maybe just have a built in global policy that will just target every single agent.

@bradhawkins85 are you able to make the script take the company name as a parameter and then submit a PR with it so we can add it to the 'Community Scripts' repository so will show up in script manager for everyone? You can just add the script to the 'scripts' folder in the root of this project where all the other powershell scripts are, and then edit this file https://github.com/wh1te909/tacticalrmm/blob/develop/api/tacticalrmm/scripts/community_scripts.json
and follow the format and add a section with your script in there with name description etc

**Comment by sadnub** [comment]
Should be able to create a default policy in the settings. Any conflicting checks applied to client, site or agent would override it. I'll see about adding this.

**Comment by sadnub** [comment]
#100 Should added default policies in the settings that will apply to all agents.
