### ISSUE TITLE
Allow configuration of MeshCentral SMTP settings in Docker

### ISSUE THREAD

**Issue by joeldeteves** [wh1te909/tacticalrmm#916]
**Is your feature request related to a problem? Please describe.**
The MeshCentral config gets overwritten each time the Docker container is restarted. This is fine, but the current entrypoint script does not allow configuration of SMTP settings.

**Describe the solution you'd like**
Add SMTP variables + config to the tactical-meshcentral container entrypoint script

**Describe alternatives you've considered**
- Using an init container to edit the config or mounting the config as a volume (both are messy)
 
**Additional context**
See https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.9.pdf for more info

**Comment by silversword411** [comment]
Ignore me...brain was somewhere else. Meant to hit done on notification. #DontDayDreamAndClearNotificationStreamAtTheSameTime

**Comment by sadnub** [comment]
You can use the MESH_PERSISTEN_CONFIG=1 option in the mesh container to avoid the mesh config being overwritten

**Comment by joeldeteves** [comment]
Hi @sadnub, it would be nice to have these variables configurable through the Docker environment. Do you mind keeping this one open? I'm happy to work on it and add another PR when I have time.

**Comment by sadnub** [comment]
Yeah no problem! Can just add the variables at the top of the mesh container entrypoint

**Comment by wh1te909** [comment]
merged
