### ISSUE TITLE
Remote reboot not working after update to 0.11.2

### ISSUE THREAD

**Issue by bvessey** [wh1te909/tacticalrmm#933]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Tried with Chrome & Firefox, assume all browsers same behavior
 - RMM Version (as shown in top left of web UI): 0.11.2

**Installation Method:**
  - [X ] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.8.0
- Agent OS: Windows 10 Enterprise, 64 bit v1909 (build 18363.1977) • Agent v1.8.0 || Windows 10 Enterprise, 64 bit v1909 (build 18363.2037) • Agent v1.8.0

**Describe the bug**
I am no longer able to invoke / trigger a reboot of the client PC from the context / actions menu in TacticalRMM's web interface.

**To Reproduce**
1 - Right-click on asset
2 - Select Reboot > Now from Menu
3 - Observe nothing happening on client device...

**Expected behavior**
Previously this would trigger a reboot of the remote asset within 10 seconds or so.

**Screenshots**

**Additional context**

**Comment by bvessey** [comment]
Additional info:

Just attempted to schedule the reboot and it returns the following error:
![image](https://user-images.githubusercontent.com/23658345/149387792-a3647044-2257-4ff5-8a0c-d30730b3d6b4.png)

**Comment by bvessey** [comment]
Forgot to mention, am using hardening instructions from docs 
https://wh1te909.github.io/tacticalrmm/securing_nginx/

Had to comment out server_names_hash_bucket_size 256; in /etc/nginx/conf.d/botblocker-nginx-settings.conf as it was indicating that the directive was duplicated.

**Comment by bvessey** [comment]
Perfect, Thanks !

**Comment by wh1te909** [comment]
released in 0.11.3
