### ISSUE TITLE
RMM Agent failing to report back on windows terminal servers

### ISSUE THREAD

**Issue by Sneakypotatoo** [wh1te909/tacticalrmm#946]
**Server Info (please complete the following information):**
 - OS: Server 2016+
 - Browser: [e.g. chrome, safari]
 - RMM Version (0.11.3):

**Installation Method:**
  - [ ] Standard
  - [X ] Docker

**Agent Info (please complete the following information):**
- Agent version 1.8.0:
- Agent OS: Win Server 2016/2019

**Describe the bug**
RMM Agent failing to report back to RMM server when terminal services role is installed/rdp gateway

**To Reproduce**
Install rdpgateway/terminal services roles and rmm client

**Expected behavior**
Client to report back status of server

**Comment by bradhawkins85** [comment]
Can you try the following from an elevated command prompt on the RDS server.

net stop tacticalagent
"c:\Program Files\TacticalAgent\tacticalrmm.exe" -m winagentsvc -log debug -logto stdout
net start tacticalagent

Best way to troubleshoot these issues is via the Discord support channel.  https://discord.gg/upGTkWp

You will want to remove the tokens from the output and post the results in Discord. If there is an issue discovered with the agent then a github issue will be used to track the resolution of the issue.

**Comment by Sneakypotatoo** [comment]
already sent the logs to wh1te909

**Comment by technoicon** [comment]
Hi,

Turns out this was the Antivirus blocking something.  The AV had no reports and no av blocking but once removed everything starting working as expected.

**Comment by wh1te909** [comment]
thanks for the update
