### ISSUE TITLE
Feature Request: Support internal CA

### ISSUE THREAD

**Issue by meyerje** [wh1te909/tacticalrmm#95]
We are deploying this behind a firewall and VPN using our domain certificate authority.  To enable this I made the below modifications to the install script and am wondering if these can be leveraged moving forward with install.sh and update.sh?

Change line 101 to =true to force BEHIND_NAT (probably not necessary)
`BEHIND_NAT=true`

Comment out lines 122 - 126 to bypass Lets Encrypt
```
#sudo certbot certonly --manual -d *.${rootdomain} --agree-tos --no-bootstrap --manual-public-ip-logging-ok --preferred-challenges dns -m ${letsemail} --no-eff-email
#while [[ $? -ne 0 ]]
#do
#sudo certbot certonly --manual -d *.${rootdomain} --agree-tos --no-bootstrap --manual-public-ip-logging-ok --preferred-challenges dns -m ${letsemail} --no-eff-email
#done
```

And then changed each section of the nginx configurations to point to the certificates we got from our CA for the server.  The certificates must be staged before running the installer script.  Replace each instance of:

```
ssl_certificate /etc/letsencrypt/live/${rootdomain}/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/${rootdomain}/privkey.pem;
```

With:

```
ssl_certificate /etc/ssl/certs/caissued.pem;
ssl_certificate_key /etc/ssl/private/privkey.pem;
```

**Comment by sadnub** [comment]
@wh1te909 I was thinking more about this and we can allow updating certificates through the UI. We could also allow completing the letsencrypt setup in the UI as well. The reverse proxy can just fallback to self-signed certs if none are present. Let me know if this sounds good and I can implement it.

**Comment by meyerje** [comment]
That'd be great.  I noticed the four Let's Encrypt lines in the install.sh file will loop indefinitely if the commands fail so we may have to account for at least that.

**Comment by sadnub** [comment]
@meyerje I added #140 to remove the Let's Encrypt dependency from the install script. If you opt out of Let's Encrypt, it will create a self signed certificate. You can replace the self-signed certificate with your internal CA certs and restart nginx. I added a section to the readme also.

**Comment by wh1te909** [comment]
merged
