### ISSUE TITLE
Server Side Checks

### ISSUE THREAD

**Issue by daveclev12** [wh1te909/tacticalrmm#954]
**Is your feature request related to a problem? Please describe.**
We sometimes need to monitor externally hosted services and cannot install an agent

**Describe the solution you'd like**
I would really like if the RMM server itself could carry out some very basic checks similar to the agents. i.e. ping checks, website availability checks (check for status 200) etc. This would be helpful as sometimes we monitor externally hosted services such as web servers, mail servers and VPN gateways where we cannot install an agent

Love this software! Keep up the good work!

**Comment by wh1te909** [comment]
this will be possible once linux agent is released

**Comment by dinger1986** [comment]
Was just about to say similar. Will be able to all this and more, could even have another vps doing the checks save load on your server (I mean you could already using a windows server but yuck lol).

**Comment by daveclev12** [comment]
That sounds great! Is there an estimate on the Linux agent release?

**Comment by wh1te909** [comment]
no exact ETA but it's actively being worked on and my priority atm before any other new features
