### ISSUE TITLE
400: Bad Request when trying to connect to agent

### ISSUE THREAD

**Issue by anauv** [wh1te909/tacticalrmm#955]
**Server Info (please complete the following information):**
 - Bhyve virtual OS: Ubuntu 20.04.3 LTS (newest upgrades done with apt upgrade, didn't help)
 - Hypervisor: FreeBSD 13.0 with bhyve (without firewall)
 - Browser: Chrome, Firefox and Edge
 - RMM Version (as shown in top left of web UI): v0.11.3 (./update.sh --force done, didn't help)

**Installation Method:**
  - [ X ] Standard

**Agent Info (please complete the following information):**
- Agent version: v1.8.0
- Agent OS: Windows 10 Pro, 64 bit v20H2 (build 19042.1288)

**Describe the bug**
Can't connect to agent out of nowhere on another day.

**To Reproduce**
1. Go to the RMM website
2. Right-click on Agent and select Take Control
3. Wait for the page to load, at the moment Connect is greyed out.
4. Click on Restart Connection 
4. See error: "The specified service does not exist as an installed service. 400: Bad Request"

**Expected behavior**
Expected to see and control the screen of the agent

**Screenshots**
![image](https://user-images.githubusercontent.com/98519849/151330687-0cce12de-84ce-4d3c-8ee0-797c360930da.png)

**Comment by anauv** [comment]
Just ran forced update again and now I got this error, but after that the script ran without errors:
chown: cannot access '/home/tactical/.config': No such file or directory

**Comment by silversword411** [comment]
This sounds like a support issue, probably a problem with connection between agent/server or mesh service not running. Please use discord support channel.

https://discord.gg/upGTkWp

Closing this issue, will reopen if there's actually a bug that needs fixing
