### ISSUE TITLE
You can delete scripts with active tasks and checks

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#957]
1. Create script
2. Create task and/or check on agent using script
3. Delete script

It should stop you from deleting script if it's assigned, or going to have problems with tasks later.
Or, even better check: If script in use somewhere give the option to remove from all locations at script deletion time. 

Probably need to be able to find where the script is allocated when you do want to delete (like Show Relations in Automation Manager).

**Comment by sadnub** [comment]
Will be fixed in the next release. Check were already being deleted if the script was. Tasks will self-delete the task if it is unable to find it when running now.
