### ISSUE TITLE
Bug: Microsoft Defender ATP Malware detection Trojan:Win32/Fuery.C!cl

### ISSUE THREAD

**Issue by ArmandusNereus** [wh1te909/tacticalrmm#96]
Microsoft Defender ATP shows the winagent-v0.10.2.exe as Trojan.
Probably a false positive but nice to fix.

[https://imgur.com/KO58TkX](url)

[tacticalrmm-virus.pdf](https://github.com/wh1te909/tacticalrmm/files/5194888/tacticalrmm-virus.pdf)

**Comment by wh1te909** [comment]
Lol yea obv it's a false positive but I understand why AV picks it up, it basically is a legal virus xD.

Nothing I can do without code signing the executable which I cannot afford to pay the yearly fee and even then I would have to contact all the AV companies and get it whitelisted. MeshCentral pays to code sign their executable and they still have issues with AV flagging it...

So you'll need to add it to AV exceptions, I had to as well on all my machines.
Whitelist these 3 dirs
C:\salt
C:\Program Files\Mesh Agent
C:\Program Files\TacticalAgent
