### ISSUE TITLE
Agent error connectex

### ISSUE THREAD

**Issue by iarellano24** [wh1te909/tacticalrmm#963]
Hi, i have an error with agent when i install it on windows 10.

**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: ALL
 - RMM Version (as shown in top left of web UI): 0.11.3

**Installation Method:**
  - [*] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): None
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2]: WIN 10

**Describe the bug**
I downloaded the agent from the platform frontend, but I can't install the app on any device. I followed the instructions in the official documentation without making any mistakes in DNS and domains or opening ports.

**Screenshots**
CMD:
![cmd](https://user-images.githubusercontent.com/97777593/152035093-0d19e3b9-4c62-45e9-916f-b6dccfa6ba7e.PNG)

ERROR:
![error_cmd](https://user-images.githubusercontent.com/97777593/152035103-8389097f-a9f0-4488-91d6-0b4a8e8b85e0.png)

**Comment by dinger1986** [comment]
Please fill in some information about the issue you are having

**Comment by iarellano24** [comment]
> Please fill in some information about the issue you are having although most likely this is a support issue so might be better on GitHub discussions or #support on discord

Sorry now is ok.

**Comment by dinger1986** [comment]
can you try these commands

https://wh1te909.github.io/tacticalrmm/troubleshooting/#testing-network-connectivity-between-agent-and-server

**Comment by iarellano24** [comment]
Ok, i try. 
only port 4222 throws me an error.

![image](https://user-images.githubusercontent.com/97777593/152054102-7fc2c267-9352-4771-824d-945cb2983f43.png)

server:

![image](https://user-images.githubusercontent.com/97777593/152053957-969996ac-86a8-4f87-9b6d-04bf03e0c748.png)

**Comment by dinger1986** [comment]
Ok and if you ping that dns address do you get a reply?

**Comment by wh1te909** [comment]
please also paste the output of this command:
```
sudo systemctl status nats.service
```

**Comment by iarellano24** [comment]
> Ok and if you ping that dns address do you get a reply?
Ping works.

![image](https://user-images.githubusercontent.com/97777593/152054454-4847519a-a127-4259-9a64-3a1751d02df0.png)

**Comment by iarellano24** [comment]
> sudo systemctl status nats.service

![image](https://user-images.githubusercontent.com/97777593/152054600-89fadf07-930e-4c0f-976a-f9bd7932b490.png)

**Comment by dinger1986** [comment]
Have you opened port 4222?

**Comment by dinger1986** [comment]
Are you using custom ssl?

**Comment by iarellano24** [comment]
> Have you opened port 4222?

Yest. Its open.

> Are you using custom ssl?

Nop, it was a clean install. but after installation, all links show an ssl error anyway. 

![image](https://user-images.githubusercontent.com/97777593/152055278-c1aa51be-94a4-4d79-b53f-26ba7165eb89.png)

**Comment by dinger1986** [comment]
Ok so it's not working then.

Did you verify the TXT record? It looks like it failed.

**Comment by iarellano24** [comment]
> Ok so it's not working then.
> 
> Did you verify the TXT record? It looks like it failed.

Yes. We add the txt record and it works.

Thanks a @wh1te909 in this thread, we know that the nats.service is stopped, so we understand that the problem may be there. We already restarted the nats.service but the problem persists. So what can we do? 

We try solve this with docs, but when we try get output using this line 

nats-server -DVV -c /rmm/api/tacticalrmm/nats-rmm.conf

we have this result:

![image](https://user-images.githubusercontent.com/97777593/152056938-d75cd894-034c-4e36-b4c4-814dcbb20a1e.png)

**Comment by wh1te909** [comment]
`rms.above.cl` is that your subdomain or root domain?

**Comment by dinger1986** [comment]
Nats doesn't work without a genuine SSL certificate and yours doesn't appear to have installed properly.

**Comment by dinger1986** [comment]
If you click on the ssl error and show the cert details that would be helpful

**Comment by silversword411** [comment]
Looks like you're using cloudflare, you know you can't proxy nats right?

https://wh1te909.github.io/tacticalrmm/troubleshooting/#using-cloudflare-dns

**Comment by dinger1986** [comment]
> Looks like you're using cloudflare, you know you can't proxy nats right?
> 
> 
> 
> https://wh1te909.github.io/tacticalrmm/troubleshooting/#using-cloudflare-dns
> 
> 

But SSL isn't working anyway, maybe it's proxied so should be using cloudflare SSL

**Comment by silversword411** [comment]
From public looks ok. Must be something else going on in the network from their screenshots

![2022-02-01_170836 - brave_Certificate](https://user-images.githubusercontent.com/13395348/152059769-6d0065de-c5d9-41b0-88c3-dacfc265a3a8.png)

**Comment by dinger1986** [comment]
The url is api.rms.above.cl for api

**Comment by iarellano24** [comment]
@silversword411 @dinger1986 @wh1te909 
Ok, the ssl issue was fixed.
The error occurs because the "Nginx Full" ports were not enabled in the execution of the script, for this reason it was not possible to verify the SSL configuration, however, the nats.service problem continues.

@silversword411 the cloudflare configuration is the same as in the documentation.

**Comment by dinger1986** [comment]
So is your api record? api.rms.above.cl?

**Comment by silversword411** [comment]
> The error occurs because the "Nginx Full" ports were not enabled in the execution of the script, for this reason it was not possible to verify the SSL configuration, however, the nats.service problem continues.

Sounds like you're running a proxy. You should discuss in the discord #unsupported channel
https://discord.gg/bHcCxEfCnV

**Comment by silversword411** [comment]
Looks like LE certs are in nginx, just not loaded in nats

![2022-02-01_172109 - brave_Certificate](https://user-images.githubusercontent.com/13395348/152061290-1caa1d3e-1e5c-434f-a7e4-25d868b829a3.png)

`update --force` run to make sure certs are everywhere?

**Comment by dinger1986** [comment]
What's the folder under /etc/letsencrypt/live? I'm guessing it's not /etc/letsencrypt/live/rms.above.cl?

**Comment by silversword411** [comment]
Post if there are issues still, I think you may have found your problem
