### ISSUE TITLE
Feature Request: Allow the ability to sync agent tasks

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#97]
When removing a task from a policy the task is not removed from the agents.
Removing a policy from a client/site does not remove the tasks from the agents.

**Comment by sadnub** [comment]
@bradhawkins85 Thanks for bringing this up. I will need to rework the task deletion since it tries once to delete the task(s) from the agents then deletes the task from the UI. I think I can add a pending_deletion field to the task and check this once the agent checks in, so that offline agents will eventually get the tasks cleaned up. I will work on this.

**Comment by bradhawkins85** [comment]
thanks @sadnub 
I was actually meaning that the tasks were not removing from the webui but it appears they just took a while.
pending_deletion would be good though if the agents are not removing the scheduled tasks due to being offline.

Is there a way we can clean up scheduled tasks as part of this fix to tidy up old tasks that did not get removed previously?

**Comment by sadnub** [comment]
When checks and tasks are modified, a background task is fired off to perform the action, so the UI can return a response faster. If there are a large number of agents affected it could take a little bit for the affected checks and tasks to get deleted/created. 

For cleaning up orphaned tasks on the agent that might get tricky. I could try and create a python script to compare the agent tasks and the UI and delete if it doesn't have a reference. I will have to test that.

I do have a fix for the orphaned tasks implemented, but I need to do more testing. Should be this evening.

**Comment by sadnub** [comment]
#100 Adds the reliable task edits on the agent. Still working on cleanup for existing agents

**Comment by sadnub** [comment]
I was thinking about this more and it might be beneficial to have a sync tasks agent command. This will help if a task gets deleted from the agent on accident.

**Comment by bradhawkins85** [comment]
@sadnub sounds like a brilliant idea.
The task could remove all tactical rmm tasks and re-create them that would handle the clean up as well.

**Comment by sadnub** [comment]
@bradhawkins85 I just added a PR with adds command to remove tasks on agents that are already removed from the UI. You can run `python manage.py remove_orphaned_tasks` on the server and it will cycle through all agents.

**Comment by bradhawkins85** [comment]
Thank you @sadnub will give it a run once the PR is merged.

**Comment by bradhawkins85** [comment]
@sadnub i'm getting an error when running the script:
I only have python3 not python so not sure if this is the issue.

tactical@tactical:/rmm/api/tacticalrmm$ python3 manage.py remove_orphaned_tasks
Traceback (most recent call last):
  File "manage.py", line 10, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 12, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

**Comment by wh1te909** [comment]
you have to activate the python virtual environment first
```
cd /rmm/api/tacticalrmm/
source ../env/bin/activate
python manage.py remove_orphaned_tasks
```
