### ISSUE TITLE
Agent v0.1.0

### ISSUE THREAD

**Issue by Cr7chton** [wh1te909/tacticalrmm#970]
**Server Info (please complete the following information):**
 - OS: Linux raspberrypi 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux
 - Browser: chrome
 - RMM Version 0.11.3

**Installation Method:**
  - [X] Standard 
 

**Agent Info 
- Agent version : 1.8.0 or 0.1.0 ??
- Agent OS:  Win 10 v21h2, 
- 
**Describe the bug**
Sur une installation propre je suis bloquer avec l'agent en version 0.1.0 à l'affichage pour l'ensemble des postes. 
J'ai mit à jour vers l'agent 1.8, pas d'erreur et je reste avec cette affichage.
Mis a jour via [https://github.com/wh1te909/rmmagent/releases](https://github.com/wh1te909/rmmagent/releases ).  pas de changement.

Google traduction :
On a clean installation I am blocked with the agent in version 0.1.0 on display for all workstations. I updated to agent 1.8, no error and I stay with this display. Updated via [https://github.com/wh1te909/rmmagent/releases](https://github.com/wh1te909/rmmagent/releases). no change

**Expected behavior**

**Screenshots**
![Capture d’écran 2022-02-11 162743](https://user-images.githubusercontent.com/99492744/153621112-5bd0a576-3680-4773-a800-d1f5232c7a22.png)

**Additional context**

**Comment by silversword411** [comment]
You AV has probably killed and eaten the agent. 

This is support, please use Discord for support matters. 

https://discord.gg/upGTkWp

Going to close this issue.
