### ISSUE TITLE
Automation Policies wont apply

### ISSUE THREAD

**Issue by guillaumebottollier** [wh1te909/tacticalrmm#977]
**Server Info (please complete the following information):**
 - OS: Debian 10
 - Browser: chrome/firefox
 - RMM Version (as shown in top left of web UI): 0.11.3

**Installation Method:**
  - [X] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.8.0
- Agent OS: Win10

**Describe the bug**
Hello,
Since upgraded to 0.11.3 automation policies does not applied anymore to agents.
i try to remove the policy, this will wype all the tasks and checks on agents correctly.
then i do all the server maintenances, restart the whole machine
but still the same : assignement of Automation policy has no effect on agents

**To Reproduce**
apply an automation policy to a client or site, no checks and no task will appear on agents

**Expected behavior**
application of policies build in the automation manager

**Screenshots**

**Additional context**

**Comment by kmcclainmt** [comment]
Same Issue:

All the way from Global Settings to applying a policy directly to an asset, the asset is not inheriting any Checks or Tasks. Rebooted VM to test and all ran all server maintenance tasks.

**Comment by wh1te909** [comment]
can you all please paste output of `redis-server --version` and `cat /etc/*release*` thanks

**Comment by guillaumebottollier** [comment]
Hello Dan, here are the outputs : 

`redis-server --version
Redis server v=5.0.3 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=94145a25ce04923
`
`
cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
`
Thank's for investigate on this.

**Comment by wh1te909** [comment]
thanks. so far am unable to reproduce. 
can you provide steps to reproduce from a blank state. 
see below gif. might be easier for you to screen record the steps like I did here
https://imgur.com/M8YYhSF

**Comment by guillaumebottollier** [comment]
mmm problem seems to be more tricky, i create a new client/site with a new agent, and assignement of a newly created automation policy test works.
But it doesn't work on a site containing 100 agents, some online some offline, with the same automation policy test.

**Comment by guillaumebottollier** [comment]
mmm problem seems to be more tricky, i create a new client/site with a new agent, and assignement of a newly created automation policy test works.
But it does partially works on a site containing 100 agents, some online some offline, with the same automation policy test.
the numbers of agents in the site seems to really impact.
I recreat my policy from scratch and applied on this 100 agents site, and i have duplicated tasks :

![image](https://user-images.githubusercontent.com/84961534/154761347-b287a2f3-e161-47e9-b874-1829c1e113b2.png)

**Comment by wh1te909** [comment]
ok can you still record yourself creating the policy and we will test with a couple hundred agents
but need to see how you are creating the policy/checks/tasks etc and all their settings

**Comment by silversword411** [comment]
You're only getting partial duplication of tasks...there was an old bug with old version that had this issue. Also have you checked all your automation policies and confirmed you're not applying multiple policies at the different levels: default TRMM workstation, client, site, agent.

Remove all your policies and make sure agents see all policies unapplied (resync if necessary - and wait/confirm it applies if you're applying to hundreds of agents)

Your screenshot also cut off

![2022-02-21_113539 - trmm policies](https://user-images.githubusercontent.com/13395348/154995617-f4d6dc19-325a-4cb0-8ebd-e4faf9a34bd1.png)

**Comment by DavidAamcomp** [comment]
Same thing is happening to me.  

New clients are not applying the default Server,Workstation policy.
I am unable to add the policty manually with right click on server.
I've restarted the VM.

`Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=636cde3b5c7a3923`

`DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal`

**Comment by guillaumebottollier** [comment]
Hello
after 1. clean all the automation policies on the impacted site/client 2. recreate the policy from srcatch 3. apply the new policy
this seems to be better, but i still have task that never runs, agent that never updates...

![image](https://user-images.githubusercontent.com/84961534/155160179-1c52bd26-1b5e-4b7d-afb6-798073016e21.png)

**Comment by silversword411** [comment]
> but i still have task that never runs, agent that never updates...

I had a VERY small number (like 4) that wouldn't update to 1.8.0 (they were frequently offline/rarely rebooted). Please provide debug logs of problems, with more details. 

I think I just workaround it by uninstalling and then reinstalling.

**Comment by volkjohn** [comment]
A scheduled task for my automation policy looked like it was being run on agents that have had the agent installed for over 2 months, but the output of the scheduled task was showing that nothing was being run. On agents that had just been recently added to tacticalrmm (younger than 2 months), the scheduled task would modulate between "Waiting for task creation on agent" and something about waiting for next agent check-in.

I ended up creating a new automation policy with a new scheduled task and the scheduled task is now running correctly on all agents.

I dug into the autotasks_automatedtask table in postgres. It looks like initial scheduled task (Update All Chocolatey Apps) I setup last year now has an empty actions field, simply showing {}. The previous failed scheduled tasks, if they ran at all on agents, all have an empty actions field as well.

There are minute differences in the scheduled task that I created last year and the new one I created today. I am attaching the two scheduled tasks.

Thank you @wh1te909 and all other contributors for your work on tacticalrmm!

[autotasks_EmptyActions.csv](https://github.com/wh1te909/tacticalrmm/files/8187789/autotasks_EmptyActions.csv)

**Comment by silversword411** [comment]
Sounds like this is a closed issue? Post if it needs re-opening

**Comment by schmm** [comment]
Tasks are never applied. The status always remains on "Waiting for task creation on agent"
![Tactical_RMM_-_2023-03-16_12 17 38](https://user-images.githubusercontent.com/92079487/225601296-80ea0bc0-c73b-4d95-9685-218ad8d5f711.png)

**Comment by schmm** [comment]
up to date and online

**Comment by schmm** [comment]
[https://discord.com/channels/736478043522072608/1006426744267477053/threads/1069354059921899520](url)

and

wget -N https://raw.githubusercontent.com/amidaware/tacticalrmm/master/update.sh
./update.sh --force

solved my problem

**Comment by schmm** [comment]
![Tactical_RMM_-_2023-03-17_14 38 50](https://user-images.githubusercontent.com/92079487/225920853-e1c2e5a0-454b-46b7-893d-5ecf664319a1.png)
???

**Comment by schmm** [comment]
The error "Scheduled task cannot be created" occurs when a task already exists.
After deleting the existing task on the client, the agent was able to create the task without any problems.

How can I force the task to be overwritten on the other clients?
