### ISSUE TITLE
Feature request: Warranty Lookup

### ISSUE THREAD

**Issue by adamjrberry** [wh1te909/tacticalrmm#982]
I have looked but don't see a similar request already. I think it would be great in the future for TRMM to have a field showing warranty status of a machine. It looks like some people have managed to bodge a similar solution with Powershell scripts but there are lots of limitations to this. Other RMM vendors have integrated warranty checks into their systems so it would be awesome if TRMM could in future!

**Comment by dinger1986** [comment]
Bodged doesn't really do it justice as that's essentially what other RMMs have done they just display it differently.

Maybe your feature request is to display it on the machine or something?

**Comment by adamjrberry** [comment]
Hey - perhaps 'bodged' wasn't the right term to use... The reason I said that is because there was some scripts out there that became quickly redundant because of changes to HP, Dell, Lenovo lookups and their API changes. Through those changes, other RMMs have managed to consistently show the warranty status, so I assumed that there was another way, outside of a powershell script, to get this information. 
If anyone has a current working script, I'd really love to see it, as this is something I'm in need of. I'd like to just output the warranty expiry date to a custom field in TRMM.

**Comment by dinger1986** [comment]
Are the current community scripts not working with url actions?

There are countless ways to do it including powershell, doesn't mean ones better than the other is what I meant.

Keeping up with manufacturers etc will be an ever evolving front and with the scripts could be easier for the community to maintain rather than just the devs.

**Comment by silversword411** [comment]
That data is only stored on the manufacturers website/database once you look a machine up by SN right?

**Comment by adamjrberry** [comment]
Hey, thanks for the reply.
A community script would certainly do the job just fine if it works. I couldn't see one in the TRMM community scripts page, and the ones I found on other websites don't work any more.

Silversword, not sure quite what you mean? You can do a lookup of SN on the websites to get status, but it appears that the data is already there as previous scripts have managed to capture it.. That said, the ways of accessing the information seems to be ever changing.

**Comment by dinger1986** [comment]
so this one would work, you would collect your serial numbers, save them as custom fields then use the api to pull them out into an html page, or could put it back to notes or something:

https://www.cyberdrain.com/automating-with-powershell-automating-warranty-information-reporting/

**Comment by plao** [comment]
Nice feature! For me, absolutely +1!

**Comment by silversword411** [comment]
I'll look at the script for now

**Comment by dinger1986** [comment]
$serial = (gwmi win32_bios).SerialNumber
$brand = (gwmi win32_bios).Manufacturer

**Comment by silversword411** [comment]
Added to wip
