### ISSUE TITLE
Log 404 NOT FOUND for paths that don't exist

### ISSUE THREAD

**Issue by NiceGuyIT** [wh1te909/tacticalrmm#986]
**Is your feature request related to a problem? Please describe.**
The frontend (`rmm.example.com`) is logging HTTP 200 for paths that don't exist.

**Describe the solution you'd like**
I would like the server to conform to the standard HTTP codes and return a 404 if the path doesn't exist.

```text
$ curl --head https://rmm.a8n.tools/owa/auth/logon.aspx
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 23 Feb 2022 13:21:39 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 661
Last-Modified: Sun, 16 Jan 2022 14:29:56 GMT
Connection: keep-alive
ETag: "61e42be4-295"
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Accept-Ranges: bytes
```

Here's the nginx log for the above request.
```text
172.30.0.10 - - [23/Feb/2022:08:21:33 -0500] "GET /owa/auth/logon.aspx HTTP/1.1" 200 386 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
```

**Describe alternatives you've considered**
I've considered not reporting this.

**Additional context**
While researching a problem, I ran across logs showing HTTP 200 for `/owa/auth/logon.aspx`, a URL common to Outlook Web Access. This seems to imply the server is hacked and responding to a valid request. That is not the case, though, as that path doesn't exist on the server.

**Comment by silversword411** [comment]
Sounds like no options on this one. Closing, post if you find some workaround.

**Comment by NiceGuyIT** [comment]
For future reference. [How do I correctly deal with 404 HTTP errors when using an SPA and no server-side computation?](https://stackoverflow.com/questions/68495355/how-do-i-correctly-deal-with-404-http-errors-when-using-an-spa-and-no-server-sid)
