### ISSUE TITLE
Feature Request: Tasks depend on Tasks or Tasks depend on Checks or Checks depend on Tasks

### ISSUE THREAD

**Issue by JSuenram** [wh1te909/tacticalrmm#993]
For Example.... you Check if Firewall is enabled.... and if not fire a task that enabled Firewall.... Sure you can do all this in the Check, but not every example is like this.... Or Trigger Tasks on Checks and so on..... more flexibility what will be done if something else returns True or False without the need to put everything possible in a script....

I guess it will be more userfriendly....

**Comment by silversword411** [comment]
So if I understand this, you want as part of the script and task setup process if return of x do y.

Can this be done with script snippets now as part of your script?

**Comment by bc24fl** [comment]
Being able to run a script depending on the output of another is super powerful.  I've been thinking of this problem for some time now.  The only way to currently do this is by saving your output to Custom Fields and then using the API to run the next script but that can get sloppy pretty quick although doable.

**Comment by r3die** [comment]
This is something you may be able to with checks and setting exit codes in your scripts. 
For instance, I have a PS script as a check, when it finds something it ends with a certain exit code that TRMM check sees as a 'failure', then I have a dependent task that runs upon failure

**Comment by silversword411** [comment]
@JSuenram So there is already support for running a task (on check error) when a check fails (have check be a script with a return code). 

Will that do everything you're trying to do, or do we need to keep this issue open?

**Comment by silversword411** [comment]
Closing, will reopen if hear back
