### ISSUE TITLE
Scripts run thru bulk script doesn't appear in audit log

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#995]
Run script against individual agents. 
Check Audit log, doesn't reflect anything. Check History, you see the script run.

**Comment by sadnub** [comment]
When bulk actions are run, it will show in the audit log as a Bulk Action versus under the individual agents.

**Comment by silversword411** [comment]
> When bulk actions are run, it will show in the audit log as a Bulk Action versus under the individual agents.

This is how it's always worked?

Intuitively I'm expecting if something happens on the agent, it'll be in the agent history. Can we have it also show up there, not just in the server-wide audit log?
