### ISSUE TITLE
Feature Request: Event Log Check can only use Application, System and Security

### ISSUE THREAD

**Issue by JSuenram** [wh1te909/tacticalrmm#996]
Consider you want to monitor Eventlog vor NTLM-Auditing.
You need to look in "Microsoft-Windows-NTLM/Operational" which is not Possible with Event-Log-Check at the moment.

There are about 150 other EventLogs which are not written to Application/System or Security....
Currently you can not use them in TRMM.

**Comment by dinger1986** [comment]
you can with powershell, can look at the defender checks for reference

**Comment by silversword411** [comment]
You can use powershell to query any event log. Use this as example: 
https://github.com/amidaware/community-scripts/blob/main/scripts/Win_Defender_Status_Report.ps1

Closing
